[package]
name = "ww3d-assets"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
ww3d-core = { path = "../ww3d-core" }
ww3d-gpu = { path = "../ww3d-gpu" }
glam = {workspace = true, features = ["bytemuck"]}
binrw = {workspace = true}
tokio = {workspace = true, features = ["full"]}
thiserror = {workspace = true}
bytemuck = {workspace = true, features = ["derive"]}
wgpu = {workspace = true}
parking_lot = {workspace = true}

[dev-dependencies]
tempfile = {workspace = true}
anyhow = {workspace = true}
serde = {workspace = true, features = ["derive"]}
serde_json = {workspace = true}
