//! C++-style menu callback shims.

pub mod challenge_menu;
pub mod credits_menu;
pub mod disconnect_window;
pub mod download_menu;
pub mod establish_connections_window;
pub mod game_info_window;
pub mod keyboard_options_menu;
pub mod lan_game_options_menu;
pub mod lan_lobby_menu;
pub mod lan_map_select_menu;
pub mod main_menu;
pub mod map_select_menu;
#[cfg(feature = "online_ui")]
pub mod network_direct_connect;
pub mod options_menu;
pub mod popup_communicator;
#[cfg(feature = "online_ui")]
pub mod popup_host_game;
#[cfg(feature = "online_ui")]
pub mod popup_join_game;
#[cfg(feature = "online_ui")]
pub mod popup_ladder_select;
#[cfg(feature = "online_ui")]
pub mod popup_player_info;
pub mod popup_replay;
pub mod popup_save_load;
pub mod quit_menu;
pub mod replay_menu;
pub mod score_screen;
pub mod single_player_menu;
pub mod skirmish_game_options_menu;
pub mod skirmish_map_select_menu;
#[cfg(feature = "online_ui")]
pub mod wol_buddy_overlay;
#[cfg(feature = "online_ui")]
pub mod wol_custom_score_screen;
#[cfg(feature = "online_ui")]
pub mod wol_game_setup_menu;
#[cfg(feature = "online_ui")]
pub mod wol_ladder_screen;
#[cfg(feature = "online_ui")]
pub mod wol_lobby_menu;
#[cfg(feature = "online_ui")]
pub mod wol_locale_select_popup;
#[cfg(feature = "online_ui")]
pub mod wol_login_menu;
#[cfg(feature = "online_ui")]
pub mod wol_map_select_menu;
#[cfg(feature = "online_ui")]
pub mod wol_message_window;
#[cfg(feature = "online_ui")]
pub mod wol_quick_match_menu;
#[cfg(feature = "online_ui")]
pub mod wol_status_menu;
#[cfg(feature = "online_ui")]
pub mod wol_welcome_menu;
#[cfg(feature = "online_ui")]
pub mod wolqm_score_screen;
