[package]
name = "ww3d-game"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
ww3d-renderer-3d = { path = "../crates/ww3d-renderer-3d" }
ww3d-assets = { path = "../crates/ww3d-assets" }
ww3d-particles = { path = "../crates/ww3d-particles" }
ww3d-geometry = { path = "../crates/ww3d-geometry" }
ww3d-physics = { path = "../crates/ww3d-physics" }
ww3d-engine = { path = "../crates/ww3d-engine" }
glam = {workspace = true, features = ["bytemuck"]}
bytemuck = {workspace = true, features = ["derive"]}
winit = {workspace = true}
wgpu = {workspace = true}
tokio = {workspace = true, features = ["full"]}

[[bin]]
name = "main"
path = "src/main.rs"
