[package]
name = "ww3d-core"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
glam = {workspace = true, features = ["bytemuck"]}
thiserror = {workspace = true}
binrw = {workspace = true}
log = {workspace = true}
once_cell = {workspace = true}
slotmap = {workspace = true}

[dev-dependencies]
