//! GUI Callbacks System
//!
//! This module contains all the GUI callback functions and menu systems
//! that handle user interface interactions throughout the game.

pub mod challenge_menu;
pub mod control_bar_callbacks;
pub mod difficulty_select;
pub mod diplomacy;
pub mod download_menu;
pub mod game_info_window;
pub mod generals_exp_points;
pub mod ime_candidate;
pub mod in_game_popup_message;
pub mod ingame_callbacks;
pub mod keyboard_options_menu;
pub mod lan_game_options_menu;
pub mod lan_map_select_menu;
pub mod menu_callbacks;
pub mod message_box;
#[cfg(feature = "network")]
pub mod network_direct_connect;
#[cfg(not(feature = "network"))]
mod network_stubs;
pub mod popup_communicator;
#[cfg(feature = "network")]
pub mod popup_host_game;
#[cfg(feature = "network")]
pub mod popup_join_game;
#[cfg(feature = "network")]
pub mod popup_ladder_select;
#[cfg(feature = "network")]
pub mod popup_player_info;
pub mod popup_replay;
pub mod popup_save_load;
pub mod quit_menu;
pub mod replay_controls;
pub mod replay_menu;
pub mod score_screen;
pub mod skirmish_game_options_menu;
pub mod skirmish_map_select_menu;
#[cfg(feature = "network")]
pub mod wol_buddy_overlay;
#[cfg(feature = "network")]
pub mod wol_custom_score_screen;
#[cfg(feature = "network")]
pub mod wol_game_setup_menu;
#[cfg(feature = "network")]
pub mod wol_ladder_screen;
#[cfg(feature = "network")]
pub mod wol_lobby_menu;
#[cfg(feature = "network")]
pub mod wol_locale_select_popup;
#[cfg(feature = "network")]
pub mod wol_login_menu;
#[cfg(feature = "network")]
pub mod wol_map_select_menu;
#[cfg(feature = "network")]
pub mod wol_message_window;
#[cfg(feature = "network")]
pub mod wol_quick_match_menu;
#[cfg(feature = "network")]
pub mod wol_status_menu;
#[cfg(feature = "network")]
pub mod wol_welcome_menu;
#[cfg(feature = "network")]
pub mod wolqm_score_screen;

// Re-export main types
pub use challenge_menu::*;
pub use control_bar_callbacks::*;
pub use difficulty_select::*;
pub use diplomacy::*;
pub use download_menu::*;
pub use game_info_window::*;
pub use generals_exp_points::*;
pub use ime_candidate::*;
pub use in_game_popup_message::*;
pub use ingame_callbacks::*;
pub use keyboard_options_menu::*;
pub use lan_game_options_menu::*;
pub use lan_map_select_menu::*;
pub use menu_callbacks::*;
pub use message_box::*;
#[cfg(feature = "network")]
pub use network_direct_connect::*;
#[cfg(not(feature = "network"))]
pub use network_stubs::*;
pub use popup_communicator::*;
#[cfg(feature = "network")]
pub use popup_host_game::*;
#[cfg(feature = "network")]
pub use popup_join_game::*;
#[cfg(feature = "network")]
pub use popup_ladder_select::*;
#[cfg(feature = "network")]
pub use popup_player_info::*;
pub use popup_replay::*;
pub use popup_save_load::*;
pub use quit_menu::*;
pub use replay_controls::*;
pub use replay_menu::*;
pub use score_screen::*;
pub use skirmish_game_options_menu::*;
pub use skirmish_map_select_menu::*;
#[cfg(feature = "network")]
pub use wol_buddy_overlay::*;
#[cfg(feature = "network")]
pub use wol_custom_score_screen::*;
#[cfg(feature = "network")]
pub use wol_game_setup_menu::*;
#[cfg(feature = "network")]
pub use wol_ladder_screen::*;
#[cfg(feature = "network")]
pub use wol_lobby_menu::*;
#[cfg(feature = "network")]
pub use wol_locale_select_popup::*;
#[cfg(feature = "network")]
pub use wol_login_menu::*;
#[cfg(feature = "network")]
pub use wol_map_select_menu::*;
#[cfg(feature = "network")]
pub use wol_message_window::*;
#[cfg(feature = "network")]
pub use wol_quick_match_menu::*;
#[cfg(feature = "network")]
pub use wol_status_menu::*;
#[cfg(feature = "network")]
pub use wol_welcome_menu::*;
#[cfg(feature = "network")]
pub use wolqm_score_screen::*;
