[package]
name = "ww3d-engine"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license = "GPL-3.0-or-later"
publish = false

[dependencies]
ww3d-gpu = { path = "../ww3d-gpu" }
ww3d-core = { path = "../ww3d-core" }
wgpu = { workspace = true }
once_cell = {workspace = true}
parking_lot = {workspace = true}
thiserror = {workspace = true}
log = {workspace = true}
pollster = {workspace = true}
png = {workspace = true}
glam = {workspace = true}
