use super::*;
use crate::wwfile::{FileRights, WWFile};

// Generated by compiling the original chunkio.cpp unchanged. See the adjacent
// provenance JSON and tests/oracles/generate_chunkio_fixtures.py. This covers
// writer framing and raw-buffer Read; C++'s pointer-sized typed-load overloads
// are a separate unresolved contract (hq-zr5ih).
const CPP_NESTED: &[u8] = include_bytes!("../tests/fixtures/chunkio_cpp_nested.bin");
const CPP_PARTIAL: &[u8] = include_bytes!("../tests/fixtures/chunkio_cpp_partial.bin");

fn input(bytes: &[u8]) -> (tempfile::TempDir, WWFile) {
    let directory = tempfile::tempdir().unwrap();
    let path = directory.path().join("chunks.bin");
    std::fs::write(&path, bytes).unwrap();
    let mut file = WWFile::with_path(path);
    file.open(FileRights::Read).unwrap();
    (directory, file)
}

fn vectors() -> (
    IOVector2Struct,
    IOVector3Struct,
    IOVector4Struct,
    IOQuaternionStruct,
) {
    (
        IOVector2Struct { x: 1.25, y: -0.0 },
        IOVector3Struct {
            x: f32::from_bits(0x7fc12345),
            y: -2.5,
            z: 3.0,
        },
        IOVector4Struct {
            x: -1.0,
            y: f32::INFINITY,
            z: f32::NEG_INFINITY,
            w: f32::from_bits(0x7fc54321),
        },
        IOQuaternionStruct {
            q: [0.0, 0.5, -0.5, 1.0],
        },
    )
}

#[test]
fn writer_matches_original_cpp_nested_headers_micro_chunks_and_float_bits() {
    let directory = tempfile::tempdir().unwrap();
    let path = directory.path().join("chunks.bin");
    let mut file = WWFile::with_path(&path);
    file.open(FileRights::ReadWrite).unwrap();
    let (v2, v3, v4, quat) = vectors();
    {
        let mut save = ChunkSaveClass::new(&mut file);
        assert!(save.begin_chunk(0x11223344));
        assert!(save.begin_chunk(0xaabbccdd));
        assert_eq!(save.write_vec2(&v2), 8);
        assert_eq!(save.write_vec3(&v3), 12);
        assert_eq!(save.write_vec4(&v4), 16);
        assert_eq!(save.write_quat(&quat), 16);
        assert!(save.end_chunk());
        assert!(save.begin_chunk(0x10203040));
        assert!(save.begin_micro_chunk(0x7e));
        assert_eq!(save.write(&[0x10, 0x20, 0x30]), 3);
        assert!(save.end_micro_chunk());
        assert!(save.end_chunk());
        assert!(save.end_chunk());
        assert_eq!(save.cur_chunk_depth(), 0);
    }
    file.close().unwrap();
    assert_eq!(std::fs::read(path).unwrap(), CPP_NESTED);
}

#[test]
fn loads_original_cpp_fixture_with_current_rust_typed_read_contract() {
    let (_directory, mut file) = input(CPP_NESTED);
    let mut load = ChunkLoadClass::new(&mut file);
    assert!(load.open_chunk());
    assert_eq!(load.cur_chunk_id(), 0x11223344);
    assert_eq!(load.contains_chunks(), 1);
    assert!(load.open_chunk());
    assert_eq!(load.cur_chunk_id(), 0xaabbccdd);
    assert_eq!(load.cur_chunk_length(), 52);
    let (v2, v3, v4, quat) = vectors();
    let mut actual2 = IOVector2Struct::default();
    let mut actual3 = IOVector3Struct::default();
    let mut actual4 = IOVector4Struct::default();
    let mut actualq = IOQuaternionStruct::default();
    assert_eq!(load.read_vec2(&mut actual2), 8);
    assert_eq!(load.read_vec3(&mut actual3), 12);
    assert_eq!(load.read_vec4(&mut actual4), 16);
    assert_eq!(load.read_quat(&mut actualq), 16);
    assert_eq!(
        [actual2.x.to_bits(), actual2.y.to_bits()],
        [v2.x.to_bits(), v2.y.to_bits()]
    );
    assert_eq!(
        [
            actual3.x.to_bits(),
            actual3.y.to_bits(),
            actual3.z.to_bits()
        ],
        [v3.x.to_bits(), v3.y.to_bits(), v3.z.to_bits()]
    );
    assert_eq!(
        [
            actual4.x.to_bits(),
            actual4.y.to_bits(),
            actual4.z.to_bits(),
            actual4.w.to_bits()
        ],
        [
            v4.x.to_bits(),
            v4.y.to_bits(),
            v4.z.to_bits(),
            v4.w.to_bits()
        ]
    );
    assert_eq!(actualq.q.map(f32::to_bits), quat.q.map(f32::to_bits));
    assert!(load.close_chunk());
    assert!(load.open_chunk());
    assert_eq!(load.cur_chunk_id(), 0x10203040);
    assert!(load.open_micro_chunk());
    assert_eq!(load.cur_micro_chunk_id(), 0x7e);
    assert_eq!(load.cur_micro_chunk_length(), 3);
    let mut payload = [0; 3];
    assert_eq!(load.read(&mut payload), 3);
    assert_eq!(payload, [0x10, 0x20, 0x30]);
    assert!(load.close_micro_chunk());
    assert!(load.close_chunk());
    assert!(!load.open_chunk());
    assert!(load.close_chunk());
    assert_eq!(load.cur_chunk_depth(), 0);
}

#[test]
fn short_reads_preserve_the_cpp_written_prefix_and_unread_float_bits() {
    for count in 0..16 {
        let mut bytes = vec![9, 0, 0, 0, 16, 0, 0, 0];
        bytes.extend_from_slice(&CPP_NESTED[36..36 + count]);
        let (_directory, mut file) = input(&bytes);
        let mut load = ChunkLoadClass::new(&mut file);
        assert!(load.open_chunk());
        let mut value = IOVector4Struct {
            x: 1.25,
            y: -2.5,
            z: 3.0,
            w: 4.0,
        };
        assert_eq!(load.read_vec4(&mut value), 0);
        let actual: Vec<_> = [value.x, value.y, value.z, value.w]
            .into_iter()
            .flat_map(f32::to_le_bytes)
            .collect();
        assert_eq!(
            actual,
            CPP_PARTIAL[count * 16..(count + 1) * 16],
            "short length {count}"
        );
        assert_eq!(load.position_stack[0], 0);
    }
}

#[test]
fn rejected_reads_leave_values_and_stream_position_unchanged() {
    let (_directory, mut file) = input(&[9, 0, 0, 0, 4, 0, 0, 0, 1, 2, 3, 4]);
    let mut load = ChunkLoadClass::new(&mut file);
    assert!(load.open_chunk());
    let mut value = IOVector2Struct {
        x: -0.0,
        y: f32::from_bits(0x7fc12345),
    };
    assert_eq!(load.read_vec2(&mut value), 0);
    assert_eq!(value.x.to_bits(), 0x80000000);
    assert_eq!(value.y.to_bits(), 0x7fc12345);
    let mut payload = [0; 4];
    assert_eq!(load.read(&mut payload), 4);
    assert_eq!(payload, [1, 2, 3, 4]);
}

#[test]
fn truncated_headers_never_admit_a_chunk() {
    for length in 0..8 {
        let (_directory, mut file) = input(&CPP_NESTED[..length]);
        let mut load = ChunkLoadClass::new(&mut file);
        assert!(!load.open_chunk());
        assert_eq!(load.cur_chunk_depth(), 0);
    }
}
