//! Constants mirroring WWDownload `downloaddefs.h`.

const SEVERITY_ERROR: u32 = 1;
const FACILITY_ITF: u32 = 4;

const fn make_hresult(severity: u32, facility: u32, code: u32) -> u32 {
    (severity << 31) | (facility << 16) | code
}

pub const DOWNLOADSTATUS_NONE: u32 = 0;
pub const DOWNLOADSTATUS_GO: u32 = 1;
pub const DOWNLOADSTATUS_CONNECTING: u32 = 2;
pub const DOWNLOADSTATUS_LOGGINGIN: u32 = 3;
pub const DOWNLOADSTATUS_FINDINGFILE: u32 = 4;
pub const DOWNLOADSTATUS_QUERYINGRESUME: u32 = 5;
pub const DOWNLOADSTATUS_DOWNLOADING: u32 = 6;
pub const DOWNLOADSTATUS_DISCONNECTING: u32 = 7;
pub const DOWNLOADSTATUS_FINISHING: u32 = 8;
pub const DOWNLOADSTATUS_DONE: u32 = 0;

pub const DOWNLOAD_SUCCEEDED: u32 = 0;
pub const DOWNLOAD_PARAMERROR: u32 = make_hresult(SEVERITY_ERROR, FACILITY_ITF, 1);
pub const DOWNLOAD_STATUSERROR: u32 = make_hresult(SEVERITY_ERROR, FACILITY_ITF, 2);
pub const DOWNLOAD_NETWORKERROR: u32 = make_hresult(SEVERITY_ERROR, FACILITY_ITF, 3);
pub const DOWNLOAD_FILEERROR: u32 = make_hresult(SEVERITY_ERROR, FACILITY_ITF, 4);
pub const DOWNLOAD_REENTERERROR: u32 = make_hresult(SEVERITY_ERROR, FACILITY_ITF, 4);

pub const DOWNLOADEVENT_SUCCEEDED: u32 = 0;
pub const DOWNLOADEVENT_FAILED: u32 = make_hresult(SEVERITY_ERROR, FACILITY_ITF, 5);
pub const DOWNLOADEVENT_RESUME: u32 = 0;
pub const DOWNLOADEVENT_DONOTRESUME: u32 = make_hresult(SEVERITY_ERROR, FACILITY_ITF, 6);

pub const DOWNLOADEVENT_NOSUCHSERVER: u32 = 1;
pub const DOWNLOADEVENT_COULDNOTCONNECT: u32 = 2;
pub const DOWNLOADEVENT_LOGINFAILED: u32 = 3;
pub const DOWNLOADEVENT_NOSUCHFILE: u32 = 4;
pub const DOWNLOADEVENT_LOCALFILEOPENFAILED: u32 = 5;
pub const DOWNLOADEVENT_TCPERROR: u32 = 6;
pub const DOWNLOADEVENT_DISCONNECTERROR: u32 = 7;
