/*****************************************************************
*
*	Project:		3DTEST1 (3d Test Program)
*
*	File:			bittype.h
*
*	Start Date:		Dec 18, 1996
*
*	Programmer:		Greg Hjelstrom
*
*****************************************************************/

#ifndef BITTYPE_H
#define BITTYPE_H

typedef unsigned char	uint8;
typedef unsigned short	uint16;
typedef unsigned long	uint32;

typedef signed char		sint8;
typedef signed short	sint16;
typedef signed long		sint32;

typedef float			float32;
typedef double			float64;


#endif //BITTYPE_H