[package]
name = "big_unpack"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[lib]
name = "big_unpack"
path = "src/lib.rs"

[[bin]]
name = "big_unpack"
path = "src/main.rs"

[dependencies]
anyhow = {workspace = true}
clap = {workspace = true, features = ["derive"]}
walkdir = {workspace = true}
