[package]
name = "wwlib-rust"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[features]
default = []
internal = []

[dependencies]
rand = {workspace = true, features = ["std_rng"]}
tokio = {workspace = true, features = ["full"]}
thiserror = {workspace = true}
serde = {workspace = true, features = ["derive"]}
serde_json = {workspace = true}
chrono = {workspace = true, features = ["serde"]}
log = {workspace = true}
base_types = { path = "base_types" }
memory_system = { path = "memory_system" }
string_system = { path = "string_system" }
ini_parser = { path = "ini_parser" }
base64 = {workspace = true}
regex = {workspace = true}
rsa = {workspace = true}
num-bigint = {workspace = true}
num-integer = {workspace = true}
num-traits = {workspace = true}

[dev-dependencies]
tempfile = {workspace = true}

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = [
  "Win32_Foundation",
  "Win32_Storage_FileSystem",
  "Win32_System_Registry",
  "Win32_System_SystemServices",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_WindowsAndMessaging",
] }
