//! Auto-generated module list for W3DDevice GameClient
pub mod atmospheric_fog;
pub mod camerashakesystem;
pub mod complete_sky_system;
#[path = "Drawable/mod.rs"]
pub mod drawable;
pub mod fow_terrain_overlay;
#[path = "GUI/mod.rs"]
pub mod gui;
#[path = "Module/mod.rs"]
pub mod module;
pub mod projectile_stream_bridge;
#[path = "Shadow/mod.rs"]
pub mod shadow;
pub mod sky_rendering;
pub mod sun_system;
pub mod terrain_lod;
pub mod terrain_rendering;
pub mod terrain_system;
pub mod terrain_tex;
pub mod terrain_texture;
pub mod w3d_waypoint_buffer;
#[path = "Water/mod.rs"]
pub mod water;
pub mod wthree_d_asset_manager;
pub mod wthree_d_asset_manager_exposed;
pub mod wthree_d_bib_buffer;
pub mod wthree_d_bridge_buffer;
pub mod wthree_d_buffer_manager;
pub mod wthree_d_debug_display;
pub mod wthree_d_display;
pub mod wthree_d_display_string;
pub mod wthree_d_display_string_manager;
pub mod wthree_d_dynamic_light;
pub mod wthree_d_file_system;
pub mod wthree_d_gadget;
pub mod wthree_d_game_font;
pub mod wthree_d_game_window;
pub mod wthree_d_game_window_manager;
pub mod wthree_d_gui_callbacks;
pub mod wthree_d_particle_sys;
pub mod wthree_d_prop_buffer;
pub mod wthree_d_road_buffer;
pub mod wthree_d_scene;
pub mod wthree_d_scene_submission;
pub mod wthree_d_segmented_line;
pub mod wthree_d_shader_manager;
pub mod wthree_d_shadow;
pub mod wthree_d_shroud;
pub mod wthree_d_snow;
pub mod wthree_d_terrain_background;
pub mod wthree_d_terrain_tracks;
pub mod wthree_d_terrain_visual;
pub mod wthree_d_tree_buffer;
pub mod wthree_d_video_buffer;
pub mod wthree_d_videobuffer;
pub mod wthree_d_view;
pub mod wthree_d_volumetric_shadow;
pub mod wthree_d_water;
pub mod wthree_d_water_tracks;
pub mod wthree_d_waypoint_buffer;
