#![allow(
    unused_imports,
    unused_variables,
    dead_code,
    non_snake_case,
    unreachable_patterns
)]
use super::*;

mod campaign_menus;
mod dialogs;
mod gameplay;
mod gameplay_orders;
mod gameplay_select;
mod hud_bar;
mod live_commands;
mod live_gates_a;
mod live_gates_b;
mod live_gates_c;
mod live_presentation;
mod live_probes;
mod overlay_clicks;
mod shell_core;
mod skirmish;

impl CnCGameEngine {
    pub(super) fn apply_runtime_host_command(&mut self, raw_command: &str) {
        let mut parts = raw_command.split('|');
        let command = parts.next().unwrap_or_default().trim().to_ascii_lowercase();
        if command.is_empty() {
            return;
        }

        let mut args = HashMap::<String, String>::new();
        for part in parts {
            if let Some((key, value)) = part.split_once('=') {
                args.insert(
                    key.trim().to_ascii_lowercase(),
                    value.trim().trim_matches('"').to_string(),
                );
            }
        }

        match command.as_str() {
            "exit" => self.runtime_host_cmd_exit(&args),
            "menu" | "quit_to_menu" | "exit_to_menu" => self.runtime_host_cmd_menu(&args),
            "toggle_pause" | "pause" => self.runtime_host_cmd_toggle_pause(&args),
            "open_message_of_the_day" | "open_motd" => self.runtime_host_cmd_open_message_of_the_day(&args),
            "open_get_updates" | "open_updates" => self.runtime_host_cmd_open_get_updates(&args),
            "open_world_builder" | "launch_world_builder" => self.runtime_host_cmd_open_world_builder(&args),
            "options_probe" => self.runtime_host_cmd_options_probe(&args),
            "open_options" | "options" => self.runtime_host_cmd_open_options(&args),
            "open_credits" => self.runtime_host_cmd_open_credits(&args),
            "click_credits_menu" => self.runtime_host_cmd_click_credits_menu(&args),
            "show_message_box" => self.runtime_host_cmd_show_message_box(&args),
            "click_message_box" => self.runtime_host_cmd_click_message_box(&args),
            "toggle_diplomacy" => self.runtime_host_cmd_toggle_diplomacy(&args),
            "click_diplomacy" => self.runtime_host_cmd_click_diplomacy(&args),
            "open_popup_replay" => self.runtime_host_cmd_open_popup_replay(&args),
            "click_popup_replay" => self.runtime_host_cmd_click_popup_replay(&args),
            "open_single_player_menu" => self.runtime_host_cmd_open_single_player_menu(&args),
            "click_single_player_menu" => self.runtime_host_cmd_click_single_player_menu(&args),
            "open_map_select_menu" => self.runtime_host_cmd_open_map_select_menu(&args),
            "click_map_select_menu" => self.runtime_host_cmd_click_map_select_menu(&args),
            "toggle_control_bar" => self.runtime_host_cmd_toggle_control_bar(&args),
            "click_control_bar" => self.runtime_host_cmd_click_control_bar(&args),
            "open_single_player_menu" => self.runtime_host_cmd_open_single_player_menu_2(&args),
            "open_multiplayer_menu" => self.runtime_host_cmd_open_multiplayer_menu(&args),
            "open_load_replay_menu" => self.runtime_host_cmd_open_load_replay_menu(&args),
            "click_replay_menu" => self.runtime_host_cmd_click_replay_menu(&args),
            "toggle_quit_menu" => self.runtime_host_cmd_toggle_quit_menu(&args),
            "click_quit_menu" => self.runtime_host_cmd_click_quit_menu(&args),
            "open_keyboard_options" => self.runtime_host_cmd_open_keyboard_options(&args),
            "click_keyboard_options" => self.runtime_host_cmd_click_keyboard_options(&args),
            "open_score_screen" => self.runtime_host_cmd_open_score_screen(&args),
            "click_score_screen" => self.runtime_host_cmd_click_score_screen(&args),
            "open_options_menu" => self.runtime_host_cmd_open_options_menu(&args),
            "click_options_menu" => self.runtime_host_cmd_click_options_menu(&args),
            "open_difficulty_menu" => self.runtime_host_cmd_open_difficulty_menu(&args),
            "click_difficulty_select" => self.runtime_host_cmd_click_difficulty_select(&args),
            "show_loading_screen" => self.runtime_host_cmd_show_loading_screen(&args),
            "click_loading_screen" => self.runtime_host_cmd_click_loading_screen(&args),
            "toggle_in_game_chat" => self.runtime_host_cmd_toggle_in_game_chat(&args),
            "click_in_game_chat" => self.runtime_host_cmd_click_in_game_chat(&args),
            "click_idle_worker" => self.runtime_host_cmd_click_idle_worker(&args),
            "open_generals_exp" => self.runtime_host_cmd_open_generals_exp(&args),
            "click_generals_exp" => self.runtime_host_cmd_click_generals_exp(&args),
            "open_popup_communicator" => self.runtime_host_cmd_open_popup_communicator(&args),
            "click_popup_communicator" => self.runtime_host_cmd_click_popup_communicator(&args),
            "click_replay_control" => self.runtime_host_cmd_click_replay_control(&args),
            "toggle_shell_map" => self.runtime_host_cmd_toggle_shell_map(&args),
            "click_shell_map" => self.runtime_host_cmd_click_shell_map(&args),
            "click_beacon" => self.runtime_host_cmd_click_beacon(&args),
            "click_eva" => self.runtime_host_cmd_click_eva(&args),
            "click_ime" => self.runtime_host_cmd_click_ime(&args),
            "click_smudge" => self.runtime_host_cmd_click_smudge(&args),
            "click_ocl_timer" => self.runtime_host_cmd_click_ocl_timer(&args),
            "click_control_bar_resizer" => self.runtime_host_cmd_click_control_bar_resizer(&args),
            "click_under_construction" => self.runtime_host_cmd_click_under_construction(&args),
            "click_structure_inventory" => self.runtime_host_cmd_click_structure_inventory(&args),
            "click_multi_select" => self.runtime_host_cmd_click_multi_select(&args),
            "click_credits_roll" => self.runtime_host_cmd_click_credits_roll(&args),
            "click_challenge_generals" => self.runtime_host_cmd_click_challenge_generals(&args),
            "click_gameworld_authority" => self.runtime_host_cmd_click_gameworld_authority(&args),
            "click_window_video" => self.runtime_host_cmd_click_window_video(&args),
            "click_main_menu_layout" => self.runtime_host_cmd_click_main_menu_layout(&args),
            "click_control_bar_scheme" => self.runtime_host_cmd_click_control_bar_scheme(&args),
            "click_presentation_boundary" => self.runtime_host_cmd_click_presentation_boundary(&args),
            "click_control_bar_print_positions" => self.runtime_host_cmd_click_control_bar_print_positions(&args),
            "click_terrain_env_boundary" => self.runtime_host_cmd_click_terrain_env_boundary(&args),
            "click_main_menu_wnd" => self.runtime_host_cmd_click_main_menu_wnd(&args),
            "click_shell_stack" => self.runtime_host_cmd_click_shell_stack(&args),
            "click_shell_skirmish_nav" => self.runtime_host_cmd_click_shell_skirmish_nav(&args),
            "click_campaign_start" => self.runtime_host_cmd_click_campaign_start(&args),
            "open_skirmish_menu" => self.runtime_host_cmd_open_skirmish_menu(&args),
            "click_skirmish_start" => self.runtime_host_cmd_click_skirmish_start(&args),
            "click_skirmish_options_wnd" => self.runtime_host_cmd_click_skirmish_options_wnd(&args),
            "open_load_game" => self.runtime_host_cmd_open_load_game(&args),
            "click_save_load" => self.runtime_host_cmd_click_save_load(&args),
            "open_online" => self.runtime_host_cmd_open_online(&args),
            "open_network" => self.runtime_host_cmd_open_network(&args),
            "open_replay" => self.runtime_host_cmd_open_replay(&args),
            "open_challenge_menu" => self.runtime_host_cmd_open_challenge_menu(&args),
            "click_challenge_start" => self.runtime_host_cmd_click_challenge_start(&args),
            "start_game" => self.runtime_host_cmd_start_game(&args),
            "queue_new_game" => self.runtime_host_cmd_queue_new_game(&args),
            "click_new_game_stream" => self.runtime_host_cmd_click_new_game_stream(&args),
            "click_w3d_main_menu_init" => self.runtime_host_cmd_click_w3d_main_menu_init(&args),
            "click_start_game_loading" => self.runtime_host_cmd_click_start_game_loading(&args),
            "click_live_map_load" => self.runtime_host_cmd_click_live_map_load(&args),
            "click_live_presentation_seed" => self.runtime_host_cmd_click_live_presentation_seed(&args),
            "click_live_gameworld_shadow" => self.runtime_host_cmd_click_live_gameworld_shadow(&args),
            "click_single_authority" => self.runtime_host_cmd_click_single_authority(&args),
            "click_presentation_client_boundary" => self.runtime_host_cmd_click_presentation_client_boundary(&args),
            "click_golden_map_host_victory" => self.runtime_host_cmd_click_golden_map_host_victory(&args),
            "click_executable_presentation_boundary" => self.runtime_host_cmd_click_executable_presentation_boundary(&args),
            "click_gameworld_production_authority" => self.runtime_host_cmd_click_gameworld_production_authority(&args),
            "click_gameworld_sole_tick_coupling" => self.runtime_host_cmd_click_gameworld_sole_tick_coupling(&args),
            "click_gameworld_authority_matrix" => self.runtime_host_cmd_click_gameworld_authority_matrix(&args),
            "click_live_gameworld_production_writeback" => self.runtime_host_cmd_click_live_gameworld_production_writeback(&args),
            "click_live_gameworld_construction_writeback" => self.runtime_host_cmd_click_live_gameworld_construction_writeback(&args),
            "click_live_gameworld_damage_channel" => self.runtime_host_cmd_click_live_gameworld_damage_channel(&args),
            "click_live_gameworld_economy_movement" => self.runtime_host_cmd_click_live_gameworld_economy_movement(&args),
            "click_live_gameworld_projectile_ai" => self.runtime_host_cmd_click_live_gameworld_projectile_ai(&args),
            "click_live_gameworld_fire_special_power" => self.runtime_host_cmd_click_live_gameworld_fire_special_power(&args),
            "click_live_gameworld_presentation_view" => self.runtime_host_cmd_click_live_gameworld_presentation_view(&args),
            "click_live_presentation_gameworld_overlay" => self.runtime_host_cmd_click_live_presentation_gameworld_overlay(&args),
            "click_executable_gameworld_presentation" => self.runtime_host_cmd_click_executable_gameworld_presentation(&args),
            "click_live_presentation_overlay_deepen" => self.runtime_host_cmd_click_live_presentation_overlay_deepen(&args),
            "click_live_presentation_overlay_stamp" => self.runtime_host_cmd_click_live_presentation_overlay_stamp(&args),
            "click_live_gameworld_entity_view_deepen" => self.runtime_host_cmd_click_live_gameworld_entity_view_deepen(&args),
            "click_live_presentation_append_missing" => self.runtime_host_cmd_click_live_presentation_append_missing(&args),
            "click_live_presentation_build_from_gameworld" => self.runtime_host_cmd_click_live_presentation_build_from_gameworld(&args),
            "click_live_presentation_from_gameworld_default" => self.runtime_host_cmd_click_live_presentation_from_gameworld_default(&args),
            "click_live_presentation_build_for_engine" => self.runtime_host_cmd_click_live_presentation_build_for_engine(&args),
            "click_live_presentation_rebuilt_vertical_gate" => self.runtime_host_cmd_click_live_presentation_rebuilt_vertical_gate(&args),
            "click_live_command_attack_log" => self.runtime_host_cmd_click_live_command_attack_log(&args),
            "click_live_command_guard_log" => self.runtime_host_cmd_click_live_command_guard_log(&args),
            "click_live_command_production_construction_log" => self.runtime_host_cmd_click_live_command_production_construction_log(&args),
            "click_live_command_rally_log" => self.runtime_host_cmd_click_live_command_rally_log(&args),
            "click_live_evacuate_contain_log" => self.runtime_host_cmd_click_live_evacuate_contain_log(&args),
            "click_live_command_cheer_science_log" => self.runtime_host_cmd_click_live_command_cheer_science_log(&args),
            "click_live_command_deploy_status_log" => self.runtime_host_cmd_click_live_command_deploy_status_log(&args),
            "click_live_command_formation_log" => self.runtime_host_cmd_click_live_command_formation_log(&args),
            "click_live_command_order_target_log" => self.runtime_host_cmd_click_live_command_order_target_log(&args),
            "click_live_command_selection_log" => self.runtime_host_cmd_click_live_command_selection_log(&args),
            "click_live_command_non_attack_order_target" => self.runtime_host_cmd_click_live_command_non_attack_order_target(&args),
            "click_live_golden_mopup_default_off" => self.runtime_host_cmd_click_live_golden_mopup_default_off(&args),
            "click_live_die_command_dual_world_empty_gate" => self.runtime_host_cmd_click_live_die_command_dual_world_empty_gate(&args),
            "click_live_upgrade_behavior_dual_world_empty_gate" => self.runtime_host_cmd_click_live_upgrade_behavior_dual_world_empty_gate(&args),
            "click_live_construction_placement_dual_world_empty_gate" => self.runtime_host_cmd_click_live_construction_placement_dual_world_empty_gate(&args),
            "click_live_presentation_env_only" => self.runtime_host_cmd_click_live_presentation_env_only(&args),
            "click_live_os_input_command_path" => self.runtime_host_cmd_click_live_os_input_command_path(&args),
            "click_live_command_beacon_note" => self.runtime_host_cmd_click_live_command_beacon_note(&args),
            "click_live_host_beacon_presentation" => self.runtime_host_cmd_click_live_host_beacon_presentation(&args),
            "click_live_command_sell_deselect_log" => self.runtime_host_cmd_click_live_command_sell_deselect_log(&args),
            "click_live_presentation_fow_only" => self.runtime_host_cmd_click_live_presentation_fow_only(&args),
            "click_live_ui_producer_presentation_only" => self.runtime_host_cmd_click_live_ui_producer_presentation_only(&args),
            "click_live_ui_helpers_presentation_only" => self.runtime_host_cmd_click_live_ui_helpers_presentation_only(&args),
            "click_live_control_group_camera_presentation_only" => self.runtime_host_cmd_click_live_control_group_camera_presentation_only(&args),
            "click_live_cmd_filter_env_presentation_only" => self.runtime_host_cmd_click_live_cmd_filter_env_presentation_only(&args),
            "click_live_selection_commands_presentation_only" => self.runtime_host_cmd_click_live_selection_commands_presentation_only(&args),
            "click_live_ui_command_selection_presentation_only" => self.runtime_host_cmd_click_live_ui_command_selection_presentation_only(&args),
            "click_live_local_team_presentation_only" => self.runtime_host_cmd_click_live_local_team_presentation_only(&args),
            "click_live_hotkey_move_attack_selection_presentation_only" => self.runtime_host_cmd_click_live_hotkey_move_attack_selection_presentation_only(&args),
            "click_live_pick_object_presentation_only" => self.runtime_host_cmd_click_live_pick_object_presentation_only(&args),
            "click_live_bootstrap_camera_presentation_only" => self.runtime_host_cmd_click_live_bootstrap_camera_presentation_only(&args),
            "click_live_force_complete_authority_api" => self.runtime_host_cmd_click_live_force_complete_authority_api(&args),
            "click_live_path_guard_authority_api" => self.runtime_host_cmd_click_live_path_guard_authority_api(&args),
            "click_live_hotkey_selection_camera_presentation_only" => self.runtime_host_cmd_click_live_hotkey_selection_camera_presentation_only(&args),
            "click_live_construct_spawn_pose_authority_api" => self.runtime_host_cmd_click_live_construct_spawn_pose_authority_api(&args),
            "click_live_rmb_target_presentation_only" => self.runtime_host_cmd_click_live_rmb_target_presentation_only(&args),
            "click_live_rmb_selected_presentation_only" => self.runtime_host_cmd_click_live_rmb_selected_presentation_only(&args),
            "click_live_command_unit_authority_api" => self.runtime_host_cmd_click_live_command_unit_authority_api(&args),
            "click_live_command_unit_more_authority_api" => self.runtime_host_cmd_click_live_command_unit_more_authority_api(&args),
            "click_live_command_executor_authority_api" => self.runtime_host_cmd_click_live_command_executor_authority_api(&args),
            "click_live_command_executor_more_authority_api" => self.runtime_host_cmd_click_live_command_executor_more_authority_api(&args),
            "click_live_engine_presentation_player_ui" => self.runtime_host_cmd_click_live_engine_presentation_player_ui(&args),
            "click_live_rmb_presentation_full_classify" => self.runtime_host_cmd_click_live_rmb_presentation_full_classify(&args),
            "click_live_mouse_input_presentation_only" => self.runtime_host_cmd_click_live_mouse_input_presentation_only(&args),
            "click_live_engine_player_ui_boot_peel" => self.runtime_host_cmd_click_live_engine_player_ui_boot_peel(&args),
            "click_live_player_probe_api" => self.runtime_host_cmd_click_live_player_probe_api(&args),
            "click_live_player_team_probe" => self.runtime_host_cmd_click_live_player_team_probe(&args),
            "click_live_player_field_probe" => self.runtime_host_cmd_click_live_player_field_probe(&args),
            "click_live_camera_height_probe" => self.runtime_host_cmd_click_live_camera_height_probe(&args),
            "click_live_command_player_probe" => self.runtime_host_cmd_click_live_command_player_probe(&args),
            "click_live_construct_economy_probe" => self.runtime_host_cmd_click_live_construct_economy_probe(&args),
            "click_live_command_unit_probe" => self.runtime_host_cmd_click_live_command_unit_probe(&args),
            "click_live_selection_query_probe" => self.runtime_host_cmd_click_live_selection_query_probe(&args),
            "click_live_world_pick_probe" => self.runtime_host_cmd_click_live_world_pick_probe(&args),
            "click_live_object_registry_empty_fastpath" => self.runtime_host_cmd_click_live_object_registry_empty_fastpath(&args),
            "click_live_legacy_object_registry_fastpath" => self.runtime_host_cmd_click_live_legacy_object_registry_fastpath(&args),
            "click_live_client_dual_world_empty_gate" => self.runtime_host_cmd_click_live_client_dual_world_empty_gate(&args),
            "click_live_presentation_time_frozen_probe" => self.runtime_host_cmd_click_live_presentation_time_frozen_probe(&args),
            "click_live_presentation_visual_speed_probe" => self.runtime_host_cmd_click_live_presentation_visual_speed_probe(&args),
            "click_live_presentation_script_camera_probe" => self.runtime_host_cmd_click_live_presentation_script_camera_probe(&args),
            "click_live_ai_group_dual_world_empty_gate" => self.runtime_host_cmd_click_live_ai_group_dual_world_empty_gate(&args),
            "click_live_slaved_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_slaved_update_dual_world_empty_gate(&args),
            "click_live_demoralize_power_dual_world_empty_gate" => self.runtime_host_cmd_click_live_demoralize_power_dual_world_empty_gate(&args),
            "click_live_bone_fx_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_bone_fx_update_dual_world_empty_gate(&args),
            "click_live_supply_warehouse_dock_dual_world_empty_gate" => self.runtime_host_cmd_click_live_supply_warehouse_dock_dual_world_empty_gate(&args),
            "click_live_ocl_special_power_dual_world_empty_gate" => self.runtime_host_cmd_click_live_ocl_special_power_dual_world_empty_gate(&args),
            "click_live_railed_transport_ai_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_railed_transport_ai_update_dual_world_empty_gate(&args),
            "click_live_squish_collide_dual_world_empty_gate" => self.runtime_host_cmd_click_live_squish_collide_dual_world_empty_gate(&args),
            "click_live_weapon_bonus_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_weapon_bonus_update_dual_world_empty_gate(&args),
            "click_live_minefield_behavior_dual_world_empty_gate" => self.runtime_host_cmd_click_live_minefield_behavior_dual_world_empty_gate(&args),
            "click_live_point_defense_laser_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_point_defense_laser_update_dual_world_empty_gate(&args),
            "click_live_lifetime_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_lifetime_update_dual_world_empty_gate(&args),
            "click_live_slow_death_behavior_dual_world_empty_gate" => self.runtime_host_cmd_click_live_slow_death_behavior_dual_world_empty_gate(&args),
            "click_live_battle_bus_slow_death_behavior_dual_world_empty_gate" => self.runtime_host_cmd_click_live_battle_bus_slow_death_behavior_dual_world_empty_gate(&args),
            "click_live_damage_module_dual_world_empty_gate" => self.runtime_host_cmd_click_live_damage_module_dual_world_empty_gate(&args),
            "click_live_transition_damage_fx_dual_world_empty_gate" => self.runtime_host_cmd_click_live_transition_damage_fx_dual_world_empty_gate(&args),
            "click_live_spawn_point_production_exit_behavior_dual_world_empty_gate" => self.runtime_host_cmd_click_live_spawn_point_production_exit_behavior_dual_world_empty_gate(&args),
            "click_live_build_placement_dual_world_empty_gate" => self.runtime_host_cmd_click_live_build_placement_dual_world_empty_gate(&args),
            "click_live_weapon_set_dual_world_empty_gate" => self.runtime_host_cmd_click_live_weapon_set_dual_world_empty_gate(&args),
            "click_live_experience_tracker_dual_world_empty_gate" => self.runtime_host_cmd_click_live_experience_tracker_dual_world_empty_gate(&args),
            "click_live_ai_targeting_dual_world_empty_gate" => self.runtime_host_cmd_click_live_ai_targeting_dual_world_empty_gate(&args),
            "click_live_move_to_state_dual_world_empty_gate" => self.runtime_host_cmd_click_live_move_to_state_dual_world_empty_gate(&args),
            "click_live_locomotor_core_dual_world_empty_gate" => self.runtime_host_cmd_click_live_locomotor_core_dual_world_empty_gate(&args),
            "click_live_path_following_dual_world_empty_gate" => self.runtime_host_cmd_click_live_path_following_dual_world_empty_gate(&args),
            "click_live_ai_manager_dual_world_empty_gate" => self.runtime_host_cmd_click_live_ai_manager_dual_world_empty_gate(&args),
            "click_live_ai_states_dual_world_empty_gate" => self.runtime_host_cmd_click_live_ai_states_dual_world_empty_gate(&args),
            "click_live_ai_player_dual_world_empty_gate" => self.runtime_host_cmd_click_live_ai_player_dual_world_empty_gate(&args),
            "click_live_team_dual_world_empty_gate" => self.runtime_host_cmd_click_live_team_dual_world_empty_gate(&args),
            "click_live_ai_legacy_states_dual_world_empty_gate" => self.runtime_host_cmd_click_live_ai_legacy_states_dual_world_empty_gate(&args),
            "click_live_unit_dual_world_empty_gate" => self.runtime_host_cmd_click_live_unit_dual_world_empty_gate(&args),
            "click_live_stealth_dual_world_empty_gate" => self.runtime_host_cmd_click_live_stealth_dual_world_empty_gate(&args),
            "click_live_garrison_dual_world_empty_gate" => self.runtime_host_cmd_click_live_garrison_dual_world_empty_gate(&args),
            "click_live_open_contain_dual_world_empty_gate" => self.runtime_host_cmd_click_live_open_contain_dual_world_empty_gate(&args),
            "click_live_pathfind_dual_world_empty_gate" => self.runtime_host_cmd_click_live_pathfind_dual_world_empty_gate(&args),
            "click_live_fire_weapon_when_dead_behavior_dual_world_empty_gate" => self.runtime_host_cmd_click_live_fire_weapon_when_dead_behavior_dual_world_empty_gate(&args),
            "click_live_guard_dual_world_empty_gate" => self.runtime_host_cmd_click_live_guard_dual_world_empty_gate(&args),
            "click_live_guard_retaliate_dual_world_empty_gate" => self.runtime_host_cmd_click_live_guard_retaliate_dual_world_empty_gate(&args),
            "click_live_wander_ai_dual_world_empty_gate" => self.runtime_host_cmd_click_live_wander_ai_dual_world_empty_gate(&args),
            "click_live_subobjects_upgrade_dual_world_empty_gate" => self.runtime_host_cmd_click_live_subobjects_upgrade_dual_world_empty_gate(&args),
            "click_live_unit_exit_dual_world_empty_gate" => self.runtime_host_cmd_click_live_unit_exit_dual_world_empty_gate(&args),
            "click_live_owner_resolve_dual_world_empty_gate" => self.runtime_host_cmd_click_live_owner_resolve_dual_world_empty_gate(&args),
            "click_live_spy_vision_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_spy_vision_update_dual_world_empty_gate(&args),
            "click_live_overcharge_behavior_dual_world_empty_gate" => self.runtime_host_cmd_click_live_overcharge_behavior_dual_world_empty_gate(&args),
            "click_live_tech_building_behavior_dual_world_empty_gate" => self.runtime_host_cmd_click_live_tech_building_behavior_dual_world_empty_gate(&args),
            "click_live_power_plant_upgrade_dual_world_empty_gate" => self.runtime_host_cmd_click_live_power_plant_upgrade_dual_world_empty_gate(&args),
            "click_live_stealth_upgrade_dual_world_empty_gate" => self.runtime_host_cmd_click_live_stealth_upgrade_dual_world_empty_gate(&args),
            "click_live_aurora_strike_power_dual_world_empty_gate" => self.runtime_host_cmd_click_live_aurora_strike_power_dual_world_empty_gate(&args),
            "click_live_carpet_bomb_power_dual_world_empty_gate" => self.runtime_host_cmd_click_live_carpet_bomb_power_dual_world_empty_gate(&args),
            "click_live_nuclear_missile_power_dual_world_empty_gate" => self.runtime_host_cmd_click_live_nuclear_missile_power_dual_world_empty_gate(&args),
            "click_live_overlord_draw_dual_world_empty_gate" => self.runtime_host_cmd_click_live_overlord_draw_dual_world_empty_gate(&args),
            "click_live_stealth_integration_dual_world_empty_gate" => self.runtime_host_cmd_click_live_stealth_integration_dual_world_empty_gate(&args),
            "click_live_player_upgrade_manager_dual_world_empty_gate" => self.runtime_host_cmd_click_live_player_upgrade_manager_dual_world_empty_gate(&args),
            "click_live_advanced_nuggets_dual_world_empty_gate" => self.runtime_host_cmd_click_live_advanced_nuggets_dual_world_empty_gate(&args),
            "click_live_replace_object_upgrade_dual_world_empty_gate" => self.runtime_host_cmd_click_live_replace_object_upgrade_dual_world_empty_gate(&args),
            "click_live_fire_spread_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_fire_spread_update_dual_world_empty_gate(&args),
            "click_live_object_upgrade_batch_dual_world_empty_gate" => self.runtime_host_cmd_click_live_object_upgrade_batch_dual_world_empty_gate(&args),
            "click_live_contain_module_overrides_fail_closed" => self.runtime_host_cmd_click_live_contain_module_overrides_fail_closed(&args),
            "click_live_core_sim_dual_world_empty_gate" => self.runtime_host_cmd_click_live_core_sim_dual_world_empty_gate(&args),
            "click_live_ai_mod_dual_world_empty_gate" => self.runtime_host_cmd_click_live_ai_mod_dual_world_empty_gate(&args),
            "click_live_object_mod_dual_world_empty_gate" => self.runtime_host_cmd_click_live_object_mod_dual_world_empty_gate(&args),
            "click_live_weapon_dual_world_empty_gate" => self.runtime_host_cmd_click_live_weapon_dual_world_empty_gate(&args),
            "click_live_partition_filters_dual_world_empty_gate" => self.runtime_host_cmd_click_live_partition_filters_dual_world_empty_gate(&args),
            "click_live_ai_state_machine_dual_world_empty_gate" => self.runtime_host_cmd_click_live_ai_state_machine_dual_world_empty_gate(&args),
            "click_live_player_dual_world_empty_gate" => self.runtime_host_cmd_click_live_player_dual_world_empty_gate(&args),
            "click_live_game_client_dual_world_empty_gate" => self.runtime_host_cmd_click_live_game_client_dual_world_empty_gate(&args),
            "click_live_drawable_dual_world_empty_gate" => self.runtime_host_cmd_click_live_drawable_dual_world_empty_gate(&args),
            "click_live_script_conditions_dual_world_empty_gate" => self.runtime_host_cmd_click_live_script_conditions_dual_world_empty_gate(&args),
            "click_live_transport_contain_dual_world_empty_gate" => self.runtime_host_cmd_click_live_transport_contain_dual_world_empty_gate(&args),
            "click_live_ingame_ui_dual_world_empty_gate" => self.runtime_host_cmd_click_live_ingame_ui_dual_world_empty_gate(&args),
            "click_live_helix_contain_dual_world_empty_gate" => self.runtime_host_cmd_click_live_helix_contain_dual_world_empty_gate(&args),
            "click_live_command_processor_dual_world_empty_gate" => self.runtime_host_cmd_click_live_command_processor_dual_world_empty_gate(&args),
            "click_live_turret_dual_world_empty_gate" => self.runtime_host_cmd_click_live_turret_dual_world_empty_gate(&args),
            "click_live_rider_change_contain_dual_world_empty_gate" => self.runtime_host_cmd_click_live_rider_change_contain_dual_world_empty_gate(&args),
            "click_live_selection_dual_world_empty_gate" => self.runtime_host_cmd_click_live_selection_dual_world_empty_gate(&args),
            "click_live_cave_contain_dual_world_empty_gate" => self.runtime_host_cmd_click_live_cave_contain_dual_world_empty_gate(&args),
            "click_live_tunnel_contain_dual_world_empty_gate" => self.runtime_host_cmd_click_live_tunnel_contain_dual_world_empty_gate(&args),
            "click_live_helpers_dual_world_empty_gate" => self.runtime_host_cmd_click_live_helpers_dual_world_empty_gate(&args),
            "click_live_ai_update_interface_dual_world_empty_gate" => self.runtime_host_cmd_click_live_ai_update_interface_dual_world_empty_gate(&args),
            "click_live_stealth_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_stealth_update_dual_world_empty_gate(&args),
            "click_live_script_executor_dual_world_empty_gate" => self.runtime_host_cmd_click_live_script_executor_dual_world_empty_gate(&args),
            "click_live_ai_integration_dual_world_empty_gate" => self.runtime_host_cmd_click_live_ai_integration_dual_world_empty_gate(&args),
            "click_live_dumb_projectile_dual_world_empty_gate" => self.runtime_host_cmd_click_live_dumb_projectile_dual_world_empty_gate(&args),
            "click_live_enhanced_player_dual_world_empty_gate" => self.runtime_host_cmd_click_live_enhanced_player_dual_world_empty_gate(&args),
            "click_live_hijacker_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_hijacker_update_dual_world_empty_gate(&args),
            "click_live_weapon_impl_dual_world_empty_gate" => self.runtime_host_cmd_click_live_weapon_impl_dual_world_empty_gate(&args),
            "click_live_async_player_dual_world_empty_gate" => self.runtime_host_cmd_click_live_async_player_dual_world_empty_gate(&args),
            "click_live_active_body_dual_world_empty_gate" => self.runtime_host_cmd_click_live_active_body_dual_world_empty_gate(&args),
            "click_live_skirmish_conditions_dual_world_empty_gate" => self.runtime_host_cmd_click_live_skirmish_conditions_dual_world_empty_gate(&args),
            "click_live_ai_build_list_dual_world_empty_gate" => self.runtime_host_cmd_click_live_ai_build_list_dual_world_empty_gate(&args),
            "click_live_victory_dual_world_empty_gate" => self.runtime_host_cmd_click_live_victory_dual_world_empty_gate(&args),
            "click_live_script_actions_dual_world_empty_gate" => self.runtime_host_cmd_click_live_script_actions_dual_world_empty_gate(&args),
            "click_live_special_ability_dual_world_empty_gate" => self.runtime_host_cmd_click_live_special_ability_dual_world_empty_gate(&args),
            "click_live_stealth_detector_dual_world_empty_gate" => self.runtime_host_cmd_click_live_stealth_detector_dual_world_empty_gate(&args),
            "click_live_supply_system_dual_world_empty_gate" => self.runtime_host_cmd_click_live_supply_system_dual_world_empty_gate(&args),
            "click_live_particle_uplink_dual_world_empty_gate" => self.runtime_host_cmd_click_live_particle_uplink_dual_world_empty_gate(&args),
            "click_live_overlord_contain_dual_world_empty_gate" => self.runtime_host_cmd_click_live_overlord_contain_dual_world_empty_gate(&args),
            "click_live_bridge_behavior_dual_world_empty_gate" => self.runtime_host_cmd_click_live_bridge_behavior_dual_world_empty_gate(&args),
            "click_live_stealth_behavior_dual_world_empty_gate" => self.runtime_host_cmd_click_live_stealth_behavior_dual_world_empty_gate(&args),
            "click_live_crate_collide_dual_world_empty_gate" => self.runtime_host_cmd_click_live_crate_collide_dual_world_empty_gate(&args),
            "click_live_object_manager_dual_world_empty_gate" => self.runtime_host_cmd_click_live_object_manager_dual_world_empty_gate(&args),
            "click_live_sticky_bomb_dual_world_empty_gate" => self.runtime_host_cmd_click_live_sticky_bomb_dual_world_empty_gate(&args),
            "click_live_auto_heal_dual_world_empty_gate" => self.runtime_host_cmd_click_live_auto_heal_dual_world_empty_gate(&args),
            "click_live_grant_stealth_dual_world_empty_gate" => self.runtime_host_cmd_click_live_grant_stealth_dual_world_empty_gate(&args),
            "click_live_status_bits_upgrade_dual_world_empty_gate" => self.runtime_host_cmd_click_live_status_bits_upgrade_dual_world_empty_gate(&args),
            "click_live_jet_ai_dual_world_empty_gate" => self.runtime_host_cmd_click_live_jet_ai_dual_world_empty_gate(&args),
            "click_live_parking_place_dual_world_empty_gate" => self.runtime_host_cmd_click_live_parking_place_dual_world_empty_gate(&args),
            "click_live_flight_deck_dual_world_empty_gate" => self.runtime_host_cmd_click_live_flight_deck_dual_world_empty_gate(&args),
            "click_live_exit_strategies_dual_world_empty_gate" => self.runtime_host_cmd_click_live_exit_strategies_dual_world_empty_gate(&args),
            "click_live_collision_system_dual_world_empty_gate" => self.runtime_host_cmd_click_live_collision_system_dual_world_empty_gate(&args),
            "click_live_max_health_upgrade_dual_world_empty_gate" => self.runtime_host_cmd_click_live_max_health_upgrade_dual_world_empty_gate(&args),
            "click_live_structure_topple_dual_world_empty_gate" => self.runtime_host_cmd_click_live_structure_topple_dual_world_empty_gate(&args),
            "click_live_physics_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_physics_update_dual_world_empty_gate(&args),
            "click_live_cleanup_hazard_dual_world_empty_gate" => self.runtime_host_cmd_click_live_cleanup_hazard_dual_world_empty_gate(&args),
            "click_live_bridge_tower_dual_world_empty_gate" => self.runtime_host_cmd_click_live_bridge_tower_dual_world_empty_gate(&args),
            "click_live_armor_upgrade_dual_world_empty_gate" => self.runtime_host_cmd_click_live_armor_upgrade_dual_world_empty_gate(&args),
            "click_live_paradrop_power_dual_world_empty_gate" => self.runtime_host_cmd_click_live_paradrop_power_dual_world_empty_gate(&args),
            "click_live_fuel_air_bomb_dual_world_empty_gate" => self.runtime_host_cmd_click_live_fuel_air_bomb_dual_world_empty_gate(&args),
            "click_live_tensile_formation_dual_world_empty_gate" => self.runtime_host_cmd_click_live_tensile_formation_dual_world_empty_gate(&args),
            "click_live_die_mod_dual_world_empty_gate" => self.runtime_host_cmd_click_live_die_mod_dual_world_empty_gate(&args),
            "click_live_partition_manager_dual_world_empty_gate" => self.runtime_host_cmd_click_live_partition_manager_dual_world_empty_gate(&args),
            "click_live_spectre_gunship_dual_world_empty_gate" => self.runtime_host_cmd_click_live_spectre_gunship_dual_world_empty_gate(&args),
            "click_live_production_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_production_update_dual_world_empty_gate(&args),
            "click_live_neutron_blast_dual_world_empty_gate" => self.runtime_host_cmd_click_live_neutron_blast_dual_world_empty_gate(&args),
            "click_live_countermeasures_dual_world_empty_gate" => self.runtime_host_cmd_click_live_countermeasures_dual_world_empty_gate(&args),
            "click_live_skirmish_player_dual_world_empty_gate" => self.runtime_host_cmd_click_live_skirmish_player_dual_world_empty_gate(&args),
            "click_live_a10_strike_dual_world_empty_gate" => self.runtime_host_cmd_click_live_a10_strike_dual_world_empty_gate(&args),
            "click_live_rebuild_hole_dual_world_empty_gate" => self.runtime_host_cmd_click_live_rebuild_hole_dual_world_empty_gate(&args),
            "click_live_wave_guide_dual_world_empty_gate" => self.runtime_host_cmd_click_live_wave_guide_dual_world_empty_gate(&args),
            "click_live_emp_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_emp_update_dual_world_empty_gate(&args),
            "click_live_bunker_buster_dual_world_empty_gate" => self.runtime_host_cmd_click_live_bunker_buster_dual_world_empty_gate(&args),
            "click_live_bridge_scaffold_dual_world_empty_gate" => self.runtime_host_cmd_click_live_bridge_scaffold_dual_world_empty_gate(&args),
            "click_live_assisted_targeting_dual_world_empty_gate" => self.runtime_host_cmd_click_live_assisted_targeting_dual_world_empty_gate(&args),
            "click_live_economy_dual_world_empty_gate" => self.runtime_host_cmd_click_live_economy_dual_world_empty_gate(&args),
            "click_live_turret_ai_dual_world_empty_gate" => self.runtime_host_cmd_click_live_turret_ai_dual_world_empty_gate(&args),
            "click_live_stealth_detector_module_dual_world_empty_gate" => self.runtime_host_cmd_click_live_stealth_detector_module_dual_world_empty_gate(&args),
            "click_live_modules_dual_world_empty_gate" => self.runtime_host_cmd_click_live_modules_dual_world_empty_gate(&args),
            "click_live_terrain_dual_world_empty_gate" => self.runtime_host_cmd_click_live_terrain_dual_world_empty_gate(&args),
            "click_live_special_power_template_dual_world_empty_gate" => self.runtime_host_cmd_click_live_special_power_template_dual_world_empty_gate(&args),
            "click_live_script_evaluator_dual_world_empty_gate" => self.runtime_host_cmd_click_live_script_evaluator_dual_world_empty_gate(&args),
            "click_live_system_game_logic_dual_world_empty_gate" => self.runtime_host_cmd_click_live_system_game_logic_dual_world_empty_gate(&args),
            "click_live_meta_event_dual_world_empty_gate" => self.runtime_host_cmd_click_live_meta_event_dual_world_empty_gate(&args),
            "click_live_spawn_behavior_dual_world_empty_gate" => self.runtime_host_cmd_click_live_spawn_behavior_dual_world_empty_gate(&args),
            "click_live_action_manager_dual_world_empty_gate" => self.runtime_host_cmd_click_live_action_manager_dual_world_empty_gate(&args),
            "click_live_script_engine_dual_world_empty_gate" => self.runtime_host_cmd_click_live_script_engine_dual_world_empty_gate(&args),
            "click_live_chinook_ai_dual_world_empty_gate" => self.runtime_host_cmd_click_live_chinook_ai_dual_world_empty_gate(&args),
            "click_live_missile_ai_dual_world_empty_gate" => self.runtime_host_cmd_click_live_missile_ai_dual_world_empty_gate(&args),
            "click_live_dozer_ai_dual_world_empty_gate" => self.runtime_host_cmd_click_live_dozer_ai_dual_world_empty_gate(&args),
            "click_live_deliver_payload_ai_dual_world_empty_gate" => self.runtime_host_cmd_click_live_deliver_payload_ai_dual_world_empty_gate(&args),
            "click_live_special_power_module_dual_world_empty_gate" => self.runtime_host_cmd_click_live_special_power_module_dual_world_empty_gate(&args),
            "click_live_pow_truck_ai_dual_world_empty_gate" => self.runtime_host_cmd_click_live_pow_truck_ai_dual_world_empty_gate(&args),
            "click_live_dock_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_dock_update_dual_world_empty_gate(&args),
            "click_live_weapon_template_dual_world_empty_gate" => self.runtime_host_cmd_click_live_weapon_template_dual_world_empty_gate(&args),
            "click_live_railroad_guide_ai_dual_world_empty_gate" => self.runtime_host_cmd_click_live_railroad_guide_ai_dual_world_empty_gate(&args),
            "click_live_hack_internet_ai_dual_world_empty_gate" => self.runtime_host_cmd_click_live_hack_internet_ai_dual_world_empty_gate(&args),
            "click_live_spectre_gunship_deployment_dual_world_empty_gate" => self.runtime_host_cmd_click_live_spectre_gunship_deployment_dual_world_empty_gate(&args),
            "click_live_radius_decal_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_radius_decal_update_dual_world_empty_gate(&args),
            "click_live_railed_transport_dock_dual_world_empty_gate" => self.runtime_host_cmd_click_live_railed_transport_dock_dual_world_empty_gate(&args),
            "click_live_structure_collapse_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_structure_collapse_update_dual_world_empty_gate(&args),
            "click_live_propaganda_tower_behavior_dual_world_empty_gate" => self.runtime_host_cmd_click_live_propaganda_tower_behavior_dual_world_empty_gate(&args),
            "click_live_propaganda_center_behavior_dual_world_empty_gate" => self.runtime_host_cmd_click_live_propaganda_center_behavior_dual_world_empty_gate(&args),
            "click_live_production_update_complete_dual_world_empty_gate" => self.runtime_host_cmd_click_live_production_update_complete_dual_world_empty_gate(&args),
            "click_live_pow_truck_behavior_dual_world_empty_gate" => self.runtime_host_cmd_click_live_pow_truck_behavior_dual_world_empty_gate(&args),
            "click_live_fire_weapon_when_damaged_behavior_dual_world_empty_gate" => self.runtime_host_cmd_click_live_fire_weapon_when_damaged_behavior_dual_world_empty_gate(&args),
            "click_live_veterancy_crate_collide_dual_world_empty_gate" => self.runtime_host_cmd_click_live_veterancy_crate_collide_dual_world_empty_gate(&args),
            "click_live_assault_transport_ai_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_assault_transport_ai_update_dual_world_empty_gate(&args),
            "click_live_heal_contain_dual_world_empty_gate" => self.runtime_host_cmd_click_live_heal_contain_dual_world_empty_gate(&args),
            "click_live_topple_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_topple_update_dual_world_empty_gate(&args),
            "click_live_projectile_stream_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_projectile_stream_update_dual_world_empty_gate(&args),
            "click_live_demo_trap_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_demo_trap_update_dual_world_empty_gate(&args),
            "click_live_mob_member_slaved_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_mob_member_slaved_update_dual_world_empty_gate(&args),
            "click_live_tn_guard_dual_world_empty_gate" => self.runtime_host_cmd_click_live_tn_guard_dual_world_empty_gate(&args),
            "click_live_production_update_dual_world_empty_gate_wave376" => self.runtime_host_cmd_click_live_production_update_dual_world_empty_gate_wave376(&args),
            "click_live_poisoned_behavior_dual_world_empty_gate" => self.runtime_host_cmd_click_live_poisoned_behavior_dual_world_empty_gate(&args),
            "click_live_horde_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_horde_update_dual_world_empty_gate(&args),
            "click_live_flammable_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_flammable_update_dual_world_empty_gate(&args),
            "click_live_base_regenerate_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_base_regenerate_update_dual_world_empty_gate(&args),
            "click_live_queue_production_exit_behavior_dual_world_empty_gate" => self.runtime_host_cmd_click_live_queue_production_exit_behavior_dual_world_empty_gate(&args),
            "click_live_missile_launcher_building_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_missile_launcher_building_update_dual_world_empty_gate(&args),
            "click_live_dynamic_shroud_clearing_range_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_dynamic_shroud_clearing_range_update_dual_world_empty_gate(&args),
            "click_live_command_button_hunt_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_command_button_hunt_update_dual_world_empty_gate(&args),
            "click_live_prison_behavior_dual_world_empty_gate" => self.runtime_host_cmd_click_live_prison_behavior_dual_world_empty_gate(&args),
            "click_live_generate_minefield_behavior_dual_world_empty_gate" => self.runtime_host_cmd_click_live_generate_minefield_behavior_dual_world_empty_gate(&args),
            "click_live_demoralize_special_power_dual_world_empty_gate" => self.runtime_host_cmd_click_live_demoralize_special_power_dual_world_empty_gate(&args),
            "click_live_stealth_detector_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_stealth_detector_update_dual_world_empty_gate(&args),
            "click_live_hive_structure_body_dual_world_empty_gate" => self.runtime_host_cmd_click_live_hive_structure_body_dual_world_empty_gate(&args),
            "click_live_salvage_crate_collide_dual_world_empty_gate" => self.runtime_host_cmd_click_live_salvage_crate_collide_dual_world_empty_gate(&args),
            "click_live_sabotage_internet_center_crate_collide_dual_world_empty_gate" => self.runtime_host_cmd_click_live_sabotage_internet_center_crate_collide_dual_world_empty_gate(&args),
            "click_live_power_plant_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_power_plant_update_dual_world_empty_gate(&args),
            "click_live_leaflet_drop_behavior_dual_world_empty_gate" => self.runtime_host_cmd_click_live_leaflet_drop_behavior_dual_world_empty_gate(&args),
            "click_live_auto_deposit_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_auto_deposit_update_dual_world_empty_gate(&args),
            "click_live_supply_warehouse_crippling_behavior_dual_world_empty_gate" => self.runtime_host_cmd_click_live_supply_warehouse_crippling_behavior_dual_world_empty_gate(&args),
            "click_live_neutron_missile_slow_death_update_dual_world_empty_gate" => self.runtime_host_cmd_click_live_neutron_missile_slow_death_update_dual_world_empty_gate(&args),
            "click_live_ai_dock_dual_world_empty_gate" => self.runtime_host_cmd_click_live_ai_dock_dual_world_empty_gate(&args),
            "click_live_ai_groups_dual_world_empty_gate" => self.runtime_host_cmd_click_live_ai_groups_dual_world_empty_gate(&args),
            "click_live_artillery_barrage_power_dual_world_empty_gate" => self.runtime_host_cmd_click_live_artillery_barrage_power_dual_world_empty_gate(&args),
            "click_live_baikonur_launch_power_dual_world_empty_gate" => self.runtime_host_cmd_click_live_baikonur_launch_power_dual_world_empty_gate(&args),
            "save_game" | "quicksave" => self.runtime_host_cmd_save_game(&args),
            "quickload" => self.runtime_host_cmd_quickload(&args),
            "load_game" => self.runtime_host_cmd_load_game(&args),
            "pause_save" => self.runtime_host_cmd_pause_save(&args),
            "pause_load" => self.runtime_host_cmd_pause_load(&args),
            "replay" => self.runtime_host_cmd_replay(&args),
            "enqueue_production" | "train_unit" => self.runtime_host_cmd_enqueue_production(&args),
            "select_local_unit" => self.runtime_host_cmd_select_local_unit(&args),
            "move" | "move_selected" => self.runtime_host_cmd_move(&args),
            "attack_nearest_enemy" => self.runtime_host_cmd_attack_nearest_enemy(&args),
            "stop_all" | "stop_selected" => self.runtime_host_cmd_stop_all(&args),
            "sell" | "sell_selected" => self.runtime_host_cmd_sell(&args),
            "upgrade" | "queue_upgrade" => self.runtime_host_cmd_upgrade(&args),
            "guard" | "guard_position" => self.runtime_host_cmd_guard(&args),
            "attack_move" | "attackmove" => self.runtime_host_cmd_attack_move(&args),
            "scatter" => self.runtime_host_cmd_scatter(&args),
            "patrol" => self.runtime_host_cmd_patrol(&args),
            "deploy" => self.runtime_host_cmd_deploy(&args),
            "cheer" => self.runtime_host_cmd_cheer(&args),
            "formation" | "create_formation" => self.runtime_host_cmd_formation(&args),
            "capture" | "capture_building" => self.runtime_host_cmd_capture(&args),
            "return_supplies" | "return_to_supply" => self.runtime_host_cmd_return_supplies(&args),
            "evacuate" => self.runtime_host_cmd_evacuate(&args),
            "repair" => self.runtime_host_cmd_repair(&args),
            "return_to_base" => self.runtime_host_cmd_return_to_base(&args),
            "attitude_aggressive" | "aggressive" => self.runtime_host_cmd_attitude_aggressive(&args),
            "attitude_passive" | "passive" => self.runtime_host_cmd_attitude_passive(&args),
            "attitude_sleep" | "sleep" => self.runtime_host_cmd_attitude_sleep(&args),
            "set_rally" | "rally" => self.runtime_host_cmd_set_rally(&args),
            "switch_weapons" => self.runtime_host_cmd_switch_weapons(&args),
            "view_command_center" | "view_cc" => self.runtime_host_cmd_view_command_center(&args),
            "clear_mines" => self.runtime_host_cmd_clear_mines(&args),
            "place_beacon" => self.runtime_host_cmd_place_beacon(&args),
            "hack_internet" | "hack" => self.runtime_host_cmd_hack_internet(&args),
            "cleanup_area" | "cleanup" => self.runtime_host_cmd_cleanup_area(&args),
            "combat_drop" => self.runtime_host_cmd_combat_drop(&args),
            "toggle_overcharge" | "overcharge" => self.runtime_host_cmd_toggle_overcharge(&args),
            "special_power" | "do_special_power" => self.runtime_host_cmd_special_power(&args),
            "remove_beacon" => self.runtime_host_cmd_remove_beacon(&args),
            "demo_suicide" | "detonate_demo" => self.runtime_host_cmd_demo_suicide(&args),
            "detonate_remote" => self.runtime_host_cmd_detonate_remote(&args),
            "view_last_radar" | "view_radar" => self.runtime_host_cmd_view_last_radar(&args),
            "force_attack" | "force_attack_ground" => self.runtime_host_cmd_force_attack(&args),
            "force_attack_object" | "force_attack_target" => self.runtime_host_cmd_force_attack_object(&args),
            "select_all" | "select_all_units" => self.runtime_host_cmd_select_all(&args),
            "select_all_combat" => self.runtime_host_cmd_select_all_combat(&args),
            "assign_control_group" | "set_control_group" => self.runtime_host_cmd_assign_control_group(&args),
            "recall_control_group" | "select_control_group" => self.runtime_host_cmd_recall_control_group(&args),
            "waypoint_mode" | "toggle_waypoint" => self.runtime_host_cmd_waypoint_mode(&args),
            "add_waypoint" | "waypoint" => self.runtime_host_cmd_add_waypoint(&args),
            "box_select" => self.runtime_host_cmd_box_select(&args),
            "select_similar" | "double_click_select" => self.runtime_host_cmd_select_similar(&args),
            "select_on_screen" => self.runtime_host_cmd_select_on_screen(&args),
            "select_aircraft" => self.runtime_host_cmd_select_aircraft(&args),
            "select_idle_harvesters" | "select_idle" => self.runtime_host_cmd_select_idle_harvesters(&args),
            "select_structures" => self.runtime_host_cmd_select_structures(&args),
            "select_moving" => self.runtime_host_cmd_select_moving(&args),
            "camera_reset" | "reset_camera" => self.runtime_host_cmd_camera_reset(&args),
            "camera_look_at" | "look_at" => self.runtime_host_cmd_camera_look_at(&args),
            "camera_zoom" | "zoom" => self.runtime_host_cmd_camera_zoom(&args),
            "camera_track" | "toggle_camera_track" => self.runtime_host_cmd_camera_track(&args),
            "cancel_production" | "cancel_queue" => self.runtime_host_cmd_cancel_production(&args),
            "open_diplomacy" | "diplomacy" => self.runtime_host_cmd_open_diplomacy(&args),
            "auto_attack" | "sticky_auto_attack" | "toggle_auto_attack" => self.runtime_host_cmd_auto_attack(&args),
            "request_capture" | "screenshot" => self.runtime_host_cmd_request_capture(&args),
            "construct" | "dozer_construct" | "place_structure" => self.runtime_host_cmd_construct(&args),
            // Windowed sit-through inject: shared WM path, Injected origin
            // (does not latch playable_claim evidence).
            // Headless always fails closed; drive_os_wnd_* is deliberately NOT used.
            "winit_click_named" => self.runtime_host_cmd_winit_click_named(&args),
            "winit_menu_nav" => self.runtime_host_cmd_winit_menu_nav(&args),
            "winit_gameplay_order" => self.runtime_host_cmd_winit_gameplay_order(&args),
            "window_move" | "move_window" => self.runtime_host_cmd_window_move(&args),
            // Physical drive aids: advance Menu FLASH/BUTTONFLASH transitions
            // (C++ plays them at 60 fps; windowed Menu frames are ~4 s, so the
            // SP dropdown is unhittable for 7+ frames without this) and commit
            // the retail UseAlternateMouse option (C++ OptionsMenu.cpp:1157
            // checkbox → CommandXlat.cpp:3656 RMB-context-command mode).
            "tick_main_menu_transitions" => {
                self.runtime_host_cmd_tick_main_menu_transitions(&args)
            }
            "alternate_mouse" | "use_alternate_mouse" => {
                self.runtime_host_cmd_alternate_mouse(&args)
            }
            _ => {
                debug!(
                    "Ignoring unknown runtime host command '{}'",
                    raw_command.trim()
                );
            }
        }
    }
}
