[package]
name = "ww3d-effects"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
glam = {workspace = true, features = ["bytemuck"]}
ww3d-renderer-3d = { path = "../ww3d-renderer-3d" }
ww3d-core = { path = "../ww3d-core" }
wgpu = {workspace = true}
winit = {workspace = true}
tokio = {workspace = true, features = ["full"]}
bytemuck = {workspace = true, features = ["derive"]}
thiserror = {workspace = true}
anyhow = {workspace = true}
rand = {workspace = true}
configparser = {workspace = true}

[dev-dependencies]
pollster = {workspace = true}
