//! Early residual honesty band (waves 72–120). No playable_claim flip.
//!
//! Owns this band's field subset and evaluate assignments.
//! Public `WaveHonesty`/`EarlyHonesty` stay flat via `from_parts`.

#![allow(unused_imports, unused_variables)]

use super::super::imports::*;

pub(super) struct Waves72120 {
    pub mesh_asset_residual_ok: bool,
    pub rng_residual_pack_ok: bool,
    pub special_power_wave72_residual_ok: bool,
    pub special_power_wave73_residual_ok: bool,
    pub special_power_wave76_residual_ok: bool,
    pub paradrop_wave76_residual_ok: bool,
    pub graphics_wave76_residual_ok: bool,
    pub spectre_orbit_decal_presentation_ok: bool,
    pub special_power_wave77_residual_ok: bool,
    pub fow_residual_pack_ok: bool,
    pub ground_height_presentation_ok: bool,
    pub weapon_store_seed_residual_ok: bool,
    pub ai_skirmish_residual_ok: bool,
    pub special_power_wave78_residual_ok: bool,
    pub cluster_mines_wave78_residual_ok: bool,
    pub gps_scrambler_wave78_residual_ok: bool,
    pub cash_bounty_wave78_residual_ok: bool,
    pub minimap_residual_pack_ok: bool,
    pub selection_hud_residual_pack_ok: bool,
    pub input_residual_pack_ok: bool,
    pub drawable_residual_fields_ok: bool,
    pub unit_training_wave79_residual_ok: bool,
    pub upgrades_cost_time_application_ok: bool,
    pub command_button_wave80_residual_ok: bool,
    pub science_rank_wave80_residual_ok: bool,
    pub superweapon_kindof_wave80_residual_ok: bool,
    pub special_power_enum_wave80_residual_ok: bool,
    pub terrain_height_sample_wave81_ok: bool,
    pub pathfinder_wave81_residual_ok: bool,
    pub locomotor_table_wave81_ok: bool,
    pub armor_table_wave81_ok: bool,
    pub puc_flare_table_wave81_ok: bool,
    pub damage_type_wave82_ok: bool,
    pub death_type_wave82_ok: bool,
    pub model_condition_wave82_ok: bool,
    pub weapon_bonus_wave82_ok: bool,
    pub object_status_wave82_ok: bool,
    pub production_queue_wave83_ok: bool,
    pub supply_warehouse_wave83_ok: bool,
    pub dozer_build_wave83_ok: bool,
    pub capture_building_wave83_ok: bool,
    pub power_plant_wave83_ok: bool,
    pub command_center_wave83_ok: bool,
    pub kindof_wave84_ok: bool,
    pub weapon_slot_wave84_ok: bool,
    pub veterancy_wave84_ok: bool,
    pub relationship_wave84_ok: bool,
    pub geometry_wave84_ok: bool,
    pub shadow_wave84_ok: bool,
    pub faction_side_wave85_ok: bool,
    pub player_template_wave85_ok: bool,
    pub starting_cash_wave85_ok: bool,
    pub skirmish_ai_personality_wave85_ok: bool,
    pub victory_condition_wave85_ok: bool,
    pub gamedata_camera_fps_wave86_ok: bool,
    pub gamedata_world_constants_wave86_ok: bool,
    pub multiplayer_options_wave86_ok: bool,
    pub map_selection_wave86_ok: bool,
    pub crate_deepen_wave86_ok: bool,
    pub weather_wave87_ok: bool,
    pub water_wave87_ok: bool,
    pub bridge_wave87_ok: bool,
    pub tunnel_wave87_ok: bool,
    pub garrison_wave87_ok: bool,
    pub transport_wave87_ok: bool,
    pub radius_cursor_wave88_ok: bool,
    pub mouse_cursor_wave88_ok: bool,
    pub superweapon_fxlist_wave88_ok: bool,
    pub superweapon_ocl_wave88_ok: bool,
    pub superweapon_particle_wave88_ok: bool,
    pub superweapon_audio_wave88_ok: bool,
    pub rank_skill_wave89_ok: bool,
    pub experience_wave89_ok: bool,
    pub hotkey_wave89_ok: bool,
    pub chat_wave89_ok: bool,
    pub replay_wave89_ok: bool,
    pub options_wave89_ok: bool,
    pub gamespeed_wave90_ok: bool,
    pub frame_rate_wave90_ok: bool,
    pub debug_tables_wave90_ok: bool,
    pub language_wave90_ok: bool,
    pub credits_wave90_ok: bool,
    pub tooltip_wave91_ok: bool,
    pub help_box_wave91_ok: bool,
    pub message_wave91_ok: bool,
    pub eva_wave91_ok: bool,
    pub video_wave91_ok: bool,
    pub mission_briefing_wave91_ok: bool,
    pub weapon_deepen_wave92_ok: bool,
    pub armor_expand_wave92_ok: bool,
    pub body_health_wave92_ok: bool,
    pub locomotor_expand_wave92_ok: bool,
    pub science_names_wave92_ok: bool,
    pub particle_emit_wave93_ok: bool,
    pub drawable_opacity_wave93_ok: bool,
    pub shadow_deepen_wave93_ok: bool,
    pub terrain_texture_wave93_ok: bool,
    pub road_wave93_ok: bool,
    pub ai_state_wave94_ok: bool,
    pub special_ability_wave94_ok: bool,
    pub upgrade_names_wave94_ok: bool,
    pub command_set_wave94_ok: bool,
    pub script_action_wave95_ok: bool,
    pub script_condition_wave95_ok: bool,
    pub map_object_wave95_ok: bool,
    pub waypoint_wave95_ok: bool,
    pub team_wave95_ok: bool,
    pub player_deepen_wave95_ok: bool,
    pub partition_wave96_ok: bool,
    pub collision_wave96_ok: bool,
    pub physics_wave96_ok: bool,
    pub projectile_wave96_ok: bool,
    pub radar_deepen_wave97_ok: bool,
    pub spotter_wave97_ok: bool,
    pub stealth_deepen_wave97_ok: bool,
    pub detector_deepen_wave97_ok: bool,
    pub vision_wave97_ok: bool,
    pub dock_wave98_ok: bool,
    pub contain_wave98_ok: bool,
    pub exit_wave98_ok: bool,
    pub heal_wave98_ok: bool,
    pub production_deepen_wave99_ok: bool,
    pub buildable_wave99_ok: bool,
    pub prerequisite_wave99_ok: bool,
    pub command_button_deepen_wave99_ok: bool,
    pub control_bar_deepen_wave99_ok: bool,
    pub thing_factory_deepen_wave100_ok: bool,
    pub module_type_wave100_ok: bool,
    pub xfer_deepen_wave100_ok: bool,
    pub thing_factory_crosslink_wave100_ok: bool,
    pub module_factory_deepen_wave101_ok: bool,
    pub thing_factory_create_wave101_ok: bool,
    pub partition_register_wave101_ok: bool,
    pub mf_crosslink_wave101_ok: bool,
    pub display_string_deepen_wave102_ok: bool,
    pub anim2d_deepen_wave102_ok: bool,
    pub laser_segliner_deepen_wave102_ok: bool,
    pub csf_multi_locale_deepen_wave102_ok: bool,
    pub presentation_deepen_wave102_ok: bool,
    pub weapon_deepen_wave103_ok: bool,
    pub armor_expand_wave103_ok: bool,
    pub locomotor_expand_wave103_ok: bool,
    pub special_power_deepen_wave103_ok: bool,
    pub object_kindof_wave103_ok: bool,
    pub object_status_wave104_ok: bool,
    pub object_create_wave104_ok: bool,
    pub active_body_wave104_ok: bool,
    pub drawable_create_wave104_ok: bool,
    pub register_object_wave104_ok: bool,
    pub ai_group_wave105_ok: bool,
    pub ai_path_wave105_ok: bool,
    pub weapon_fire_wave105_ok: bool,
    pub damage_application_wave105_ok: bool,
    pub veterancy_wave105_ok: bool,
    pub game_state_deepen_wave106_ok: bool,
    pub campaign_mission_wave106_ok: bool,
    pub main_menu_deepen_wave106_ok: bool,
    pub game_window_deepen_wave106_ok: bool,
    pub window_layout_deepen_wave106_ok: bool,
    pub particle_system_deepen_wave107_ok: bool,
    pub fxlist_entry_deepen_wave107_ok: bool,
    pub ocl_create_deepen_wave107_ok: bool,
    pub audio_deepen_wave107_ok: bool,
    pub heightmap_deepen_wave108_ok: bool,
    pub bridge_deepen_wave108_ok: bool,
    pub water_deepen_wave108_ok: bool,
    pub road_deepen_wave108_ok: bool,
    pub cliff_peels_wave108_ok: bool,
    pub special_power_store_wave109_ok: bool,
    pub science_store_wave109_ok: bool,
    pub upgrade_store_wave109_ok: bool,
    pub player_deepen_wave109_ok: bool,
    pub team_deepen_wave109_ok: bool,
    pub message_stream_marker_wave110_ok: bool,
    pub game_message_arg_wave110_ok: bool,
    pub meta_event_category_wave110_ok: bool,
    pub ingame_ui_wave110_ok: bool,
    pub drawable_icon_flash_wave111_ok: bool,
    pub drawable_status_stealth_wave111_ok: bool,
    pub terrain_decal_wave111_ok: bool,
    pub display_draw_image_wave111_ok: bool,
    pub game_client_translator_wave111_ok: bool,
    pub particle_priority_wave111_ok: bool,
    pub mouse_residual_wave112_ok: bool,
    pub keyboard_residual_wave112_ok: bool,
    pub view_residual_wave112_ok: bool,
    pub game_window_manager_wave113_ok: bool,
    pub window_style_wave113_ok: bool,
    pub gadget_wave113_ok: bool,
    pub video_buffer_wave113_ok: bool,
    pub audio_event_wave113_ok: bool,
    pub main_menu_skirmish_names_wave114_ok: bool,
    pub main_menu_skirmish_nav_steps_wave114_ok: bool,
    pub main_menu_skirmish_message_wave114_ok: bool,
    pub map_select_names_wave115_ok: bool,
    pub map_select_nav_steps_wave115_ok: bool,
    pub map_select_commands_wave115_ok: bool,
    pub slot_state_wave116_ok: bool,
    pub slot_combo_names_wave116_ok: bool,
    pub slot_nav_commands_wave116_ok: bool,
    pub starting_cash_wave117_ok: bool,
    pub game_speed_controls_wave117_ok: bool,
    pub rules_nav_commands_wave117_ok: bool,
    pub main_menu_button_names_wave118_ok: bool,
    pub main_menu_push_targets_wave118_ok: bool,
    pub main_menu_button_nav_commands_wave118_ok: bool,
    pub campaign_button_names_wave119_ok: bool,
    pub campaign_enums_wave119_ok: bool,
    pub campaign_nav_commands_wave119_ok: bool,
    pub challenge_control_names_wave120_ok: bool,
    pub challenge_nav_commands_wave120_ok: bool,
}

pub(super) fn evaluate(
    pres: &crate::presentation_frame::PresentationFrame,
    presentation_ok: bool,
) -> Waves72120 {
    Waves72120 {
        mesh_asset_residual_ok: honesty_mesh_asset_residual_ok(),
        rng_residual_pack_ok: honesty_rng_residual_pack_ok(),
        special_power_wave72_residual_ok: honesty_special_power_residual_pack_ok(),
        special_power_wave73_residual_ok: honesty_special_power_residual_pack_wave73_ok(),
        special_power_wave76_residual_ok: honesty_special_power_residual_pack_wave76_ok(),
        paradrop_wave76_residual_ok: honesty_paradrop_residual_pack_wave76_ok(),
        graphics_wave76_residual_ok: honesty_graphics_residual_pack_wave76_ok(),
        spectre_orbit_decal_presentation_ok: honesty_spectre_orbit_decal_presentation_ok()
            && presentation_ok
            && pres.spectre_orbit_decal_presentation_residual_ok(),
        special_power_wave77_residual_ok: honesty_special_power_residual_pack_wave77_ok(),
        fow_residual_pack_ok: honesty_fow_residual_pack_wave77(),
        ground_height_presentation_ok: presentation_ok
            && pres.ground_height_presentation_residual_ok(),
        weapon_store_seed_residual_ok: honesty_weapon_store_host_seed_residual_wave77(),
        ai_skirmish_residual_ok: honesty_ai_skirmish_residual_pack_wave77(),
        special_power_wave78_residual_ok: honesty_special_power_residual_pack_wave78_ok(),
        cluster_mines_wave78_residual_ok: honesty_cluster_mines_residual_pack_wave78(),
        gps_scrambler_wave78_residual_ok: honesty_gps_scrambler_residual_pack_wave78(),
        cash_bounty_wave78_residual_ok: honesty_cash_bounty_residual_pack_wave78(),
        minimap_residual_pack_ok: honesty_minimap_residual_pack_wave79(),
        selection_hud_residual_pack_ok: honesty_selection_hud_residual_pack_wave79(),
        input_residual_pack_ok: honesty_input_residual_pack_wave79(),
        drawable_residual_fields_ok: honesty_drawable_residual_fields_wave79_ok(),
        unit_training_wave79_residual_ok: honesty_unit_training_residual_pack_wave79_ok(),
        upgrades_cost_time_application_ok: honesty_upgrades_cost_time_application_wave79_ok(),
        command_button_wave80_residual_ok: honesty_command_button_superweapon_residual_pack_wave80(
        ),
        science_rank_wave80_residual_ok: honesty_science_rank_residual_pack_wave80(),
        superweapon_kindof_wave80_residual_ok: honesty_superweapon_kindof_residual_pack_wave80(),
        special_power_enum_wave80_residual_ok: honesty_special_power_enum_residual_pack_wave80(),
        terrain_height_sample_wave81_ok: honesty_map_height_sample_residual_pack_wave81(),
        pathfinder_wave81_residual_ok: honesty_pathfinder_residual_pack_wave81(),
        locomotor_table_wave81_ok: honesty_locomotor_residual_table_wave81(),
        armor_table_wave81_ok: honesty_armor_residual_table_wave81(),
        puc_flare_table_wave81_ok: honesty_particle_outer_node_flare_name_table_wave81(),
        damage_type_wave82_ok: honesty_damage_type_enum_table_wave82(),
        death_type_wave82_ok: honesty_death_type_enum_table_wave82(),
        model_condition_wave82_ok: honesty_model_condition_enum_table_wave82(),
        weapon_bonus_wave82_ok: honesty_weapon_bonus_enum_table_wave82(),
        object_status_wave82_ok: honesty_object_status_enum_table_wave82(),
        production_queue_wave83_ok: honesty_production_queue_residual_pack_wave83(),
        supply_warehouse_wave83_ok: honesty_supply_warehouse_residual_pack_wave83(),
        dozer_build_wave83_ok: honesty_dozer_build_residual_pack_wave83(),
        capture_building_wave83_ok: honesty_capture_building_residual_pack_wave83(),
        power_plant_wave83_ok: honesty_power_plant_residual_pack_wave83(),
        command_center_wave83_ok: honesty_command_center_residual_pack_wave83(),
        kindof_wave84_ok: honesty_kindof_enum_table_wave84(),
        weapon_slot_wave84_ok: honesty_weapon_slot_enum_table_wave84(),
        veterancy_wave84_ok: honesty_veterancy_level_enum_table_wave84(),
        relationship_wave84_ok: honesty_relationship_enum_table_wave84(),
        geometry_wave84_ok: honesty_geometry_type_enum_table_wave84(),
        shadow_wave84_ok: honesty_shadow_type_enum_table_wave84(),
        faction_side_wave85_ok: honesty_faction_side_residual_table_wave85(),
        player_template_wave85_ok: honesty_player_template_residual_pack_wave85(),
        starting_cash_wave85_ok: honesty_starting_cash_residual_pack_wave85(),
        skirmish_ai_personality_wave85_ok: honesty_skirmish_ai_personality_residual_pack_wave85(),
        victory_condition_wave85_ok: honesty_victory_condition_residual_pack_wave85(),
        gamedata_camera_fps_wave86_ok: honesty_gamedata_camera_fps_residual_pack_wave86(),
        gamedata_world_constants_wave86_ok: honesty_gamedata_world_constants_residual_pack_wave86(),
        multiplayer_options_wave86_ok: honesty_multiplayer_options_residual_pack_wave86(),
        map_selection_wave86_ok: honesty_map_selection_residual_pack_wave86(),
        crate_deepen_wave86_ok: honesty_crate_residual_deepen_pack_wave86(),
        weather_wave87_ok: honesty_weather_residual_pack_wave87(),
        water_wave87_ok: honesty_water_residual_pack_wave87(),
        bridge_wave87_ok: honesty_bridge_residual_pack_wave87(),
        tunnel_wave87_ok: honesty_tunnel_residual_deepen_wave87(),
        garrison_wave87_ok: honesty_garrison_residual_pack_wave87(),
        transport_wave87_ok: honesty_transport_residual_pack_wave87(),
        radius_cursor_wave88_ok: honesty_radius_cursor_name_table_wave88(),
        mouse_cursor_wave88_ok: honesty_mouse_cursor_name_table_wave88(),
        superweapon_fxlist_wave88_ok: honesty_superweapon_fxlist_name_table_wave88(),
        superweapon_ocl_wave88_ok: honesty_superweapon_ocl_name_table_wave88(),
        superweapon_particle_wave88_ok: honesty_superweapon_particle_name_table_wave88(),
        superweapon_audio_wave88_ok: honesty_superweapon_audio_event_name_table_wave88(),
        rank_skill_wave89_ok: honesty_rank_skill_points_application_residual_pack_wave89(),
        experience_wave89_ok: honesty_experience_residual_tables_pack_wave89(),
        hotkey_wave89_ok: honesty_hotkey_residual_table_pack_wave89(),
        chat_wave89_ok: honesty_chat_residual_host_pack_wave89(),
        replay_wave89_ok: honesty_replay_residual_host_pack_wave89(),
        options_wave89_ok: honesty_options_residual_pack_wave89(),
        gamespeed_wave90_ok: honesty_gamespeed_residual_pack_wave90(),
        frame_rate_wave90_ok: honesty_frame_rate_residual_deepen_pack_wave90(),
        debug_tables_wave90_ok: honesty_debug_residual_tables_pack_wave90(),
        language_wave90_ok: honesty_language_residual_deepen_pack_wave90(),
        credits_wave90_ok: honesty_credits_residual_pack_wave90(),
        tooltip_wave91_ok: honesty_tooltip_residual_pack_wave91(),
        help_box_wave91_ok: honesty_help_box_residual_pack_wave91(),
        message_wave91_ok: honesty_message_residual_pack_wave91(),
        eva_wave91_ok: honesty_eva_residual_pack_wave91(),
        video_wave91_ok: honesty_video_residual_name_table_wave91(),
        mission_briefing_wave91_ok: honesty_mission_briefing_residual_pack_wave91(),
        weapon_deepen_wave92_ok: honesty_weapon_store_deepen_residual_wave92(),
        armor_expand_wave92_ok: honesty_armor_residual_expand_wave92(),
        body_health_wave92_ok: honesty_body_max_health_residual_table_wave92(),
        locomotor_expand_wave92_ok: honesty_locomotor_residual_expand_wave92(),
        science_names_wave92_ok: honesty_science_name_table_residual_wave92(),
        particle_emit_wave93_ok: honesty_particle_system_emit_rate_residual_deepen_pack_wave93(),
        drawable_opacity_wave93_ok: honesty_drawable_opacity_shroud_residual_deepen_pack_wave93(),
        shadow_deepen_wave93_ok: honesty_shadow_residual_deepen_pack_wave93(),
        terrain_texture_wave93_ok: honesty_terrain_texture_residual_pack_wave93(),
        road_wave93_ok: honesty_road_residual_pack_wave93(),
        ai_state_wave94_ok: honesty_ai_state_residual_table_wave94(),
        special_ability_wave94_ok: honesty_special_ability_residual_deepen_wave94(),
        upgrade_names_wave94_ok: honesty_upgrade_name_table_residual_wave94(),
        command_set_wave94_ok: honesty_command_set_superweapon_residual_wave94(),
        script_action_wave95_ok: honesty_script_action_name_table_residual_wave95(),
        script_condition_wave95_ok: honesty_script_condition_name_table_residual_wave95(),
        map_object_wave95_ok: honesty_map_object_residual_pack_wave95(),
        waypoint_wave95_ok: honesty_waypoint_residual_pack_wave95(),
        team_wave95_ok: honesty_team_residual_pack_wave95(),
        player_deepen_wave95_ok: honesty_player_residual_deepen_pack_wave95(),
        partition_wave96_ok: honesty_partition_residual_pack_wave96(),
        collision_wave96_ok: honesty_collision_residual_pack_wave96(),
        physics_wave96_ok: honesty_physics_residual_pack_wave96(),
        projectile_wave96_ok: honesty_projectile_residual_deepen_pack_wave96(),
        radar_deepen_wave97_ok: honesty_radar_residual_deepen_pack_wave97(),
        spotter_wave97_ok: honesty_spotter_residual_pack_wave97(),
        stealth_deepen_wave97_ok: honesty_stealth_residual_deepen_pack_wave97(),
        detector_deepen_wave97_ok: honesty_detector_residual_deepen_pack_wave97(),
        vision_wave97_ok: honesty_vision_residual_pack_wave97(),
        dock_wave98_ok: honesty_dock_residual_pack_wave98(),
        contain_wave98_ok: honesty_contain_residual_deepen_pack_wave98(),
        exit_wave98_ok: honesty_exit_residual_pack_wave98(),
        heal_wave98_ok: honesty_heal_residual_deepen_pack_wave98(),
        production_deepen_wave99_ok: honesty_production_residual_deepen_pack_wave99(),
        buildable_wave99_ok: honesty_buildable_residual_pack_wave99(),
        prerequisite_wave99_ok: honesty_prerequisite_residual_pack_wave99(),
        command_button_deepen_wave99_ok: honesty_command_button_residual_deepen_pack_wave99(),
        control_bar_deepen_wave99_ok: honesty_control_bar_residual_deepen_pack_wave99(),
        thing_factory_deepen_wave100_ok: honesty_thing_factory_residual_deepen_pack_wave100(),
        module_type_wave100_ok: honesty_module_type_table_residual_pack_wave100(),
        xfer_deepen_wave100_ok: honesty_xfer_residual_deepen_pack_wave100(),
        thing_factory_crosslink_wave100_ok: honesty_thing_factory_spawn_crosslink_wave100(),
        module_factory_deepen_wave101_ok: honesty_module_factory_residual_deepen_pack_wave101(),
        thing_factory_create_wave101_ok: honesty_thing_factory_create_residual_deepen_pack_wave101(
        ),
        partition_register_wave101_ok: honesty_partition_register_residual_pack_wave101(),
        mf_crosslink_wave101_ok: honesty_thing_factory_module_partition_crosslink_wave101(),
        display_string_deepen_wave102_ok: honesty_display_string_residual_deepen_pack_wave102(),
        anim2d_deepen_wave102_ok: honesty_anim2d_residual_deepen_pack_wave102(),
        laser_segliner_deepen_wave102_ok: honesty_laser_segliner_residual_deepen_pack_wave102(),
        csf_multi_locale_deepen_wave102_ok: honesty_csf_multi_locale_residual_deepen_pack_wave102(),
        presentation_deepen_wave102_ok: honesty_presentation_residual_deepen_pack_wave102(),
        weapon_deepen_wave103_ok: honesty_weapon_store_deepen_residual_wave103(),
        armor_expand_wave103_ok: honesty_armor_residual_expand_wave103(),
        locomotor_expand_wave103_ok: honesty_locomotor_residual_expand_wave103(),
        special_power_deepen_wave103_ok: honesty_special_power_superweapon_residual_deepen_wave103(
        ),
        object_kindof_wave103_ok: honesty_object_kindof_residual_pack_wave103(),
        object_status_wave104_ok: honesty_object_status_state_machine_residual_wave104(),
        object_create_wave104_ok: honesty_object_create_order_residual_wave104(),
        active_body_wave104_ok: honesty_active_body_max_health_apply_residual_wave104(),
        drawable_create_wave104_ok: honesty_drawable_create_residual_wave104(),
        register_object_wave104_ok: honesty_gamelogic_register_object_residual_wave104(),
        ai_group_wave105_ok: honesty_ai_group_residual_pack_wave105(),
        ai_path_wave105_ok: honesty_ai_path_residual_deepen_pack_wave105(),
        weapon_fire_wave105_ok: honesty_weapon_fire_residual_deepen_pack_wave105(),
        damage_application_wave105_ok: honesty_damage_application_residual_deepen_pack_wave105(),
        veterancy_wave105_ok: honesty_veterancy_residual_deepen_pack_wave105(),
        game_state_deepen_wave106_ok: honesty_game_state_residual_deepen_pack_wave106(),
        campaign_mission_wave106_ok: honesty_campaign_mission_residual_deepen_pack_wave106(),
        main_menu_deepen_wave106_ok: honesty_main_menu_residual_deepen_pack_wave106(),
        game_window_deepen_wave106_ok: honesty_game_window_residual_deepen_pack_wave106(),
        window_layout_deepen_wave106_ok: honesty_window_layout_residual_deepen_pack_wave106(),
        particle_system_deepen_wave107_ok: honesty_particle_system_residual_deepen_pack_wave107(),
        fxlist_entry_deepen_wave107_ok: honesty_fxlist_entry_residual_deepen_pack_wave107(),
        ocl_create_deepen_wave107_ok: honesty_ocl_create_residual_deepen_pack_wave107(),
        audio_deepen_wave107_ok: honesty_audio_residual_deepen_pack_wave107(),
        heightmap_deepen_wave108_ok: honesty_heightmap_residual_deepen_pack_wave108(),
        bridge_deepen_wave108_ok: honesty_bridge_residual_deepen_pack_wave108(),
        water_deepen_wave108_ok: honesty_water_residual_deepen_pack_wave108(),
        road_deepen_wave108_ok: honesty_road_residual_deepen_pack_wave108(),
        cliff_peels_wave108_ok: honesty_cliff_residual_peels_pack_wave108(),
        special_power_store_wave109_ok: honesty_special_power_template_store_residual_wave109(),
        science_store_wave109_ok: honesty_science_store_residual_deepen_pack_wave109(),
        upgrade_store_wave109_ok: honesty_upgrade_store_residual_deepen_pack_wave109(),
        player_deepen_wave109_ok: honesty_player_residual_deepen_pack_wave109(),
        team_deepen_wave109_ok: honesty_team_residual_deepen_pack_wave109(),
        message_stream_marker_wave110_ok: honesty_message_stream_marker_residual_wave110(),
        game_message_arg_wave110_ok: honesty_game_message_argument_type_residual_wave110(),
        meta_event_category_wave110_ok: honesty_meta_event_category_residual_wave110(),
        ingame_ui_wave110_ok: honesty_ingame_ui_residual_wave110(),
        drawable_icon_flash_wave111_ok: honesty_drawable_icon_flash_residual_wave111(),
        drawable_status_stealth_wave111_ok: honesty_drawable_status_stealth_residual_wave111(),
        terrain_decal_wave111_ok: honesty_terrain_decal_residual_wave111(),
        display_draw_image_wave111_ok: honesty_display_draw_image_mode_residual_wave111(),
        game_client_translator_wave111_ok: honesty_game_client_translator_residual_wave111(),
        particle_priority_wave111_ok: honesty_particle_priority_residual_wave111(),
        mouse_residual_wave112_ok: honesty_mouse_residual_wave112(),
        keyboard_residual_wave112_ok: honesty_keyboard_residual_wave112(),
        view_residual_wave112_ok: honesty_view_residual_wave112(),
        game_window_manager_wave113_ok: honesty_game_window_manager_residual_wave113(),
        window_style_wave113_ok: honesty_window_style_residual_wave113(),
        gadget_wave113_ok: honesty_gadget_residual_wave113(),
        video_buffer_wave113_ok: honesty_video_buffer_residual_wave113(),
        audio_event_wave113_ok: honesty_audio_event_residual_wave113(),
        main_menu_skirmish_names_wave114_ok: honesty_main_menu_skirmish_names_residual_wave114(),
        main_menu_skirmish_nav_steps_wave114_ok:
            honesty_main_menu_skirmish_nav_steps_residual_wave114(),
        main_menu_skirmish_message_wave114_ok: honesty_main_menu_skirmish_message_residual_wave114(
        ),
        map_select_names_wave115_ok: honesty_skirmish_map_select_names_residual_wave115(),
        map_select_nav_steps_wave115_ok: honesty_skirmish_map_select_nav_steps_residual_wave115(),
        map_select_commands_wave115_ok: honesty_skirmish_map_select_commands_residual_wave115(),
        slot_state_wave116_ok: honesty_skirmish_slot_state_residual_wave116(),
        slot_combo_names_wave116_ok: honesty_skirmish_slot_combo_names_residual_wave116(),
        slot_nav_commands_wave116_ok: honesty_skirmish_slot_nav_commands_residual_wave116(),
        starting_cash_wave117_ok: honesty_skirmish_starting_cash_residual_wave117(),
        game_speed_controls_wave117_ok: honesty_skirmish_game_speed_controls_residual_wave117(),
        rules_nav_commands_wave117_ok: honesty_skirmish_rules_nav_commands_residual_wave117(),
        main_menu_button_names_wave118_ok: honesty_main_menu_button_names_residual_wave118(),
        main_menu_push_targets_wave118_ok: honesty_main_menu_push_targets_residual_wave118(),
        main_menu_button_nav_commands_wave118_ok:
            honesty_main_menu_button_nav_commands_residual_wave118(),
        campaign_button_names_wave119_ok: honesty_main_menu_campaign_button_names_residual_wave119(
        ),
        campaign_enums_wave119_ok: honesty_main_menu_campaign_enums_residual_wave119(),
        campaign_nav_commands_wave119_ok: honesty_main_menu_campaign_nav_commands_residual_wave119(
        ),
        challenge_control_names_wave120_ok: honesty_challenge_menu_control_names_residual_wave120(),
        challenge_nav_commands_wave120_ok: honesty_challenge_menu_nav_commands_residual_wave120(),
    }
}
