//! Early residual honesty band (waves 161–200). No playable_claim flip.
//!
//! Owns this band's field subset and evaluate assignments.
//! Public `WaveHonesty`/`EarlyHonesty` stay flat via `from_parts`.

#![allow(unused_imports, unused_variables)]

use super::super::imports::*;

pub(super) struct Waves161200 {
    pub main_menu_wnd_load_method_names_wave161_ok: bool,
    pub main_menu_wnd_load_nav_commands_wave161_ok: bool,
    pub main_menu_wnd_load_live_wave161_ok: bool,
    pub main_menu_wnd_materialise_method_names_wave162_ok: bool,
    pub main_menu_wnd_materialise_nav_commands_wave162_ok: bool,
    pub main_menu_wnd_materialise_live_wave162_ok: bool,
    pub shell_stack_push_method_names_wave163_ok: bool,
    pub shell_stack_push_nav_commands_wave163_ok: bool,
    pub shell_stack_push_live_wave163_ok: bool,
    pub shell_skirmish_nav_method_names_wave164_ok: bool,
    pub shell_skirmish_nav_commands_wave164_ok: bool,
    pub shell_skirmish_nav_live_wave164_ok: bool,
    pub control_bar_materialise_method_names_wave165_ok: bool,
    pub control_bar_materialise_nav_commands_wave165_ok: bool,
    pub control_bar_materialise_live_wave165_ok: bool,
    pub skirmish_options_wnd_method_names_wave166_ok: bool,
    pub skirmish_options_wnd_nav_commands_wave166_ok: bool,
    pub skirmish_options_wnd_live_wave166_ok: bool,
    pub new_game_stream_method_names_wave167_ok: bool,
    pub new_game_stream_nav_commands_wave167_ok: bool,
    pub new_game_stream_live_wave167_ok: bool,
    pub w3d_main_menu_init_method_names_wave168_ok: bool,
    pub w3d_main_menu_init_nav_commands_wave168_ok: bool,
    pub w3d_main_menu_init_live_wave168_ok: bool,
    pub start_game_loading_method_names_wave169_ok: bool,
    pub start_game_loading_nav_commands_wave169_ok: bool,
    pub start_game_loading_live_wave169_ok: bool,
    pub live_map_load_method_names_wave170_ok: bool,
    pub live_map_load_nav_commands_wave170_ok: bool,
    pub live_map_load_live_wave170_ok: bool,
    pub live_presentation_seed_method_names_wave171_ok: bool,
    pub live_presentation_seed_nav_commands_wave171_ok: bool,
    pub live_presentation_seed_live_wave171_ok: bool,
    pub live_gameworld_shadow_overlay_method_names_wave172_ok: bool,
    pub live_gameworld_shadow_overlay_nav_commands_wave172_ok: bool,
    pub live_gameworld_shadow_overlay_live_wave172_ok: bool,
    pub single_authority_combat_method_names_wave173_ok: bool,
    pub single_authority_combat_nav_commands_wave173_ok: bool,
    pub single_authority_combat_live_wave173_ok: bool,
    pub presentation_client_boundary_method_names_wave174_ok: bool,
    pub presentation_client_boundary_nav_commands_wave174_ok: bool,
    pub presentation_client_boundary_live_wave174_ok: bool,
    pub golden_map_host_victory_method_names_wave175_ok: bool,
    pub golden_map_host_victory_nav_commands_wave175_ok: bool,
    pub golden_map_host_victory_live_wave175_ok: bool,
    pub executable_presentation_boundary_method_names_wave176_ok: bool,
    pub executable_presentation_boundary_nav_commands_wave176_ok: bool,
    pub executable_presentation_boundary_live_wave176_ok: bool,
    pub gameworld_production_authority_method_names_wave177_ok: bool,
    pub gameworld_production_authority_nav_commands_wave177_ok: bool,
    pub gameworld_production_authority_live_wave177_ok: bool,
    pub gameworld_sole_tick_coupling_method_names_wave178_ok: bool,
    pub gameworld_sole_tick_coupling_nav_commands_wave178_ok: bool,
    pub gameworld_sole_tick_coupling_live_wave178_ok: bool,
    pub movement_authority_env_ok: bool,
    pub gameworld_authority_matrix_method_names_wave179_ok: bool,
    pub gameworld_authority_matrix_nav_commands_wave179_ok: bool,
    pub gameworld_authority_matrix_live_wave179_ok: bool,
    pub ai_fire_construction_authority_env_ok: bool,
    pub live_gameworld_production_writeback_method_names_wave180_ok: bool,
    pub live_gameworld_production_writeback_nav_commands_wave180_ok: bool,
    pub live_gameworld_production_writeback_live_wave180_ok: bool,
    pub live_gameworld_construction_writeback_method_names_wave181_ok: bool,
    pub live_gameworld_construction_writeback_nav_commands_wave181_ok: bool,
    pub live_gameworld_construction_writeback_live_wave181_ok: bool,
    pub live_gameworld_damage_channel_method_names_wave182_ok: bool,
    pub live_gameworld_damage_channel_nav_commands_wave182_ok: bool,
    pub live_gameworld_damage_channel_live_wave182_ok: bool,
    pub live_gameworld_economy_movement_method_names_wave183_ok: bool,
    pub live_gameworld_economy_movement_nav_commands_wave183_ok: bool,
    pub live_gameworld_economy_movement_live_wave183_ok: bool,
    pub live_gameworld_projectile_ai_method_names_wave184_ok: bool,
    pub live_gameworld_projectile_ai_nav_commands_wave184_ok: bool,
    pub live_gameworld_projectile_ai_live_wave184_ok: bool,
    pub live_gameworld_fire_special_power_method_names_wave185_ok: bool,
    pub live_gameworld_fire_special_power_nav_commands_wave185_ok: bool,
    pub live_gameworld_fire_special_power_live_wave185_ok: bool,
    pub live_gameworld_presentation_view_method_names_wave186_ok: bool,
    pub live_gameworld_presentation_view_nav_commands_wave186_ok: bool,
    pub live_gameworld_presentation_view_live_wave186_ok: bool,
    pub live_presentation_gameworld_overlay_method_names_wave187_ok: bool,
    pub live_presentation_gameworld_overlay_nav_commands_wave187_ok: bool,
    pub live_presentation_gameworld_overlay_live_wave187_ok: bool,
    pub executable_gameworld_presentation_method_names_wave188_ok: bool,
    pub executable_gameworld_presentation_nav_commands_wave188_ok: bool,
    pub executable_gameworld_presentation_live_wave188_ok: bool,
    pub live_presentation_overlay_deepen_method_names_wave189_ok: bool,
    pub live_presentation_overlay_deepen_nav_commands_wave189_ok: bool,
    pub live_presentation_overlay_deepen_live_wave189_ok: bool,
    pub live_presentation_overlay_stamp_method_names_wave190_ok: bool,
    pub live_presentation_overlay_stamp_nav_commands_wave190_ok: bool,
    pub live_presentation_overlay_stamp_live_wave190_ok: bool,
    pub live_gameworld_entity_view_deepen_method_names_wave191_ok: bool,
    pub live_gameworld_entity_view_deepen_nav_commands_wave191_ok: bool,
    pub live_gameworld_entity_view_deepen_live_wave191_ok: bool,
    pub live_presentation_append_missing_method_names_wave192_ok: bool,
    pub live_presentation_append_missing_nav_commands_wave192_ok: bool,
    pub live_presentation_append_missing_live_wave192_ok: bool,
    pub live_presentation_build_from_gameworld_method_names_wave193_ok: bool,
    pub live_presentation_build_from_gameworld_nav_commands_wave193_ok: bool,
    pub live_presentation_build_from_gameworld_live_wave193_ok: bool,
    pub live_presentation_from_gameworld_default_method_names_wave194_ok: bool,
    pub live_presentation_from_gameworld_default_nav_commands_wave194_ok: bool,
    pub live_presentation_from_gameworld_default_live_wave194_ok: bool,
    pub live_presentation_build_for_engine_method_names_wave195_ok: bool,
    pub live_presentation_build_for_engine_nav_commands_wave195_ok: bool,
    pub live_presentation_build_for_engine_live_wave195_ok: bool,
    pub live_presentation_rebuilt_vertical_gate_method_names_wave196_ok: bool,
    pub live_presentation_rebuilt_vertical_gate_nav_commands_wave196_ok: bool,
    pub live_presentation_rebuilt_vertical_gate_live_wave196_ok: bool,
    pub live_command_attack_log_method_names_wave197_ok: bool,
    pub live_command_attack_log_nav_commands_wave197_ok: bool,
    pub live_command_attack_log_live_wave197_ok: bool,
    pub live_command_guard_log_method_names_wave198_ok: bool,
    pub live_command_guard_log_nav_commands_wave198_ok: bool,
    pub live_command_guard_log_live_wave198_ok: bool,
    pub live_command_production_construction_log_method_names_wave199_ok: bool,
    pub live_command_production_construction_log_nav_commands_wave199_ok: bool,
    pub live_command_production_construction_log_live_wave199_ok: bool,
    pub live_command_rally_log_method_names_wave200_ok: bool,
    pub live_command_rally_log_nav_commands_wave200_ok: bool,
    pub live_command_rally_log_live_wave200_ok: bool,
}

pub(super) fn evaluate(pres: &crate::presentation_frame::PresentationFrame, presentation_ok: bool) -> Waves161200 {
    let _ = (pres, presentation_ok);
    Waves161200 {
        main_menu_wnd_load_method_names_wave161_ok: honesty_main_menu_wnd_load_method_names_residual_wave161(),
        main_menu_wnd_load_nav_commands_wave161_ok: honesty_main_menu_wnd_load_nav_commands_residual_wave161(),
        main_menu_wnd_load_live_wave161_ok: simulate_main_menu_wnd_prepare_load_honesty(),
        main_menu_wnd_materialise_method_names_wave162_ok: honesty_main_menu_wnd_materialise_method_names_residual_wave162(),
        main_menu_wnd_materialise_nav_commands_wave162_ok: honesty_main_menu_wnd_materialise_nav_commands_residual_wave162(),
        main_menu_wnd_materialise_live_wave162_ok: simulate_main_menu_wnd_materialise_honesty(),
        shell_stack_push_method_names_wave163_ok: honesty_shell_stack_push_method_names_residual_wave163(),
        shell_stack_push_nav_commands_wave163_ok: honesty_shell_stack_push_nav_commands_residual_wave163(),
        shell_stack_push_live_wave163_ok: simulate_shell_stack_push_honesty(),
        shell_skirmish_nav_method_names_wave164_ok: honesty_shell_skirmish_nav_method_names_residual_wave164(),
        shell_skirmish_nav_commands_wave164_ok: honesty_shell_skirmish_nav_commands_residual_wave164(),
        shell_skirmish_nav_live_wave164_ok: simulate_shell_skirmish_nav_honesty(),
        control_bar_materialise_method_names_wave165_ok: honesty_control_bar_materialise_method_names_residual_wave165(),
        control_bar_materialise_nav_commands_wave165_ok: honesty_control_bar_materialise_nav_commands_residual_wave165(),
        control_bar_materialise_live_wave165_ok: simulate_control_bar_materialise_honesty_wave165(),
        skirmish_options_wnd_method_names_wave166_ok: honesty_skirmish_options_wnd_method_names_residual_wave166(),
        skirmish_options_wnd_nav_commands_wave166_ok: honesty_skirmish_options_wnd_nav_commands_residual_wave166(),
        skirmish_options_wnd_live_wave166_ok: simulate_skirmish_options_wnd_honesty(),
        new_game_stream_method_names_wave167_ok: honesty_new_game_stream_method_names_residual_wave167(),
        new_game_stream_nav_commands_wave167_ok: honesty_new_game_stream_nav_commands_residual_wave167(),
        new_game_stream_live_wave167_ok: simulate_new_game_stream_post_drain_honesty(),
        w3d_main_menu_init_method_names_wave168_ok: honesty_w3d_main_menu_init_method_names_residual_wave168(),
        w3d_main_menu_init_nav_commands_wave168_ok: honesty_w3d_main_menu_init_nav_commands_residual_wave168(),
        w3d_main_menu_init_live_wave168_ok: simulate_w3d_main_menu_init_honesty(),
        start_game_loading_method_names_wave169_ok: honesty_start_game_loading_method_names_residual_wave169(),
        start_game_loading_nav_commands_wave169_ok: honesty_start_game_loading_nav_commands_residual_wave169(),
        start_game_loading_live_wave169_ok: simulate_start_game_loading_honesty(),
        live_map_load_method_names_wave170_ok: honesty_live_map_load_method_names_residual_wave170(),
        live_map_load_nav_commands_wave170_ok: honesty_live_map_load_nav_commands_residual_wave170(),
        live_map_load_live_wave170_ok: simulate_live_map_load_honesty(),
        live_presentation_seed_method_names_wave171_ok: honesty_live_presentation_seed_method_names_residual_wave171(),
        live_presentation_seed_nav_commands_wave171_ok: honesty_live_presentation_seed_nav_commands_residual_wave171(),
        live_presentation_seed_live_wave171_ok: simulate_live_presentation_seed_honesty(),
        live_gameworld_shadow_overlay_method_names_wave172_ok: honesty_live_gameworld_shadow_overlay_method_names_residual_wave172(),
        live_gameworld_shadow_overlay_nav_commands_wave172_ok: honesty_live_gameworld_shadow_overlay_nav_commands_residual_wave172(),
        live_gameworld_shadow_overlay_live_wave172_ok: simulate_live_gameworld_shadow_overlay_honesty(),
        single_authority_combat_method_names_wave173_ok: honesty_single_authority_combat_method_names_residual_wave173(),
        single_authority_combat_nav_commands_wave173_ok: honesty_single_authority_combat_nav_commands_residual_wave173(),
        single_authority_combat_live_wave173_ok: simulate_single_authority_combat_honesty(),
        presentation_client_boundary_method_names_wave174_ok: honesty_presentation_client_boundary_method_names_residual_wave174(),
        presentation_client_boundary_nav_commands_wave174_ok: honesty_presentation_client_boundary_nav_commands_residual_wave174(),
        presentation_client_boundary_live_wave174_ok: simulate_presentation_client_boundary_honesty(),
        golden_map_host_victory_method_names_wave175_ok: honesty_golden_map_host_victory_method_names_residual_wave175(),
        golden_map_host_victory_nav_commands_wave175_ok: honesty_golden_map_host_victory_nav_commands_residual_wave175(),
        golden_map_host_victory_live_wave175_ok: simulate_golden_map_host_victory_honesty(),
        executable_presentation_boundary_method_names_wave176_ok: honesty_executable_presentation_boundary_method_names_residual_wave176(),
        executable_presentation_boundary_nav_commands_wave176_ok: honesty_executable_presentation_boundary_nav_commands_residual_wave176(),
        executable_presentation_boundary_live_wave176_ok: simulate_executable_presentation_boundary_honesty(),
        gameworld_production_authority_method_names_wave177_ok: honesty_gameworld_production_authority_method_names_residual_wave177(),
        gameworld_production_authority_nav_commands_wave177_ok: honesty_gameworld_production_authority_nav_commands_residual_wave177(),
        gameworld_production_authority_live_wave177_ok: simulate_gameworld_production_authority_honesty(),
        gameworld_sole_tick_coupling_method_names_wave178_ok: honesty_gameworld_sole_tick_coupling_method_names_residual_wave178(),
        gameworld_sole_tick_coupling_nav_commands_wave178_ok: honesty_gameworld_sole_tick_coupling_nav_commands_residual_wave178(),
        gameworld_sole_tick_coupling_live_wave178_ok: simulate_gameworld_sole_tick_coupling_honesty(),
        movement_authority_env_ok: crate::gameworld_shadow::gameworld_movement_authority_enabled(),
        gameworld_authority_matrix_method_names_wave179_ok: honesty_gameworld_authority_matrix_method_names_residual_wave179(),
        gameworld_authority_matrix_nav_commands_wave179_ok: honesty_gameworld_authority_matrix_nav_commands_residual_wave179(),
        gameworld_authority_matrix_live_wave179_ok: simulate_gameworld_authority_matrix_honesty(),
        ai_fire_construction_authority_env_ok: {
            use crate::gameworld_shadow::{
                gameworld_ai_attack_authority_enabled, gameworld_construction_authority_enabled,
                gameworld_fire_spawn_authority_enabled,
            };
            gameworld_ai_attack_authority_enabled()
                && gameworld_construction_authority_enabled()
                && gameworld_fire_spawn_authority_enabled()
        },
        live_gameworld_production_writeback_method_names_wave180_ok: honesty_live_gameworld_production_writeback_method_names_residual_wave180(),
        live_gameworld_production_writeback_nav_commands_wave180_ok: honesty_live_gameworld_production_writeback_nav_commands_residual_wave180(),
        live_gameworld_production_writeback_live_wave180_ok: simulate_live_gameworld_production_writeback_honesty(),
        live_gameworld_construction_writeback_method_names_wave181_ok: honesty_live_gameworld_construction_writeback_method_names_residual_wave181(),
        live_gameworld_construction_writeback_nav_commands_wave181_ok: honesty_live_gameworld_construction_writeback_nav_commands_residual_wave181(),
        live_gameworld_construction_writeback_live_wave181_ok: simulate_live_gameworld_construction_writeback_honesty(),
        live_gameworld_damage_channel_method_names_wave182_ok: honesty_live_gameworld_damage_channel_method_names_residual_wave182(),
        live_gameworld_damage_channel_nav_commands_wave182_ok: honesty_live_gameworld_damage_channel_nav_commands_residual_wave182(),
        live_gameworld_damage_channel_live_wave182_ok: simulate_live_gameworld_damage_channel_honesty(),
        live_gameworld_economy_movement_method_names_wave183_ok: honesty_live_gameworld_economy_movement_method_names_residual_wave183(),
        live_gameworld_economy_movement_nav_commands_wave183_ok: honesty_live_gameworld_economy_movement_nav_commands_residual_wave183(),
        live_gameworld_economy_movement_live_wave183_ok: simulate_live_gameworld_economy_movement_honesty(),
        live_gameworld_projectile_ai_method_names_wave184_ok: honesty_live_gameworld_projectile_ai_method_names_residual_wave184(),
        live_gameworld_projectile_ai_nav_commands_wave184_ok: honesty_live_gameworld_projectile_ai_nav_commands_residual_wave184(),
        live_gameworld_projectile_ai_live_wave184_ok: simulate_live_gameworld_projectile_ai_honesty(),
        live_gameworld_fire_special_power_method_names_wave185_ok: honesty_live_gameworld_fire_special_power_method_names_residual_wave185(),
        live_gameworld_fire_special_power_nav_commands_wave185_ok: honesty_live_gameworld_fire_special_power_nav_commands_residual_wave185(),
        live_gameworld_fire_special_power_live_wave185_ok: simulate_live_gameworld_fire_special_power_honesty(),
        live_gameworld_presentation_view_method_names_wave186_ok: honesty_live_gameworld_presentation_view_method_names_residual_wave186(),
        live_gameworld_presentation_view_nav_commands_wave186_ok: honesty_live_gameworld_presentation_view_nav_commands_residual_wave186(),
        live_gameworld_presentation_view_live_wave186_ok: simulate_live_gameworld_presentation_view_honesty(),
        live_presentation_gameworld_overlay_method_names_wave187_ok: honesty_live_presentation_gameworld_overlay_method_names_residual_wave187(),
        live_presentation_gameworld_overlay_nav_commands_wave187_ok: honesty_live_presentation_gameworld_overlay_nav_commands_residual_wave187(),
        live_presentation_gameworld_overlay_live_wave187_ok: simulate_live_presentation_gameworld_overlay_honesty(),
        executable_gameworld_presentation_method_names_wave188_ok: honesty_executable_gameworld_presentation_method_names_residual_wave188(),
        executable_gameworld_presentation_nav_commands_wave188_ok: honesty_executable_gameworld_presentation_nav_commands_residual_wave188(),
        executable_gameworld_presentation_live_wave188_ok: simulate_executable_gameworld_presentation_honesty(),
        live_presentation_overlay_deepen_method_names_wave189_ok: honesty_live_presentation_overlay_deepen_method_names_residual_wave189(),
        live_presentation_overlay_deepen_nav_commands_wave189_ok: honesty_live_presentation_overlay_deepen_nav_commands_residual_wave189(),
        live_presentation_overlay_deepen_live_wave189_ok: simulate_live_presentation_overlay_deepen_honesty(),
        live_presentation_overlay_stamp_method_names_wave190_ok: honesty_live_presentation_overlay_stamp_method_names_residual_wave190(),
        live_presentation_overlay_stamp_nav_commands_wave190_ok: honesty_live_presentation_overlay_stamp_nav_commands_residual_wave190(),
        live_presentation_overlay_stamp_live_wave190_ok: simulate_live_presentation_overlay_stamp_honesty(),
        live_gameworld_entity_view_deepen_method_names_wave191_ok: honesty_live_gameworld_entity_view_deepen_method_names_residual_wave191(),
        live_gameworld_entity_view_deepen_nav_commands_wave191_ok: honesty_live_gameworld_entity_view_deepen_nav_commands_residual_wave191(),
        live_gameworld_entity_view_deepen_live_wave191_ok: simulate_live_gameworld_entity_view_deepen_honesty(),
        live_presentation_append_missing_method_names_wave192_ok: honesty_live_presentation_append_missing_method_names_residual_wave192(),
        live_presentation_append_missing_nav_commands_wave192_ok: honesty_live_presentation_append_missing_nav_commands_residual_wave192(),
        live_presentation_append_missing_live_wave192_ok: simulate_live_presentation_append_missing_honesty(),
        live_presentation_build_from_gameworld_method_names_wave193_ok: honesty_live_presentation_build_from_gameworld_method_names_residual_wave193(),
        live_presentation_build_from_gameworld_nav_commands_wave193_ok: honesty_live_presentation_build_from_gameworld_nav_commands_residual_wave193(),
        live_presentation_build_from_gameworld_live_wave193_ok: simulate_live_presentation_build_from_gameworld_honesty(),
        live_presentation_from_gameworld_default_method_names_wave194_ok: honesty_live_presentation_from_gameworld_default_method_names_residual_wave194(),
        live_presentation_from_gameworld_default_nav_commands_wave194_ok: honesty_live_presentation_from_gameworld_default_nav_commands_residual_wave194(),
        live_presentation_from_gameworld_default_live_wave194_ok: simulate_live_presentation_from_gameworld_default_honesty(),
        live_presentation_build_for_engine_method_names_wave195_ok: honesty_live_presentation_build_for_engine_method_names_residual_wave195(),
        live_presentation_build_for_engine_nav_commands_wave195_ok: honesty_live_presentation_build_for_engine_nav_commands_residual_wave195(),
        live_presentation_build_for_engine_live_wave195_ok: simulate_live_presentation_build_for_engine_honesty(),
        live_presentation_rebuilt_vertical_gate_method_names_wave196_ok: honesty_live_presentation_rebuilt_vertical_gate_method_names_residual_wave196(),
        live_presentation_rebuilt_vertical_gate_nav_commands_wave196_ok: honesty_live_presentation_rebuilt_vertical_gate_nav_commands_residual_wave196(),
        live_presentation_rebuilt_vertical_gate_live_wave196_ok: simulate_live_presentation_rebuilt_vertical_gate_honesty(),
        live_command_attack_log_method_names_wave197_ok: honesty_live_command_attack_log_method_names_residual_wave197(),
        live_command_attack_log_nav_commands_wave197_ok: honesty_live_command_attack_log_nav_commands_residual_wave197(),
        live_command_attack_log_live_wave197_ok: simulate_live_command_attack_log_honesty(),
        live_command_guard_log_method_names_wave198_ok: honesty_live_command_guard_log_method_names_residual_wave198(),
        live_command_guard_log_nav_commands_wave198_ok: honesty_live_command_guard_log_nav_commands_residual_wave198(),
        live_command_guard_log_live_wave198_ok: simulate_live_command_guard_log_honesty(),
        live_command_production_construction_log_method_names_wave199_ok: honesty_live_command_production_construction_log_method_names_residual_wave199(),
        live_command_production_construction_log_nav_commands_wave199_ok: honesty_live_command_production_construction_log_nav_commands_residual_wave199(),
        live_command_production_construction_log_live_wave199_ok: simulate_live_command_production_construction_log_honesty(),
        live_command_rally_log_method_names_wave200_ok: honesty_live_command_rally_log_method_names_residual_wave200(),
        live_command_rally_log_nav_commands_wave200_ok: honesty_live_command_rally_log_nav_commands_residual_wave200(),
        live_command_rally_log_live_wave200_ok: simulate_live_command_rally_log_honesty(),
    }
}
