[package]
name = "string_system"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
base_types = { path = "../base_types" }
memory_system = { path = "../memory_system" }
serde = {workspace = true, features = ["derive"]}
parking_lot = {workspace = true}
libc = {workspace = true}

[features]
default = []
debug = []
unicode = []
