//! Particle Buffer Implementation
//!
//! This module implements the ParticleBufferClass which manages the actual
//! particle data, updates particle states, and renders particles.

use super::line_renderer::LineGroupRenderer;
use super::point_group::*;
use super::properties::*;
use super::sorting_renderer::TriangleIndices;
use super::streak::SegmentedLineRenderer;
use glam::{Mat4, Vec3, Vec4};
use std::collections::VecDeque;
use std::sync::{Mutex, OnceLock};
use ww3d_collision::SphereClass;
use ww3d_core::ww3d::WW3D;

/// Structure for passing new particles from emitter to buffer
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct NewParticle {
    pub position: Vec3,
    pub velocity: Vec3,
    pub timestamp: u32,
    pub group_id: u8,
}

impl Default for NewParticle {
    fn default() -> Self {
        Self {
            position: Vec3::ZERO,
            velocity: Vec3::ZERO,
            timestamp: 0,
            group_id: 0,
        }
    }
}

/// Individual particle data
#[derive(Debug, Clone)]
pub struct Particle {
    pub position: Vec3,
    pub previous_position: Vec3, // For ping-pong collision detection
    pub velocity: Vec3,
    pub age: u32,
    pub max_age: u32,
    pub size: f32,
    pub color: Vec3,
    pub alpha: f32,
    pub rotation: f32,
    pub rotation_speed: f32,
    pub frame: f32,
    pub blur_time: f32,
    pub group_id: u8,
    pub timestamp: u32,
    pub color_random: Vec3,
    pub alpha_random: f32,
    pub size_random: f32,
    pub rotation_random: f32,
    pub frame_random: f32,
    pub blur_time_random: f32,
    pub orientation_random: f32,
}

impl Default for Particle {
    fn default() -> Self {
        Self {
            position: Vec3::ZERO,
            previous_position: Vec3::ZERO,
            velocity: Vec3::ZERO,
            age: 0,
            max_age: 1000,
            size: 1.0,
            color: Vec3::ONE,
            alpha: 1.0,
            rotation: 0.0,
            rotation_speed: 0.0,
            frame: 0.0,
            blur_time: 0.0,
            group_id: 0,
            timestamp: 0,
            color_random: Vec3::ZERO,
            alpha_random: 0.0,
            size_random: 0.0,
            rotation_random: 0.0,
            frame_random: 0.0,
            blur_time_random: 0.0,
            orientation_random: 0.0,
        }
    }
}

/// Particle buffer class - manages particle data and rendering
#[derive(Debug)]
pub struct ParticleBuffer {
    // Particle storage
    particles: Vec<Particle>,
    active_count: usize,

    // Circular buffer for new particles
    new_particle_queue: VecDeque<NewParticle>,
    max_new_particles: usize,

    // Properties
    pub color_property: ParticleColorProperty,
    pub opacity_property: ParticleOpacityProperty,
    pub size_property: ParticleSizeProperty,
    pub rotation_property: ParticleRotationProperty,
    pub frame_property: ParticleFrameProperty,
    pub blur_time_property: ParticleBlurTimeProperty,

    // Physics
    pub acceleration: Vec3,
    pub max_age_ms: u32,
    pub future_start_time_ms: u32,

    // Rendering
    pub render_mode: RenderMode,
    pub frame_mode: FrameMode,
    pub point_group: Option<PointGroup>,
    pub line_renderer: Option<SegmentedLineRenderer>,
    pub line_group_renderer: Option<LineGroupRenderer>,

    // State
    pub current_time_ms: u32,
    pub is_emitter_dead: bool,
    pub max_size: f32,

    // LOD
    pub lod_bias: f32,
    lod_count: usize,
    decimation_threshold: usize,
    cost: [f32; 17],
    value: [f32; 18],
    projected_area: f32,

    // Soft particles
    pub soft_particles_enabled: bool,
    pub soft_particles_fade_distance: f32,

    // Ping-pong position buffers for collision detection
    pub ping_pong_enabled: bool,
    current_position_buffer: usize, // 0 or 1
}

// Random permutation array for LOD particle decimation
// Generated by pulling numbers out of a hat (matches C++ implementation)
const PERMUTATION_ARRAY: [u32; 16] = [11, 3, 7, 14, 0, 13, 1, 2, 5, 12, 15, 6, 9, 8, 4, 10];

// No max screen size sentinel value
const NO_MAX_SCREEN_SIZE: f32 = f32::MAX;

// LOD max screen sizes for 17 possible LOD levels
static LOD_MAX_SCREEN_SIZES: OnceLock<Mutex<[f32; 17]>> = OnceLock::new();

// Predictive LOD value markers
const AT_MIN_LOD: f32 = -1.0;
const AT_MAX_LOD: f32 = 1000000.0;

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum RenderMode {
    TriParticles = 0,
    QuadParticles = 1,
    Line = 2,
    LineGroup = 3,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum FrameMode {
    Frame1x1 = 0,
    Frame2x2 = 1,
    Frame4x4 = 2,
    Frame8x8 = 3,
    Frame16x16 = 4,
}

/// CPU-side particle geometry submitted to the sorting renderer.
#[derive(Debug, Clone, Default)]
pub struct ParticleSortGeometry {
    pub vertices: Vec<Vec3>,
    pub indices: Vec<TriangleIndices>,
}

impl ParticleBuffer {
    /// Create a new particle buffer
    pub fn new(
        buffer_size: usize,
        color_prop: ParticleColorProperty,
        opacity_prop: ParticleOpacityProperty,
        size_prop: ParticleSizeProperty,
        rotation_prop: ParticleRotationProperty,
        frame_prop: ParticleFrameProperty,
        blur_time_prop: ParticleBlurTimeProperty,
        acceleration: Vec3,
        max_age_ms: u32,
        future_start_time_ms: u32,
        render_mode: RenderMode,
        frame_mode: FrameMode,
        point_group: Option<PointGroup>,
        line_renderer: Option<SegmentedLineRenderer>,
        line_group_renderer: Option<LineGroupRenderer>,
    ) -> Self {
        let max_new_particles = buffer_size.min(1024); // Reasonable limit

        // Calculate LOD count (min 17 or buffer_size)
        let lod_count = buffer_size.min(17);

        let mut buffer = Self {
            particles: vec![Particle::default(); buffer_size],
            active_count: 0,
            new_particle_queue: VecDeque::with_capacity(max_new_particles),
            max_new_particles,
            color_property: color_prop,
            opacity_property: opacity_prop,
            size_property: size_prop,
            rotation_property: rotation_prop,
            frame_property: frame_prop,
            blur_time_property: blur_time_prop,
            acceleration,
            max_age_ms,
            future_start_time_ms,
            render_mode,
            frame_mode,
            point_group,
            line_renderer,
            line_group_renderer,
            current_time_ms: 0,
            is_emitter_dead: false,
            max_size: 0.0,
            lod_bias: 1.0,
            lod_count,
            decimation_threshold: 0,
            cost: [0.0; 17],
            value: [0.0; 18],
            projected_area: 0.0,
            soft_particles_enabled: false,
            soft_particles_fade_distance: 1.0,
            ping_pong_enabled: false,
            current_position_buffer: 0,
        };

        // Initialize cost and value arrays with screen area of 1.0
        let min_lod = buffer.calculate_cost_value_arrays(1.0);

        // Ensure LOD is no less than minimum allowed
        if buffer.get_lod_level() < min_lod {
            buffer.set_lod_level(min_lod);
        }

        buffer
    }

    /// Add a new particle to the buffer
    pub fn add_new_particle(&mut self, particle: NewParticle) {
        if self.new_particle_queue.len() < self.max_new_particles {
            self.new_particle_queue.push_back(particle);
        } else {
            // Overwrite oldest particle
            self.new_particle_queue.pop_front();
            self.new_particle_queue.push_back(particle);
        }
    }

    /// Update particle states
    pub fn update(&mut self, delta_time_ms: u32) {
        // Process newly emitted particles regardless of elapsed time.
        self.process_new_particles();

        let mut effective_delta_ms = delta_time_ms;
        let previous_time = self.current_time_ms;
        let sync_time = WW3D::sync_time();

        if sync_time != 0 {
            self.current_time_ms = sync_time;
            if previous_time != 0 {
                effective_delta_ms = sync_time.saturating_sub(previous_time);
            }
        } else {
            self.current_time_ms = self.current_time_ms.saturating_add(delta_time_ms);
        }

        if effective_delta_ms == 0 {
            return;
        }

        let delta_time_seconds = effective_delta_ms as f32 / 1000.0;

        // Update existing particles
        self.update_existing_particles(delta_time_seconds, effective_delta_ms);

        // Kill old particles
        self.kill_old_particles();
    }

    /// Process new particles from the queue
    fn process_new_particles(&mut self) {
        while let Some(new_particle) = self.new_particle_queue.pop_front() {
            if self.active_count < self.particles.len() {
                let index = self.active_count;
                let color_random = self.color_property.random_offset();
                let alpha_random = self.opacity_property.random_offset();
                let size_random = self.size_property.random_offset();
                let (rotation_speed_random, orientation_random) =
                    self.rotation_property.random_offsets();
                let rotation_speed = self.rotation_property.sample(0.0, &rotation_speed_random);
                let frame_random = self.frame_property.random_offset();
                let blur_time_random = self.blur_time_property.random_offset();

                // Use the emitter-provided timestamp if available, otherwise fall back to the
                // buffer's running clock prior to this update.
                let spawn_timestamp = if new_particle.timestamp == 0 {
                    self.current_time_ms
                } else {
                    new_particle.timestamp
                };

                self.particles[index] = Particle {
                    position: new_particle.position,
                    previous_position: new_particle.position,
                    velocity: new_particle.velocity,
                    age: 0,
                    max_age: self.max_age_ms,
                    size: self.size_property.sample(0.0, &size_random).max(0.0),
                    color: self.color_property.sample(0.0, &color_random),
                    alpha: self
                        .opacity_property
                        .sample(0.0, &alpha_random)
                        .clamp(0.0, 1.0),
                    rotation: orientation_random,
                    rotation_speed,
                    frame: self.frame_property.sample(0.0, &frame_random),
                    blur_time: self.blur_time_property.sample(0.0, &blur_time_random),
                    group_id: new_particle.group_id,
                    timestamp: spawn_timestamp,
                    color_random,
                    alpha_random,
                    size_random,
                    rotation_random: rotation_speed_random,
                    frame_random,
                    blur_time_random,
                    orientation_random,
                };
                self.active_count += 1;
                self.max_size = self.max_size.max(self.particles[index].size);
            }
        }
    }

    /// Update existing particles
    fn update_existing_particles(&mut self, delta_time_seconds: f32, delta_time_ms: u32) {
        self.max_size = 0.0;

        for i in 0..self.active_count {
            let particle = &mut self.particles[i];
            particle.age = particle.age.saturating_add(delta_time_ms);

            // Store previous position for ping-pong collision detection
            if self.ping_pong_enabled {
                particle.previous_position = particle.position;
            }

            // Update position and velocity
            particle.velocity += self.acceleration * delta_time_seconds;
            particle.position += particle.velocity * delta_time_seconds;

            // Update visual properties
            let age_normalized = (particle.age as f32 / particle.max_age as f32).clamp(0.0, 1.0);
            particle.size = self
                .size_property
                .sample(age_normalized, &particle.size_random)
                .max(0.0);
            particle.color = self
                .color_property
                .sample(age_normalized, &particle.color_random);
            particle.alpha = self
                .opacity_property
                .sample(age_normalized, &particle.alpha_random)
                .clamp(0.0, 1.0);
            let rotation_speed = self
                .rotation_property
                .sample(age_normalized, &particle.rotation_random);
            particle.rotation_speed = rotation_speed;
            particle.rotation =
                (particle.rotation + rotation_speed * delta_time_seconds).rem_euclid(1.0);
            particle.frame = self
                .frame_property
                .sample(age_normalized, &particle.frame_random);
            particle.blur_time = self
                .blur_time_property
                .sample(age_normalized, &particle.blur_time_random);

            self.max_size = self.max_size.max(particle.size);
        }
    }

    /// Kill particles that have exceeded their maximum age
    fn kill_old_particles(&mut self) {
        let mut new_active_count = 0;

        for i in 0..self.active_count {
            if self.particles[i].age < self.particles[i].max_age {
                if new_active_count != i {
                    self.particles.swap(new_active_count, i);
                }
                new_active_count += 1;
            }
        }

        self.active_count = new_active_count;
    }

    /// Get the number of active particles
    pub fn get_active_count(&self) -> usize {
        self.active_count
    }

    /// Build a CPU geometry snapshot for transparent particle sorting.
    pub fn sorting_geometry_snapshot(&self) -> Option<ParticleSortGeometry> {
        if self.active_count == 0 {
            return None;
        }

        let active_indices = self.get_active_particles_with_lod();
        if active_indices.is_empty() {
            return None;
        }

        let mut geometry = ParticleSortGeometry::default();
        match self.render_mode {
            RenderMode::TriParticles => {
                geometry.vertices.reserve(active_indices.len() * 3);
                geometry.indices.reserve(active_indices.len());

                for particle_index in active_indices {
                    if geometry.vertices.len().saturating_add(3) > u16::MAX as usize {
                        break;
                    }
                    let particle = &self.particles[particle_index];
                    let half_size = particle.size * 0.5;
                    let base = geometry.vertices.len() as u16;
                    geometry.vertices.extend([
                        particle.position + Vec3::new(-half_size, -half_size, 0.0),
                        particle.position + Vec3::new(half_size, -half_size, 0.0),
                        particle.position + Vec3::new(0.0, half_size, 0.0),
                    ]);
                    geometry.indices.push(TriangleIndices {
                        i: base,
                        j: base + 1,
                        k: base + 2,
                    });
                }
            }
            RenderMode::QuadParticles => {
                geometry.vertices.reserve(active_indices.len() * 4);
                geometry.indices.reserve(active_indices.len() * 2);

                for particle_index in active_indices {
                    if geometry.vertices.len().saturating_add(4) > u16::MAX as usize {
                        break;
                    }
                    let particle = &self.particles[particle_index];
                    let half_size = particle.size * 0.5;
                    let base = geometry.vertices.len() as u16;
                    geometry.vertices.extend([
                        particle.position + Vec3::new(-half_size, -half_size, 0.0),
                        particle.position + Vec3::new(half_size, -half_size, 0.0),
                        particle.position + Vec3::new(half_size, half_size, 0.0),
                        particle.position + Vec3::new(-half_size, half_size, 0.0),
                    ]);
                    geometry.indices.extend([
                        TriangleIndices {
                            i: base,
                            j: base + 1,
                            k: base + 2,
                        },
                        TriangleIndices {
                            i: base + 2,
                            j: base + 3,
                            k: base,
                        },
                    ]);
                }
            }
            RenderMode::Line | RenderMode::LineGroup => return None,
        }

        Some(geometry)
    }

    /// Get the maximum buffer size
    pub fn get_max_particles(&self) -> usize {
        self.particles.len()
    }

    /// Check if the buffer is complete (no more particles and emitter is dead)
    pub fn is_complete(&self) -> bool {
        self.active_count == 0 && self.is_emitter_dead
    }

    /// Mark the emitter as dead
    pub fn emitter_is_dead(&mut self) {
        self.is_emitter_dead = true;
    }

    /// Reset colors property
    pub fn reset_colors(&mut self, new_colors: ParticleColorProperty) {
        self.color_property = new_colors;
    }

    /// Reset opacity property
    pub fn reset_opacity(&mut self, new_opacity: ParticleOpacityProperty) {
        self.opacity_property = new_opacity;
    }

    /// Reset size property
    pub fn reset_sizes(&mut self, new_sizes: ParticleSizeProperty) {
        self.size_property = new_sizes;
    }

    /// Reset rotation property
    pub fn reset_rotations(
        &mut self,
        mut new_rotations: ParticleRotationProperty,
        orient_random: f32,
    ) {
        new_rotations.set_orient_random(orient_random);
        self.rotation_property = new_rotations;
    }

    /// Reset frame property
    pub fn reset_frames(&mut self, new_frames: ParticleFrameProperty) {
        self.frame_property = new_frames;
    }

    /// Reset blur time property
    pub fn reset_blur_times(&mut self, new_blur_times: ParticleBlurTimeProperty) {
        self.blur_time_property = new_blur_times;
    }

    /// Set acceleration
    pub fn set_acceleration(&mut self, acceleration: Vec3) {
        self.acceleration = acceleration;
    }

    /// Get acceleration
    pub fn get_acceleration(&self) -> Vec3 {
        self.acceleration
    }

    /// Get lifetime in seconds
    pub fn get_lifetime(&self) -> f32 {
        self.max_age_ms as f32 / 1000.0
    }

    /// Get future start time in seconds
    pub fn get_future_start_time(&self) -> f32 {
        self.future_start_time_ms as f32 / 1000.0
    }

    /// Get start color
    pub fn get_start_color(&self) -> Vec3 {
        self.color_property.sample(0.0, &Vec3::ZERO)
    }

    /// Get start opacity
    pub fn get_start_opacity(&self) -> f32 {
        self.opacity_property.sample(0.0, &0.0_f32)
    }

    /// Get end color
    pub fn get_end_color(&self) -> Vec3 {
        if self.color_property.num_keyframes > 1 {
            let values = self.color_property.values.as_ref().unwrap();
            values.last().cloned().unwrap_or(self.color_property.start)
        } else {
            self.color_property.start
        }
    }

    /// Get end opacity
    pub fn get_end_opacity(&self) -> f32 {
        if self.opacity_property.num_keyframes > 1 {
            let values = self.opacity_property.values.as_ref().unwrap();
            values
                .last()
                .cloned()
                .unwrap_or(self.opacity_property.start)
        } else {
            self.opacity_property.start
        }
    }

    /// Get particle size
    pub fn get_particle_size(&self) -> f32 {
        self.size_property.sample(0.0, &0.0_f32)
    }

    /// Get render mode
    pub fn get_render_mode(&self) -> RenderMode {
        self.render_mode
    }

    /// Get frame mode
    pub fn get_frame_mode(&self) -> FrameMode {
        self.frame_mode
    }

    fn max_frame_index(frame_mode: FrameMode) -> u8 {
        match frame_mode {
            FrameMode::Frame1x1 => 1,
            FrameMode::Frame2x2 => 4,
            FrameMode::Frame4x4 => 16,
            FrameMode::Frame8x8 => 64,
            FrameMode::Frame16x16 => 255, // clamp to u8 range
        }
    }

    fn clamp_frame_value(frame_mode: FrameMode, value: f32) -> u8 {
        let max_index = Self::max_frame_index(frame_mode).saturating_sub(1);
        if max_index == u8::MAX {
            value.max(0.0).min(255.0).round() as u8
        } else {
            value.max(0.0).min(max_index as f32).round() as u8
        }
    }

    fn clamp_orientation_value(value: f32) -> u8 {
        let wrapped = (value * 256.0).rem_euclid(256.0);
        wrapped.round() as u8
    }

    /// Set LOD bias
    pub fn set_lod_bias(&mut self, bias: f32) {
        self.lod_bias = bias.max(0.0);
    }

    /// Get LOD bias
    pub fn get_lod_bias(&self) -> f32 {
        self.lod_bias
    }

    /// Render the particle buffer
    pub fn render(
        &mut self,
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        encoder: &mut wgpu::CommandEncoder,
        render_pass: &mut wgpu::RenderPass<'_>,
        view_projection_matrix: Mat4,
    ) {
        if self.active_count == 0 {
            return;
        }

        match self.render_mode {
            RenderMode::TriParticles | RenderMode::QuadParticles => {
                self.render_particles(device, queue, encoder, render_pass, view_projection_matrix);
            }
            RenderMode::Line => {
                if self.line_renderer.is_some() {
                    let line_renderer = self.line_renderer.as_mut().unwrap();
                    // Convert particles to line segments
                    line_renderer.clear();

                    for i in 0..self.active_count {
                        let particle = &self.particles[i];
                        let velocity_normalized = particle.velocity.normalize_or_zero();
                        let length = particle.size * 0.5; // Use size as line length factor

                        let start_pos = particle.position - velocity_normalized * length;
                        let end_pos = particle.position + velocity_normalized * length;

                        let color = Vec4::new(
                            particle.color.x,
                            particle.color.y,
                            particle.color.z,
                            particle.alpha,
                        );

                        line_renderer.add_line(
                            start_pos,
                            end_pos,
                            color,
                            color,
                            particle.size * 0.1,
                        );
                    }

                    // Render all lines
                    line_renderer.render(
                        device,
                        queue,
                        encoder,
                        render_pass,
                        view_projection_matrix,
                    );
                }
            }
            RenderMode::LineGroup => {
                self.render_line_groups(
                    device,
                    queue,
                    encoder,
                    render_pass,
                    view_projection_matrix,
                );
            }
        }
    }

    /// Render particles as triangles or quads
    fn render_particles(
        &mut self,
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        encoder: &mut wgpu::CommandEncoder,
        render_pass: &mut wgpu::RenderPass<'_>,
        view_projection_matrix: Mat4,
    ) {
        // Skip rendering if decimation threshold is at max (all particles culled)
        if self.decimation_threshold >= self.lod_count - 1 {
            return;
        }

        // Cache values before mutable borrow
        let active_count = self.active_count;
        let frame_mode = self.frame_mode;
        let decimation_threshold = self.decimation_threshold;

        if let Some(ref mut point_group) = self.point_group {
            // Update point group data with LOD decimation
            point_group.clear();

            for i in 0..active_count {
                // Apply LOD decimation - inline the logic to avoid borrowing self
                let perm_index = (i & 0xF) as usize;
                if (PERMUTATION_ARRAY[perm_index] as usize) < decimation_threshold {
                    continue;
                }

                let particle = &self.particles[i];
                point_group.add_point(
                    particle.position,
                    Vec4::new(
                        particle.color.x,
                        particle.color.y,
                        particle.color.z,
                        particle.alpha,
                    ),
                    particle.size,
                    Self::clamp_orientation_value(particle.rotation),
                    Self::clamp_frame_value(frame_mode, particle.frame),
                );
            }

            // Render the point group
            point_group.render(device, queue, encoder, render_pass, &view_projection_matrix);
        }
    }

    /// Render line groups (tetrahedron or prism)
    fn render_line_groups(
        &mut self,
        _device: &wgpu::Device,
        _queue: &wgpu::Queue,
        _encoder: &mut wgpu::CommandEncoder,
        render_pass: &mut wgpu::RenderPass<'_>,
        _view_projection_matrix: Mat4,
    ) {
        // Skip rendering if decimation threshold is at max (all particles culled)
        if self.decimation_threshold >= self.lod_count - 1 {
            return;
        }

        // Cache values before mutable borrow
        let active_count = self.active_count;
        let decimation_threshold = self.decimation_threshold;

        if let Some(ref mut line_group) = self.line_group_renderer {
            // Collect particle data for line group rendering
            let mut start_locs = Vec::new();
            let mut end_locs = Vec::new();
            let mut diffuse = Vec::new();
            let mut tail_diffuse = Vec::new();
            let mut sizes = Vec::new();
            let mut ucoords = Vec::new();

            for i in 0..active_count {
                // Apply LOD decimation - inline the logic to avoid borrowing self
                let perm_index = (i & 0xF) as usize;
                if (PERMUTATION_ARRAY[perm_index] as usize) < decimation_threshold {
                    continue;
                }

                let particle = &self.particles[i];

                // Start position is current particle position
                start_locs.push(particle.position);

                // End position is particle position + velocity (for motion blur effect)
                let velocity_scaled = particle.velocity * particle.blur_time;
                end_locs.push(particle.position + velocity_scaled);

                // Head color (current particle color)
                diffuse.push(Vec4::new(
                    particle.color.x,
                    particle.color.y,
                    particle.color.z,
                    particle.alpha,
                ));

                // Tail color (can be faded or different)
                // For now, use same color but with 0 alpha for fade effect
                tail_diffuse.push(Vec4::new(
                    particle.color.x,
                    particle.color.y,
                    particle.color.z,
                    0.0,
                ));

                sizes.push(particle.size);
                ucoords.push(particle.frame);
            }

            if !start_locs.is_empty() {
                // Calculate camera up and right vectors from view matrix
                // For now, use world space up and right
                let camera_up = Vec3::Y;
                let camera_right = Vec3::X;

                line_group.render(
                    render_pass,
                    &start_locs,
                    &end_locs,
                    Some(&diffuse),
                    Some(&tail_diffuse),
                    Some(&sizes),
                    Some(&ucoords),
                    camera_up,
                    camera_right,
                );
            }
        }
    }

    /// Get bounding sphere for culling
    pub fn get_bounding_sphere(&self) -> SphereClass {
        if self.active_count == 0 {
            return SphereClass::new(Vec3::ZERO, 0.0);
        }

        let mut min = Vec3::splat(f32::MAX);
        let mut max = Vec3::splat(f32::MIN);

        for i in 0..self.active_count {
            let pos = self.particles[i].position;
            min = min.min(pos);
            max = max.max(pos);
        }

        let center = (min + max) * 0.5;
        let radius = (max - min).length() * 0.5 + self.max_size;

        SphereClass::new(center, radius)
    }

    /// Get bounding box for culling
    pub fn get_bounding_box(&self) -> (Vec3, Vec3) {
        if self.active_count == 0 {
            return (Vec3::ZERO, Vec3::ZERO);
        }

        let mut min = Vec3::splat(f32::MAX);
        let mut max = Vec3::splat(f32::MIN);

        for i in 0..self.active_count {
            let pos = self.particles[i].position;
            let size = self.particles[i].size;
            min = min.min(pos - Vec3::splat(size));
            max = max.max(pos + Vec3::splat(size));
        }

        (min, max)
    }

    /// Sort particles by depth for proper alpha blending
    pub fn sort_particles_by_depth(&mut self, camera_position: Vec3) {
        if self.active_count <= 1 {
            return;
        }

        // Calculate distances from camera
        let mut indices: Vec<usize> = (0..self.active_count).collect();

        indices.sort_by(|&a, &b| {
            let dist_a = (self.particles[a].position - camera_position).length_squared();
            let dist_b = (self.particles[b].position - camera_position).length_squared();
            dist_b
                .partial_cmp(&dist_a)
                .unwrap_or(std::cmp::Ordering::Equal)
        });

        // Reorder particles based on sorted indices
        let mut sorted_particles = vec![Particle::default(); self.active_count];
        for (new_index, &old_index) in indices.iter().enumerate() {
            sorted_particles[new_index] = self.particles[old_index].clone();
        }

        for (i, particle) in sorted_particles.into_iter().enumerate() {
            self.particles[i] = particle;
        }
    }

    /// Enable/disable soft particles (depth-based fade)
    pub fn set_soft_particles(&mut self, enabled: bool, fade_distance: f32) {
        self.soft_particles_enabled = enabled;
        self.soft_particles_fade_distance = fade_distance;
    }

    // ============================================================================
    // Ping-Pong Position Buffers (for collision detection and effects)
    // ============================================================================

    /// Enable/disable ping-pong position buffers
    /// When enabled, particles track both current and previous positions
    /// This is useful for collision detection and motion blur effects
    pub fn set_ping_pong_enabled(&mut self, enabled: bool) {
        self.ping_pong_enabled = enabled;
        if enabled {
            // Initialize previous positions with current positions
            for i in 0..self.active_count {
                self.particles[i].previous_position = self.particles[i].position;
            }
        }
    }

    /// Check if ping-pong buffers are enabled
    pub fn is_ping_pong_enabled(&self) -> bool {
        self.ping_pong_enabled
    }

    /// Get current position buffer index (0 or 1)
    pub fn get_current_position_buffer(&self) -> usize {
        self.current_position_buffer
    }

    /// Swap position buffers (advance to next frame)
    pub fn swap_position_buffers(&mut self) {
        if self.ping_pong_enabled {
            self.current_position_buffer = 1 - self.current_position_buffer;
        }
    }

    /// Get particle's previous position (for collision/trail effects)
    pub fn get_particle_previous_position(&self, index: usize) -> Option<Vec3> {
        if self.ping_pong_enabled && index < self.active_count {
            Some(self.particles[index].previous_position)
        } else {
            None
        }
    }

    /// Get motion vector for a particle (current - previous position)
    pub fn get_particle_motion_vector(&self, index: usize) -> Option<Vec3> {
        if self.ping_pong_enabled && index < self.active_count {
            let particle = &self.particles[index];
            Some(particle.position - particle.previous_position)
        } else {
            None
        }
    }

    // ============================================================================
    // LOD (Level of Detail) System
    // ============================================================================

    /// Prepare LOD based on camera parameters and screen area
    pub fn prepare_lod(
        &mut self,
        camera_position: Vec3,
        viewport_width: f32,
        viewport_height: f32,
        view_plane_size: (f32, f32),
    ) {
        // Calculate screen area projection
        let sphere = self.get_bounding_sphere();
        let dist = (sphere.center - camera_position).length();

        let (view_plane_width, view_plane_height) = view_plane_size;
        let width_factor = viewport_width / view_plane_width;
        let height_factor = viewport_height / view_plane_height;

        let bounding_sphere_projected_radius = if dist > 0.0 {
            sphere.radius / dist
        } else {
            0.0
        };

        let particle_projected_radius = if dist > 0.0 {
            self.max_size / dist
        } else {
            0.0
        };

        let bs_rad_sq = bounding_sphere_projected_radius * bounding_sphere_projected_radius;
        let p_rad_sq =
            particle_projected_radius * particle_projected_radius * self.particles.len() as f32;
        let proj_area =
            std::f32::consts::PI * bs_rad_sq.min(p_rad_sq) * width_factor * height_factor;

        // Filter the area over time to reduce LOD popping
        self.projected_area = 0.9 * self.projected_area + 0.1 * proj_area;

        // Calculate cost/value arrays
        let min_lod = self.calculate_cost_value_arrays(self.projected_area);

        // Ensure LOD is no less than minimum allowed
        if self.get_lod_level() < min_lod {
            self.set_lod_level(min_lod);
        }
    }

    /// Calculate cost and value arrays for LOD selection
    fn calculate_cost_value_arrays(&mut self, screen_area: f32) -> usize {
        // Calculate cost heuristic for each LOD level
        // Cost factor is based on 1/16 (0.0625) of total since decimation uses 16 steps
        let cost_factor = match self.render_mode {
            RenderMode::TriParticles => self.particles.len() as f32 * 0.0625,
            RenderMode::QuadParticles => self.particles.len() as f32 * 2.0 * 0.0625,
            RenderMode::Line => (2 * self.particles.len() - 1) as f32 * 0.0625,
            RenderMode::LineGroup => {
                // LineGroup has two modes (Tetrahedron=4, Prism=8)
                // Use average for now
                self.particles.len() as f32 * 6.0 * 0.0625
            }
        };

        for lod in 0..self.lod_count {
            self.cost[lod] = cost_factor * lod as f32;
            // Avoid division by zero
            if self.cost[lod] == 0.0 {
                self.cost[lod] = 0.000001;
            }
        }

        // Calculate value heuristic
        let mut lod = 0;
        {
            let lod_sizes = LOD_MAX_SCREEN_SIZES
                .get_or_init(|| Mutex::new([NO_MAX_SCREEN_SIZE; 17]))
                .lock()
                .unwrap();
            // Find first LOD where MaxScreenSize >= screen_area
            while lod < self.lod_count && lod_sizes[lod] < screen_area {
                self.value[lod] = AT_MIN_LOD;
                lod += 1;
            }
        }

        if lod >= self.lod_count {
            lod = self.lod_count - 1;
        } else {
            self.value[lod] = AT_MIN_LOD;
        }

        let min_lod = lod;

        // Calculate value for remaining LODs based on normalized screen area
        lod += 1;
        for i in lod..self.lod_count {
            let polycount = self.cost[i];
            let benefit_factor = if polycount > f32::EPSILON {
                1.0 - (0.5 / (polycount * polycount))
            } else {
                0.0
            };
            self.value[i] = (benefit_factor * screen_area * self.lod_bias) / self.cost[i];
        }
        self.value[self.lod_count] = AT_MAX_LOD;

        min_lod
    }

    /// Increment LOD (reduce quality to improve performance)
    pub fn increment_lod(&mut self) {
        if self.decimation_threshold > 0 {
            self.decimation_threshold -= 1;
        }
    }

    /// Decrement LOD (increase quality)
    pub fn decrement_lod(&mut self) {
        if self.decimation_threshold < self.lod_count {
            self.decimation_threshold += 1;
        }
    }

    /// Get current LOD cost
    pub fn get_cost(&self) -> f32 {
        let index = (self.lod_count - 1).saturating_sub(self.decimation_threshold);
        self.cost[index]
    }

    /// Get current LOD value
    pub fn get_value(&self) -> f32 {
        let index = (self.lod_count - 1).saturating_sub(self.decimation_threshold);
        self.value[index]
    }

    /// Get value after incrementing LOD
    pub fn get_post_increment_value(&self) -> f32 {
        let index = self.lod_count.saturating_sub(self.decimation_threshold);
        self.value[index]
    }

    /// Set LOD level (0 = lowest quality, lod_count-1 = highest quality)
    pub fn set_lod_level(&mut self, lod: usize) {
        let lod = lod.min(self.lod_count);
        self.decimation_threshold = (self.lod_count - 1).saturating_sub(lod);
    }

    /// Get current LOD level
    pub fn get_lod_level(&self) -> usize {
        (self.lod_count - 1).saturating_sub(self.decimation_threshold)
    }

    /// Get total LOD count
    pub fn get_lod_count(&self) -> usize {
        self.lod_count
    }

    /// Set global LOD max screen size for a specific level
    pub fn set_lod_max_screen_size(lod_level: usize, max_screen_size: f32) {
        if lod_level < 17 {
            let mut sizes = LOD_MAX_SCREEN_SIZES
                .get_or_init(|| Mutex::new([NO_MAX_SCREEN_SIZE; 17]))
                .lock()
                .unwrap();
            sizes[lod_level] = max_screen_size;
        }
    }

    /// Get global LOD max screen size for a specific level
    pub fn get_lod_max_screen_size(lod_level: usize) -> f32 {
        if lod_level < 17 {
            let sizes = LOD_MAX_SCREEN_SIZES
                .get_or_init(|| Mutex::new([NO_MAX_SCREEN_SIZE; 17]))
                .lock()
                .unwrap();
            sizes[lod_level]
        } else {
            NO_MAX_SCREEN_SIZE
        }
    }

    /// Check if particle should be rendered based on LOD decimation
    #[allow(dead_code)] // C++ parity
    fn should_render_particle(&self, particle_index: usize) -> bool {
        let perm_index = (particle_index & 0xF) as usize;
        PERMUTATION_ARRAY[perm_index] as usize >= self.decimation_threshold
    }

    /// Get active particles after LOD decimation
    #[allow(dead_code)] // C++ parity
    fn get_active_particles_with_lod(&self) -> Vec<usize> {
        let mut active_indices = Vec::new();

        for i in 0..self.active_count {
            if self.should_render_particle(i) {
                active_indices.push(i);
            }
        }

        active_indices
    }

    /// Update GPU instancing data for large particle counts
    pub fn update_instance_data(&mut self, device: &wgpu::Device, queue: &wgpu::Queue) {
        if self.active_count == 0 {
            return;
        }

        // Prepare instance data for GPU
        let mut instance_data = Vec::with_capacity(self.active_count);

        for i in 0..self.active_count {
            let particle = &self.particles[i];

            // Pack instance data: position, color, size, rotation, frame
            instance_data.push(ParticleInstanceData {
                position: [
                    particle.position.x,
                    particle.position.y,
                    particle.position.z,
                    particle.size,
                ],
                color: [
                    particle.color.x,
                    particle.color.y,
                    particle.color.z,
                    particle.alpha,
                ],
                rotation_frame: [particle.rotation, particle.frame, 0.0, 0.0],
            });
        }

        // Update instance buffer
        if let Some(ref mut point_group) = self.point_group {
            point_group.update_instance_buffer(device, queue, &instance_data);
        }
    }
}

// ParticleInstanceData is now defined in point_group.rs
use crate::point_group::ParticleInstanceData;

#[cfg(test)]
mod tests {
    use super::*;

    fn test_buffer(render_mode: RenderMode) -> ParticleBuffer {
        ParticleBuffer::new(
            8,
            ParticleColorProperty::with_start(Vec3::ONE),
            ParticleOpacityProperty::with_start(1.0),
            ParticleSizeProperty::with_start(2.0),
            ParticleRotationProperty::with_start(0.0),
            ParticleFrameProperty::with_start(0.0),
            ParticleBlurTimeProperty::with_start(0.0),
            Vec3::ZERO,
            1000,
            0,
            render_mode,
            FrameMode::Frame1x1,
            None,
            None,
            None,
        )
    }

    #[test]
    fn tri_particle_sort_snapshot_uses_real_particle_geometry() {
        let mut buffer = test_buffer(RenderMode::TriParticles);
        buffer.add_new_particle(NewParticle {
            position: Vec3::new(1.0, 2.0, 3.0),
            ..Default::default()
        });
        buffer.update(0);

        let geometry = buffer
            .sorting_geometry_snapshot()
            .expect("active tri particle should produce sort geometry");
        assert_eq!(geometry.vertices.len(), 3);
        assert_eq!(geometry.indices, vec![TriangleIndices { i: 0, j: 1, k: 2 }]);
        assert_eq!(geometry.vertices[0], Vec3::new(0.0, 1.0, 3.0));
        assert_eq!(geometry.vertices[1], Vec3::new(2.0, 1.0, 3.0));
        assert_eq!(geometry.vertices[2], Vec3::new(1.0, 3.0, 3.0));
    }

    #[test]
    fn quad_particle_sort_snapshot_outputs_two_triangles() {
        let mut buffer = test_buffer(RenderMode::QuadParticles);
        buffer.add_new_particle(NewParticle {
            position: Vec3::new(0.0, 0.0, 5.0),
            ..Default::default()
        });
        buffer.update(0);

        let geometry = buffer
            .sorting_geometry_snapshot()
            .expect("active quad particle should produce sort geometry");
        assert_eq!(geometry.vertices.len(), 4);
        assert_eq!(
            geometry.indices,
            vec![
                TriangleIndices { i: 0, j: 1, k: 2 },
                TriangleIndices { i: 2, j: 3, k: 0 },
            ]
        );
    }

    #[test]
    fn line_particle_sort_snapshot_is_not_triangular_geometry() {
        let mut buffer = test_buffer(RenderMode::Line);
        buffer.add_new_particle(NewParticle::default());
        buffer.update(0);

        assert!(buffer.sorting_geometry_snapshot().is_none());
    }
}
