[package]
name = "math_utilities"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
rand = {workspace = true}
fastrand = {workspace = true}
lazy_static = {workspace = true}
thiserror = {workspace = true}
anyhow = {workspace = true}
glam = {workspace = true}

[features]
collision-stats = []
internal = []

[lib]
name = "math_utilities"
path = "src/lib.rs"
test = false
