[package]
name = "ww3d-particles"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
ww3d-core = { path = "../ww3d-core" }
ww3d-assets = { path = "../ww3d-assets" }
ww3d-collision = { path = "../ww3d-collision" }
glam = {workspace = true, features = ["bytemuck"]}
wgpu = {workspace = true}
winit = {workspace = true}
tokio = {workspace = true, features = ["full"]}
crossbeam = {workspace = true}
rayon = {workspace = true}
binrw = {workspace = true}
bytemuck = {workspace = true, features = ["derive"]}
thiserror = {workspace = true}
anyhow = {workspace = true}
rand = {workspace = true}
