//! C++ ScriptEngine.cpp:564-5242 template names, indexed by Scripts.h enum order.
//! Empty strings are deliberately unassigned C++ slots, not generated enum names.
use crate::scripting::core::{ConditionType, ScriptActionType};

pub(super) const CONDITION_INTERNAL_NAMES: [&str; ConditionType::NumItems as usize] = [
    "CONDITION_FALSE",                                 // ConditionFalse
    "COUNTER",                                         // Counter
    "FLAG",                                            // Flag
    "CONDITION_TRUE",                                  // ConditionTrue
    "TIMER_EXPIRED",                                   // TimerExpired
    "PLAYER_ALL_DESTROYED",                            // PlayerAllDestroyed
    "PLAYER_ALL_BUILDFACILITIES_DESTROYED",            // PlayerAllBuildfacilitiesDestroyed
    "TEAM_INSIDE_AREA_PARTIALLY",                      // TeamInsideAreaPartially
    "TEAM_DESTROYED",                                  // TeamDestroyed
    "CAMERA_MOVEMENT_FINISHED",                        // CameraMovementFinished
    "TEAM_HAS_UNITS",                                  // TeamHasUnits
    "TEAM_STATE_IS",                                   // TeamStateIs
    "TEAM_STATE_IS_NOT",                               // TeamStateIsNot
    "NAMED_INSIDE_AREA",                               // NamedInsideArea
    "NAMED_OUTSIDE_AREA",                              // NamedOutsideArea
    "NAMED_DESTROYED",                                 // NamedDestroyed
    "NAMED_NOT_DESTROYED",                             // NamedNotDestroyed
    "TEAM_INSIDE_AREA_ENTIRELY",                       // TeamInsideAreaEntirely
    "TEAM_OUTSIDE_AREA_ENTIRELY",                      // TeamOutsideAreaEntirely
    "NAMED_ATTACKED_BY_OBJECTTYPE",                    // NamedAttackedByObjecttype
    "TEAM_ATTACKED_BY_OBJECTTYPE",                     // TeamAttackedByObjecttype
    "NAMED_ATTACKED_BY_PLAYER",                        // NamedAttackedByPlayer
    "TEAM_ATTACKED_BY_PLAYER",                         // TeamAttackedByPlayer
    "BUILT_BY_PLAYER",                                 // BuiltByPlayer
    "NAMED_CREATED",                                   // NamedCreated
    "TEAM_CREATED",                                    // TeamCreated
    "PLAYER_HAS_CREDITS",                              // PlayerHasCredits
    "NAMED_DISCOVERED",                                // NamedDiscovered
    "TEAM_DISCOVERED",                                 // TeamDiscovered
    "MISSION_ATTEMPTS",                                // MissionAttempts
    "NAMED_OWNED_BY_PLAYER",                           // NamedOwnedByPlayer
    "TEAM_OWNED_BY_PLAYER",                            // TeamOwnedByPlayer
    "PLAYER_HAS_N_OR_FEWER_BUILDINGS",                 // PlayerHasNOrFewerBuildings
    "PLAYER_HAS_POWER",                                // PlayerHasPower
    "NAMED_REACHED_WAYPOINTS_END",                     // NamedReachedWaypointsEnd
    "TEAM_REACHED_WAYPOINTS_END",                      // TeamReachedWaypointsEnd
    "NAMED_SELECTED",                                  // NamedSelected
    "NAMED_ENTERED_AREA",                              // NamedEnteredArea
    "NAMED_EXITED_AREA",                               // NamedExitedArea
    "TEAM_ENTERED_AREA_ENTIRELY",                      // TeamEnteredAreaEntirely
    "TEAM_ENTERED_AREA_PARTIALLY",                     // TeamEnteredAreaPartially
    "TEAM_EXITED_AREA_ENTIRELY",                       // TeamExitedAreaEntirely
    "TEAM_EXITED_AREA_PARTIALLY",                      // TeamExitedAreaPartially
    "MULTIPLAYER_ALLIED_VICTORY",                      // MultiplayerAlliedVictory
    "MULTIPLAYER_ALLIED_DEFEAT",                       // MultiplayerAlliedDefeat
    "MULTIPLAYER_PLAYER_DEFEAT",                       // MultiplayerPlayerDefeat
    "PLAYER_HAS_NO_POWER",                             // PlayerHasNoPower
    "HAS_FINISHED_VIDEO",                              // HasFinishedVideo
    "HAS_FINISHED_SPEECH",                             // HasFinishedSpeech
    "HAS_FINISHED_AUDIO",                              // HasFinishedAudio
    "BUILDING_ENTERED_BY_PLAYER",                      // BuildingEnteredByPlayer
    "ENEMY_SIGHTED",                                   // EnemySighted
    "UNIT_HEALTH",                                     // UnitHealth
    "BRIDGE_REPAIRED",                                 // BridgeRepaired
    "BRIDGE_BROKEN",                                   // BridgeBroken
    "NAMED_DYING",                                     // NamedDying
    "NAMED_TOTALLY_DEAD",                              // NamedTotallyDead
    "PLAYER_HAS_OBJECT_COMPARISON",                    // PlayerHasObjectComparison
    "",                                                // ObsoleteScript1
    "",                                                // ObsoleteScript2
    "PLAYER_TRIGGERED_SPECIAL_POWER",                  // PlayerTriggeredSpecialPower
    "PLAYER_COMPLETED_SPECIAL_POWER",                  // PlayerCompletedSpecialPower
    "PLAYER_MIDWAY_SPECIAL_POWER",                     // PlayerMidwaySpecialPower
    "PLAYER_TRIGGERED_SPECIAL_POWER_FROM_NAMED",       // PlayerTriggeredSpecialPowerFromNamed
    "PLAYER_COMPLETED_SPECIAL_POWER_FROM_NAMED",       // PlayerCompletedSpecialPowerFromNamed
    "PLAYER_MIDWAY_SPECIAL_POWER_FROM_NAMED",          // PlayerMidwaySpecialPowerFromNamed
    "",                                                // DefunctPlayerSelectedGeneral
    "",                                                // DefunctPlayerSelectedGeneralFromNamed
    "PLAYER_BUILT_UPGRADE",                            // PlayerBuiltUpgrade
    "PLAYER_BUILT_UPGRADE_FROM_NAMED",                 // PlayerBuiltUpgradeFromNamed
    "PLAYER_DESTROYED_N_BUILDINGS_PLAYER",             // PlayerDestroyedNBuildingsPlayer
    "",                                                // UnitCompletedSequentialExecution
    "",                                                // TeamCompletedSequentialExecution
    "PLAYER_HAS_COMPARISON_UNIT_TYPE_IN_TRIGGER_AREA", // PlayerHasComparisonUnitTypeInTriggerArea
    "PLAYER_HAS_COMPARISON_UNIT_KIND_IN_TRIGGER_AREA", // PlayerHasComparisonUnitKindInTriggerArea
    "UNIT_EMPTIED",                                    // UnitEmptied
    "TYPE_SIGHTED",                                    // TypeSighted
    "NAMED_BUILDING_IS_EMPTY",                         // NamedBuildingIsEmpty
    "PLAYER_HAS_N_OR_FEWER_FACTION_BUILDINGS",         // PlayerHasNOrFewerFactionBuildings
    "UNIT_HAS_OBJECT_STATUS",                          // UnitHasObjectStatus
    "TEAM_ALL_HAS_OBJECT_STATUS",                      // TeamAllHasObjectStatus
    "TEAM_SOME_HAVE_OBJECT_STATUS",                    // TeamSomeHaveObjectStatus
    "PLAYER_POWER_COMPARE_PERCENT",                    // PlayerPowerComparePercent
    "PLAYER_EXCESS_POWER_COMPARE_VALUE",               // PlayerExcessPowerCompareValue
    "SKIRMISH_SPECIAL_POWER_READY",                    // SkirmishSpecialPowerReady
    "SKIRMISH_VALUE_IN_AREA",                          // SkirmishValueInArea
    "SKIRMISH_PLAYER_FACTION",                         // SkirmishPlayerFaction
    "SKIRMISH_SUPPLIES_VALUE_WITHIN_DISTANCE",         // SkirmishSuppliesValueWithinDistance
    "SKIRMISH_TECH_BUILDING_WITHIN_DISTANCE",          // SkirmishTechBuildingWithinDistance
    "SKIRMISH_COMMAND_BUTTON_READY_ALL",               // SkirmishCommandButtonReadyAll
    "SKIRMISH_COMMAND_BUTTON_READY_PARTIAL",           // SkirmishCommandButtonReadyPartial
    "SKIRMISH_UNOWNED_FACTION_UNIT_EXISTS",            // SkirmishUnownedFactionUnitExists
    "SKIRMISH_PLAYER_HAS_PREREQUISITE_TO_BUILD",       // SkirmishPlayerHasPrerequisiteToBuild
    "SKIRMISH_PLAYER_HAS_COMPARISON_GARRISONED",       // SkirmishPlayerHasComparisonGarrisoned
    "SKIRMISH_PLAYER_HAS_COMPARISON_CAPTURED_UNITS",   // SkirmishPlayerHasComparisonCapturedUnits
    "SKIRMISH_NAMED_AREA_EXIST",                       // SkirmishNamedAreaExist
    "SKIRMISH_PLAYER_HAS_UNITS_IN_AREA",               // SkirmishPlayerHasUnitsInArea
    "SKIRMISH_PLAYER_HAS_BEEN_ATTACKED_BY_PLAYER",     // SkirmishPlayerHasBeenAttackedByPlayer
    "SKIRMISH_PLAYER_IS_OUTSIDE_AREA",                 // SkirmishPlayerIsOutsideArea
    "SKIRMISH_PLAYER_HAS_DISCOVERED_PLAYER",           // SkirmishPlayerHasDiscoveredPlayer
    "PLAYER_ACQUIRED_SCIENCE",                         // PlayerAcquiredScience
    "PLAYER_HAS_SCIENCEPURCHASEPOINTS",                // PlayerHasSciencepurchasepoints
    "PLAYER_CAN_PURCHASE_SCIENCE",                     // PlayerCanPurchaseScience
    "MUSIC_TRACK_HAS_COMPLETED",                       // MusicTrackHasCompleted
    "PLAYER_LOST_OBJECT_TYPE",                         // PlayerLostObjectType
    "SUPPLY_SOURCE_SAFE",                              // SupplySourceSafe
    "SUPPLY_SOURCE_ATTACKED",                          // SupplySourceAttacked
    "START_POSITION_IS",                               // StartPositionIs
    "NAMED_HAS_FREE_CONTAINER_SLOTS",                  // NamedHasFreeContainerSlots
];

pub(super) const ACTION_INTERNAL_NAMES: [&str; ScriptActionType::NumItems as usize] = [
    "DEBUG_MESSAGE_BOX",                                          // DebugMessageBox
    "SET_FLAG",                                                   // SetFlag
    "SET_COUNTER",                                                // SetCounter
    "VICTORY",                                                    // Victory
    "DEFEAT",                                                     // Defeat
    "NO_OP",                                                      // NoOp
    "SET_TIMER",                                                  // SetTimer
    "PLAY_SOUND_EFFECT",                                          // PlaySoundEffect
    "ENABLE_SCRIPT",                                              // EnableScript
    "DISABLE_SCRIPT",                                             // DisableScript
    "CALL_SUBROUTINE",                                            // CallSubroutine
    "PLAY_SOUND_EFFECT_AT",                                       // PlaySoundEffectAt
    "DAMAGE_MEMBERS_OF_TEAM",                                     // DamageMembersOfTeam
    "MOVE_TEAM_TO",                                               // MoveTeamTo
    "MOVE_CAMERA_TO",                                             // MoveCameraTo
    "INCREMENT_COUNTER",                                          // IncrementCounter
    "DECREMENT_COUNTER",                                          // DecrementCounter
    "MOVE_CAMERA_ALONG_WAYPOINT_PATH",                            // MoveCameraAlongWaypointPath
    "ROTATE_CAMERA",                                              // RotateCamera
    "RESET_CAMERA",                                               // ResetCamera
    "SET_MILLISECOND_TIMER",                                      // SetMillisecondTimer
    "CAMERA_MOD_FREEZE_TIME",                                     // CameraModFreezeTime
    "SET_VISUAL_SPEED_MULTIPLIER",                                // SetVisualSpeedMultiplier
    "CREATE_OBJECT",                                              // CreateObject
    "SUSPEND_BACKGROUND_SOUNDS",                                  // SuspendBackgroundSounds
    "RESUME_BACKGROUND_SOUNDS",                                   // ResumeBackgroundSounds
    "CAMERA_MOD_SET_FINAL_ZOOM",                                  // CameraModSetFinalZoom
    "CAMERA_MOD_SET_FINAL_PITCH",                                 // CameraModSetFinalPitch
    "CAMERA_MOD_FREEZE_ANGLE",                                    // CameraModFreezeAngle
    "CAMERA_MOD_SET_FINAL_SPEED_MULTIPLIER", // CameraModSetFinalSpeedMultiplier
    "CAMERA_MOD_SET_ROLLING_AVERAGE",        // CameraModSetRollingAverage
    "CAMERA_MOD_FINAL_LOOK_TOWARD",          // CameraModFinalLookToward
    "CAMERA_MOD_LOOK_TOWARD",                // CameraModLookToward
    "TEAM_ATTACK_TEAM",                      // TeamAttackTeam
    "CREATE_REINFORCEMENT_TEAM",             // CreateReinforcementTeam
    "MOVE_CAMERA_TO_SELECTION",              // MoveCameraToSelection
    "TEAM_FOLLOW_WAYPOINTS",                 // TeamFollowWaypoints
    "TEAM_SET_STATE",                        // TeamSetState
    "MOVE_NAMED_UNIT_TO",                    // MoveNamedUnitTo
    "NAMED_ATTACK_NAMED",                    // NamedAttackNamed
    "CREATE_NAMED_ON_TEAM_AT_WAYPOINT",      // CreateNamedOnTeamAtWaypoint
    "CREATE_UNNAMED_ON_TEAM_AT_WAYPOINT",    // CreateUnnamedOnTeamAtWaypoint
    "NAMED_APPLY_ATTACK_PRIORITY_SET",       // NamedApplyAttackPrioritySet
    "TEAM_APPLY_ATTACK_PRIORITY_SET",        // TeamApplyAttackPrioritySet
    "SET_BASE_CONSTRUCTION_SPEED",           // SetBaseConstructionSpeed
    "NAMED_SET_ATTITUDE",                    // NamedSetAttitude
    "TEAM_SET_ATTITUDE",                     // TeamSetAttitude
    "NAMED_ATTACK_AREA",                     // NamedAttackArea
    "NAMED_ATTACK_TEAM",                     // NamedAttackTeam
    "TEAM_ATTACK_AREA",                      // TeamAttackArea
    "TEAM_ATTACK_NAMED",                     // TeamAttackNamed
    "TEAM_LOAD_TRANSPORTS",                  // TeamLoadTransports
    "NAMED_ENTER_NAMED",                     // NamedEnterNamed
    "TEAM_ENTER_NAMED",                      // TeamEnterNamed
    "NAMED_EXIT_ALL",                        // NamedExitAll
    "TEAM_EXIT_ALL",                         // TeamExitAll
    "NAMED_FOLLOW_WAYPOINTS",                // NamedFollowWaypoints
    "NAMED_GUARD",                           // NamedGuard
    "TEAM_GUARD",                            // TeamGuard
    "NAMED_HUNT",                            // NamedHunt
    "TEAM_HUNT",                             // TeamHunt
    "PLAYER_SELL_EVERYTHING",                // PlayerSellEverything
    "PLAYER_DISABLE_BASE_CONSTRUCTION",      // PlayerDisableBaseConstruction
    "PLAYER_DISABLE_FACTORIES",              // PlayerDisableFactories
    "PLAYER_DISABLE_UNIT_CONSTRUCTION",      // PlayerDisableUnitConstruction
    "PLAYER_ENABLE_BASE_CONSTRUCTION",       // PlayerEnableBaseConstruction
    "PLAYER_ENABLE_FACTORIES",               // PlayerEnableFactories
    "PLAYER_ENABLE_UNIT_CONSTRUCTION",       // PlayerEnableUnitConstruction
    "CAMERA_MOVE_HOME",                      // CameraMoveHome
    "BUILD_TEAM",                            // BuildTeam
    "NAMED_DAMAGE",                          // NamedDamage
    "NAMED_DELETE",                          // NamedDelete
    "TEAM_DELETE",                           // TeamDelete
    "NAMED_KILL",                            // NamedKill
    "TEAM_KILL",                             // TeamKill
    "PLAYER_KILL",                           // PlayerKill
    "DISPLAY_TEXT",                          // DisplayText
    "CAMEO_FLASH",                           // CameoFlash
    "NAMED_FLASH",                           // NamedFlash
    "TEAM_FLASH",                            // TeamFlash
    "MOVIE_PLAY_FULLSCREEN",                 // MoviePlayFullscreen
    "MOVIE_PLAY_RADAR",                      // MoviePlayRadar
    "SOUND_PLAY_NAMED",                      // SoundPlayNamed
    "SPEECH_PLAY",                           // SpeechPlay
    "PLAYER_TRANSFER_OWNERSHIP_PLAYER",      // PlayerTransferOwnershipPlayer
    "NAMED_TRANSFER_OWNERSHIP_PLAYER",       // NamedTransferOwnershipPlayer
    "PLAYER_RELATES_PLAYER",                 // PlayerRelatesPlayer
    "RADAR_CREATE_EVENT",                    // RadarCreateEvent
    "RADAR_DISABLE",                         // RadarDisable
    "RADAR_ENABLE",                          // RadarEnable
    "MAP_REVEAL_AT_WAYPOINT",                // MapRevealAtWaypoint
    "TEAM_AVAILABLE_FOR_RECRUITMENT",        // TeamAvailableForRecruitment
    "TEAM_COLLECT_NEARBY_FOR_TEAM",          // TeamCollectNearbyForTeam
    "TEAM_MERGE_INTO_TEAM",                  // TeamMergeIntoTeam
    "DISABLE_INPUT",                         // DisableInput
    "ENABLE_INPUT",                          // EnableInput
    "PLAYER_HUNT",                           // PlayerHunt
    "SOUND_AMBIENT_PAUSE",                   // SoundAmbientPause
    "SOUND_AMBIENT_RESUME",                  // SoundAmbientResume
    "MUSIC_SET_TRACK",                       // MusicSetTrack
    "SET_TREE_SWAY",                         // SetTreeSway
    "DEBUG_STRING",                          // DebugString
    "MAP_REVEAL_ALL",                        // MapRevealAll
    "TEAM_GARRISON_SPECIFIC_BUILDING",       // TeamGarrisonSpecificBuilding
    "EXIT_SPECIFIC_BUILDING",                // ExitSpecificBuilding
    "TEAM_GARRISON_NEAREST_BUILDING",        // TeamGarrisonNearestBuilding
    "TEAM_EXIT_ALL_BUILDINGS",               // TeamExitAllBuildings
    "NAMED_GARRISON_SPECIFIC_BUILDING",      // NamedGarrisonSpecificBuilding
    "NAMED_GARRISON_NEAREST_BUILDING",       // NamedGarrisonNearestBuilding
    "NAMED_EXIT_BUILDING",                   // NamedExitBuilding
    "PLAYER_GARRISON_ALL_BUILDINGS",         // PlayerGarrisonAllBuildings
    "PLAYER_EXIT_ALL_BUILDINGS",             // PlayerExitAllBuildings
    "TEAM_WANDER",                           // TeamWander
    "TEAM_PANIC",                            // TeamPanic
    "SETUP_CAMERA",                          // SetupCamera
    "CAMERA_LETTERBOX_BEGIN",                // CameraLetterboxBegin
    "CAMERA_LETTERBOX_END",                  // CameraLetterboxEnd
    "ZOOM_CAMERA",                           // ZoomCamera
    "PITCH_CAMERA",                          // PitchCamera
    "CAMERA_FOLLOW_NAMED",                   // CameraFollowNamed
    "OVERSIZE_TERRAIN",                      // OversizeTerrain
    "CAMERA_FADE_ADD",                       // CameraFadeAdd
    "CAMERA_FADE_SUBTRACT",                  // CameraFadeSubtract
    "CAMERA_FADE_SATURATE",                  // CameraFadeSaturate
    "CAMERA_FADE_MULTIPLY",                  // CameraFadeMultiply
    "CAMERA_BW_MODE_BEGIN",                  // CameraBwModeBegin
    "CAMERA_BW_MODE_END",                    // CameraBwModeEnd
    "DRAW_SKYBOX_BEGIN",                     // DrawSkyboxBegin
    "DRAW_SKYBOX_END",                       // DrawSkyboxEnd
    "SET_ATTACK_PRIORITY_THING",             // SetAttackPriorityThing
    "SET_ATTACK_PRIORITY_KIND_OF",           // SetAttackPriorityKindOf
    "SET_DEFAULT_ATTACK_PRIORITY",           // SetDefaultAttackPriority
    "CAMERA_STOP_FOLLOW",                    // CameraStopFollow
    "CAMERA_MOTION_BLUR",                    // CameraMotionBlur
    "CAMERA_MOTION_BLUR_JUMP",               // CameraMotionBlurJump
    "CAMERA_MOTION_BLUR_FOLLOW",             // CameraMotionBlurFollow
    "CAMERA_MOTION_BLUR_END_FOLLOW",         // CameraMotionBlurEndFollow
    "FREEZE_TIME",                           // FreezeTime
    "UNFREEZE_TIME",                         // UnfreezeTime
    "SHOW_MILITARY_CAPTION",                 // ShowMilitaryCaption
    "CAMERA_SET_AUDIBLE_DISTANCE",           // CameraSetAudibleDistance
    "SET_STOPPING_DISTANCE",                 // SetStoppingDistance
    "NAMED_SET_STOPPING_DISTANCE",           // NamedSetStoppingDistance
    "SET_FPS_LIMIT",                         // SetFpsLimit
    "MUSIC_SET_VOLUME",                      // MusicSetVolume
    "MAP_SHROUD_AT_WAYPOINT",                // MapShroudAtWaypoint
    "MAP_SHROUD_ALL",                        // MapShroudAll
    "SET_RANDOM_TIMER",                      // SetRandomTimer
    "SET_RANDOM_MSEC_TIMER",                 // SetRandomMsecTimer
    "STOP_TIMER",                            // StopTimer
    "RESTART_TIMER",                         // RestartTimer
    "ADD_TO_MSEC_TIMER",                     // AddToMsecTimer
    "SUB_FROM_MSEC_TIMER",                   // SubFromMsecTimer
    "TEAM_TRANSFER_TO_PLAYER",               // TeamTransferToPlayer
    "PLAYER_SET_MONEY",                      // PlayerSetMoney
    "PLAYER_GIVE_MONEY",                     // PlayerGiveMoney
    "DISABLE_SPECIAL_POWER_DISPLAY",         // DisableSpecialPowerDisplay
    "ENABLE_SPECIAL_POWER_DISPLAY",          // EnableSpecialPowerDisplay
    "NAMED_HIDE_SPECIAL_POWER_DISPLAY",      // NamedHideSpecialPowerDisplay
    "NAMED_SHOW_SPECIAL_POWER_DISPLAY",      // NamedShowSpecialPowerDisplay
    "DISPLAY_COUNTDOWN_TIMER",               // DisplayCountdownTimer
    "HIDE_COUNTDOWN_TIMER",                  // HideCountdownTimer
    "ENABLE_COUNTDOWN_TIMER_DISPLAY",        // EnableCountdownTimerDisplay
    "DISABLE_COUNTDOWN_TIMER_DISPLAY",       // DisableCountdownTimerDisplay
    "NAMED_STOP_SPECIAL_POWER_COUNTDOWN",    // NamedStopSpecialPowerCountdown
    "NAMED_START_SPECIAL_POWER_COUNTDOWN",   // NamedStartSpecialPowerCountdown
    "NAMED_SET_SPECIAL_POWER_COUNTDOWN",     // NamedSetSpecialPowerCountdown
    "NAMED_ADD_SPECIAL_POWER_COUNTDOWN",     // NamedAddSpecialPowerCountdown
    "NAMED_FIRE_SPECIAL_POWER_AT_WAYPOINT",  // NamedFireSpecialPowerAtWaypoint
    "NAMED_FIRE_SPECIAL_POWER_AT_NAMED",     // NamedFireSpecialPowerAtNamed
    "REFRESH_RADAR",                         // RefreshRadar
    "CAMERA_TETHER_NAMED",                   // CameraTetherNamed
    "CAMERA_STOP_TETHER_NAMED",              // CameraStopTetherNamed
    "CAMERA_SET_DEFAULT",                    // CameraSetDefault
    "NAMED_STOP",                            // NamedStop
    "TEAM_STOP",                             // TeamStop
    "TEAM_STOP_AND_DISBAND",                 // TeamStopAndDisband
    "RECRUIT_TEAM",                          // RecruitTeam
    "TEAM_SET_OVERRIDE_RELATION_TO_TEAM",    // TeamSetOverrideRelationToTeam
    "TEAM_REMOVE_OVERRIDE_RELATION_TO_TEAM", // TeamRemoveOverrideRelationToTeam
    "TEAM_REMOVE_ALL_OVERRIDE_RELATIONS",    // TeamRemoveAllOverrideRelations
    "CAMERA_LOOK_TOWARD_OBJECT",             // CameraLookTowardObject
    "NAMED_FIRE_WEAPON_FOLLOWING_WAYPOINT_PATH", // NamedFireWeaponFollowingWaypointPath
    "TEAM_SET_OVERRIDE_RELATION_TO_PLAYER",  // TeamSetOverrideRelationToPlayer
    "TEAM_REMOVE_OVERRIDE_RELATION_TO_PLAYER", // TeamRemoveOverrideRelationToPlayer
    "PLAYER_SET_OVERRIDE_RELATION_TO_TEAM",  // PlayerSetOverrideRelationToTeam
    "PLAYER_REMOVE_OVERRIDE_RELATION_TO_TEAM", // PlayerRemoveOverrideRelationToTeam
    "UNIT_EXECUTE_SEQUENTIAL_SCRIPT",        // UnitExecuteSequentialScript
    "UNIT_EXECUTE_SEQUENTIAL_SCRIPT_LOOPING", // UnitExecuteSequentialScriptLooping
    "UNIT_STOP_SEQUENTIAL_SCRIPT",           // UnitStopSequentialScript
    "TEAM_EXECUTE_SEQUENTIAL_SCRIPT",        // TeamExecuteSequentialScript
    "TEAM_EXECUTE_SEQUENTIAL_SCRIPT_LOOPING", // TeamExecuteSequentialScriptLooping
    "TEAM_STOP_SEQUENTIAL_SCRIPT",           // TeamStopSequentialScript
    "UNIT_GUARD_FOR_FRAMECOUNT",             // UnitGuardForFramecount
    "UNIT_IDLE_FOR_FRAMECOUNT",              // UnitIdleForFramecount
    "TEAM_GUARD_FOR_FRAMECOUNT",             // TeamGuardForFramecount
    "TEAM_IDLE_FOR_FRAMECOUNT",              // TeamIdleForFramecount
    "WATER_CHANGE_HEIGHT",                   // WaterChangeHeight
    "NAMED_USE_COMMANDBUTTON_ABILITY_ON_NAMED", // NamedUseCommandbuttonAbilityOnNamed
    "NAMED_USE_COMMANDBUTTON_ABILITY_AT_WAYPOINT", // NamedUseCommandbuttonAbilityAtWaypoint
    "WATER_CHANGE_HEIGHT_OVER_TIME",         // WaterChangeHeightOverTime
    "MAP_SWITCH_BORDER",                     // MapSwitchBorder
    "TEAM_GUARD_POSITION",                   // TeamGuardPosition
    "TEAM_GUARD_OBJECT",                     // TeamGuardObject
    "TEAM_GUARD_AREA",                       // TeamGuardArea
    "OBJECT_FORCE_SELECT",                   // ObjectForceSelect
    "CAMERA_LOOK_TOWARD_WAYPOINT",           // CameraLookTowardWaypoint
    "UNIT_DESTROY_ALL_CONTAINED",            // UnitDestroyAllContained
    "RADAR_FORCE_ENABLE",                    // RadarForceEnable
    "RADAR_REVERT_TO_NORMAL",                // RadarRevertToNormal
    "SCREEN_SHAKE",                          // ScreenShake
    "TECHTREE_MODIFY_BUILDABILITY_OBJECT",   // TechtreeModifyBuildabilityObject
    "WAREHOUSE_SET_VALUE",                   // WarehouseSetValue
    "OBJECT_CREATE_RADAR_EVENT",             // ObjectCreateRadarEvent
    "TEAM_CREATE_RADAR_EVENT",               // TeamCreateRadarEvent
    "DISPLAY_CINEMATIC_TEXT",                // DisplayCinematicText
    "DEBUG_CRASH_BOX",                       // DebugCrashBox
    "SOUND_DISABLE_TYPE",                    // SoundDisableType
    "SOUND_ENABLE_TYPE",                     // SoundEnableType
    "SOUND_ENABLE_ALL",                      // SoundEnableAll
    "AUDIO_OVERRIDE_VOLUME_TYPE",            // AudioOverrideVolumeType
    "AUDIO_RESTORE_VOLUME_TYPE",             // AudioRestoreVolumeType
    "AUDIO_RESTORE_VOLUME_ALL_TYPE",         // AudioRestoreVolumeAllType
    "INGAME_POPUP_MESSAGE",                  // IngamePopupMessage
    "SET_CAVE_INDEX",                        // SetCaveIndex
    "NAMED_SET_HELD",                        // NamedSetHeld
    "NAMED_SET_TOPPLE_DIRECTION",            // NamedSetToppleDirection
    "UNIT_MOVE_TOWARDS_NEAREST_OBJECT_TYPE", // UnitMoveTowardsNearestObjectType
    "TEAM_MOVE_TOWARDS_NEAREST_OBJECT_TYPE", // TeamMoveTowardsNearestObjectType
    "MAP_REVEAL_ALL_PERM",                   // MapRevealAllPerm
    "MAP_REVEAL_ALL_UNDO_PERM",              // MapRevealAllUndoPerm
    "NAMED_SET_REPULSOR",                    // NamedSetRepulsor
    "TEAM_SET_REPULSOR",                     // TeamSetRepulsor
    "TEAM_WANDER_IN_PLACE",                  // TeamWanderInPlace
    "TEAM_INCREASE_PRIORITY",                // TeamIncreasePriority
    "TEAM_DECREASE_PRIORITY",                // TeamDecreasePriority
    "DISPLAY_COUNTER",                       // DisplayCounter
    "HIDE_COUNTER",                          // HideCounter
    "TEAM_USE_COMMANDBUTTON_ABILITY_ON_NAMED", // TeamUseCommandbuttonAbilityOnNamed
    "TEAM_USE_COMMANDBUTTON_ABILITY_AT_WAYPOINT", // TeamUseCommandbuttonAbilityAtWaypoint
    "NAMED_USE_COMMANDBUTTON_ABILITY",       // NamedUseCommandbuttonAbility
    "TEAM_USE_COMMANDBUTTON_ABILITY",        // TeamUseCommandbuttonAbility
    "NAMED_FLASH_WHITE",                     // NamedFlashWhite
    "TEAM_FLASH_WHITE",                      // TeamFlashWhite
    "SKIRMISH_BUILD_BUILDING",               // SkirmishBuildBuilding
    "SKIRMISH_FOLLOW_APPROACH_PATH",         // SkirmishFollowApproachPath
    "IDLE_ALL_UNITS",                        // IdleAllUnits
    "RESUME_SUPPLY_TRUCKING",                // ResumeSupplyTrucking
    "NAMED_CUSTOM_COLOR",                    // NamedCustomColor
    "SKIRMISH_MOVE_TO_APPROACH_PATH",        // SkirmishMoveToApproachPath
    "SKIRMISH_BUILD_BASE_DEFENSE_FRONT",     // SkirmishBuildBaseDefenseFront
    "SKIRMISH_FIRE_SPECIAL_POWER_AT_MOST_COST", // SkirmishFireSpecialPowerAtMostCost
    "",                                      // NamedReceiveUpgrade
    "PLAYER_REPAIR_NAMED_STRUCTURE",         // PlayerRepairNamedStructure
    "SKIRMISH_BUILD_BASE_DEFENSE_FLANK",     // SkirmishBuildBaseDefenseFlank
    "SKIRMISH_BUILD_STRUCTURE_FRONT",        // SkirmishBuildStructureFront
    "SKIRMISH_BUILD_STRUCTURE_FLANK",        // SkirmishBuildStructureFlank
    "SKIRMISH_ATTACK_NEAREST_GROUP_WITH_VALUE", // SkirmishAttackNearestGroupWithValue
    "SKIRMISH_PERFORM_COMMANDBUTTON_ON_MOST_VALUABLE_OBJECT", // SkirmishPerformCommandbuttonOnMostValuableObject
    "SKIRMISH_WAIT_FOR_COMMANDBUTTON_AVAILABLE_ALL", // SkirmishWaitForCommandbuttonAvailableAll
    "SKIRMISH_WAIT_FOR_COMMANDBUTTON_AVAILABLE_PARTIAL", // SkirmishWaitForCommandbuttonAvailablePartial
    "TEAM_SPIN_FOR_FRAMECOUNT",                          // TeamSpinForFramecount
    "TEAM_ALL_USE_COMMANDBUTTON_ON_NAMED",               // TeamAllUseCommandbuttonOnNamed
    "TEAM_ALL_USE_COMMANDBUTTON_ON_NEAREST_ENEMY_UNIT", // TeamAllUseCommandbuttonOnNearestEnemyUnit
    "TEAM_ALL_USE_COMMANDBUTTON_ON_NEAREST_GARRISONED_BUILDING", // TeamAllUseCommandbuttonOnNearestGarrisonedBuilding
    "TEAM_ALL_USE_COMMANDBUTTON_ON_NEAREST_KINDOF", // TeamAllUseCommandbuttonOnNearestKindof
    "TEAM_ALL_USE_COMMANDBUTTON_ON_NEAREST_ENEMY_BUILDING", // TeamAllUseCommandbuttonOnNearestEnemyBuilding
    "TEAM_ALL_USE_COMMANDBUTTON_ON_NEAREST_ENEMY_BUILDING_CLASS", // TeamAllUseCommandbuttonOnNearestEnemyBuildingClass
    "TEAM_ALL_USE_COMMANDBUTTON_ON_NEAREST_OBJECTTYPE", // TeamAllUseCommandbuttonOnNearestObjecttype
    "TEAM_PARTIAL_USE_COMMANDBUTTON",                   // TeamPartialUseCommandbutton
    "TEAM_CAPTURE_NEAREST_UNOWNED_FACTION_UNIT",        // TeamCaptureNearestUnownedFactionUnit
    "PLAYER_CREATE_TEAM_FROM_CAPTURED_UNITS",           // PlayerCreateTeamFromCapturedUnits
    "PLAYER_ADD_SKILLPOINTS",                           // PlayerAddSkillpoints
    "PLAYER_ADD_RANKLEVEL",                             // PlayerAddRanklevel
    "PLAYER_SET_RANKLEVEL",                             // PlayerSetRanklevel
    "PLAYER_SET_RANKLEVELLIMIT",                        // PlayerSetRanklevellimit
    "PLAYER_GRANT_SCIENCE",                             // PlayerGrantScience
    "PLAYER_PURCHASE_SCIENCE",                          // PlayerPurchaseScience
    "TEAM_HUNT_WITH_COMMAND_BUTTON",                    // TeamHuntWithCommandButton
    "TEAM_WAIT_FOR_NOT_CONTAINED_ALL",                  // TeamWaitForNotContainedAll
    "TEAM_WAIT_FOR_NOT_CONTAINED_PARTIAL",              // TeamWaitForNotContainedPartial
    "TEAM_FOLLOW_WAYPOINTS_EXACT",                      // TeamFollowWaypointsExact
    "NAMED_FOLLOW_WAYPOINTS_EXACT",                     // NamedFollowWaypointsExact
    "TEAM_SET_EMOTICON",                                // TeamSetEmoticon
    "NAMED_SET_EMOTICON",                               // NamedSetEmoticon
    "AI_PLAYER_BUILD_SUPPLY_CENTER",                    // AiPlayerBuildSupplyCenter
    "AI_PLAYER_BUILD_UPGRADE",                          // AiPlayerBuildUpgrade
    "OBJECTLIST_ADDOBJECTTYPE",                         // ObjectlistAddobjecttype
    "OBJECTLIST_REMOVEOBJECTTYPE",                      // ObjectlistRemoveobjecttype
    "MAP_REVEAL_PERMANENTLY_AT_WAYPOINT",               // MapRevealPermanentlyAtWaypoint
    "MAP_UNDO_REVEAL_PERMANENTLY_AT_WAYPOINT",          // MapUndoRevealPermanentlyAtWaypoint
    "NAMED_SET_STEALTH_ENABLED",                        // NamedSetStealthEnabled
    "TEAM_SET_STEALTH_ENABLED",                         // TeamSetStealthEnabled
    "EVA_SET_ENABLED_DISABLED",                         // EvaSetEnabledDisabled
    "OPTIONS_SET_OCCLUSION_MODE",                       // OptionsSetOcclusionMode
    "LOCALDEFEAT",                                      // Localdefeat
    "OPTIONS_SET_DRAWICON_UI_MODE",                     // OptionsSetDrawiconUiMode
    "OPTIONS_SET_PARTICLE_CAP_MODE",                    // OptionsSetParticleCapMode
    "PLAYER_SCIENCE_AVAILABILITY",                      // PlayerScienceAvailability
    "UNIT_AFFECT_OBJECT_PANEL_FLAGS",                   // UnitAffectObjectPanelFlags
    "TEAM_AFFECT_OBJECT_PANEL_FLAGS",                   // TeamAffectObjectPanelFlags
    "PLAYER_SELECT_SKILLSET",                           // PlayerSelectSkillset
    "SCRIPTING_OVERRIDE_HULK_LIFETIME",                 // ScriptingOverrideHulkLifetime
    "NAMED_FACE_NAMED",                                 // NamedFaceNamed
    "NAMED_FACE_WAYPOINT",                              // NamedFaceWaypoint
    "TEAM_FACE_NAMED",                                  // TeamFaceNamed
    "TEAM_FACE_WAYPOINT",                               // TeamFaceWaypoint
    "COMMANDBAR_REMOVE_BUTTON_OBJECTTYPE",              // CommandbarRemoveButtonObjecttype
    "COMMANDBAR_ADD_BUTTON_OBJECTTYPE_SLOT",            // CommandbarAddButtonObjecttypeSlot
    "UNIT_SPAWN_NAMED_LOCATION_ORIENTATION",            // UnitSpawnNamedLocationOrientation
    "PLAYER_AFFECT_RECEIVING_EXPERIENCE",               // PlayerAffectReceivingExperience
    "PLAYER_EXCLUDE_FROM_SCORE_SCREEN",                 // PlayerExcludeFromScoreScreen
    "TEAM_GUARD_SUPPLY_CENTER",                         // TeamGuardSupplyCenter
    "ENABLE_SCORING",                                   // EnableScoring
    "DISABLE_SCORING",                                  // DisableScoring
    "SOUND_SET_VOLUME",                                 // SoundSetVolume
    "SPEECH_SET_VOLUME",                                // SpeechSetVolume
    "DISABLE_BORDER_SHROUD",                            // DisableBorderShroud
    "ENABLE_BORDER_SHROUD",                             // EnableBorderShroud
    "OBJECT_ALLOW_BONUSES",                             // ObjectAllowBonuses
    "SOUND_REMOVE_ALL_DISABLED",                        // SoundRemoveAllDisabled
    "SOUND_REMOVE_TYPE",                                // SoundRemoveType
    "TEAM_GUARD_IN_TUNNEL_NETWORK",                     // TeamGuardInTunnelNetwork
    "QUICKVICTORY",                                     // Quickvictory
    "SET_INFANTRY_LIGHTING_OVERRIDE",                   // SetInfantryLightingOverride
    "RESET_INFANTRY_LIGHTING_OVERRIDE",                 // ResetInfantryLightingOverride
    "TEAM_DELETE_LIVING",                               // TeamDeleteLiving
    "RESIZE_VIEW_GUARDBAND",                            // ResizeViewGuardband
    "DELETE_ALL_UNMANNED",                              // DeleteAllUnmanned
    "CHOOSE_VICTIM_ALWAYS_USES_NORMAL",                 // ChooseVictimAlwaysUsesNormal
    "CAMERA_ENABLE_SLAVE_MODE",                         // CameraEnableSlaveMode
    "CAMERA_DISABLE_SLAVE_MODE",                        // CameraDisableSlaveMode
    "CAMERA_ADD_SHAKER_AT",                             // CameraAddShakerAt
    "SET_TRAIN_HELD",                                   // SetTrainHeld
    "NAMED_SET_EVAC_LEFT_OR_RIGHT",                     // NamedSetEvacLeftOrRight
    "ENABLE_OBJECT_SOUND",                              // EnableObjectSound
    "DISABLE_OBJECT_SOUND",                             // DisableObjectSound
    "NAMED_USE_COMMANDBUTTON_ABILITY_USING_WAYPOINT_PATH", // NamedUseCommandbuttonAbilityUsingWaypointPath
    "NAMED_SET_UNMANNED_STATUS",                           // NamedSetUnmannedStatus
    "TEAM_SET_UNMANNED_STATUS",                            // TeamSetUnmannedStatus
    "NAMED_SET_BOOBYTRAPPED",                              // NamedSetBoobytrapped
    "TEAM_SET_BOOBYTRAPPED",                               // TeamSetBoobytrapped
    "SHOW_WEATHER",                                        // ShowWeather
    "AI_PLAYER_BUILD_TYPE_NEAREST_TEAM",                   // AiPlayerBuildTypeNearestTeam
];
