//! CPU tessellation port for C++ `W3DDevice/GameClient/W3DTerrainBackground.cpp`.

use game_engine::map_object::{MAP_HEIGHT_SCALE, MAP_XY_FACTOR};

/// C++ default flat texture resolution per terrain grid.
pub const PIXELS_PER_GRID: i32 = 8;
/// C++ `TEX1X` terrain-background texture multiplier.
pub const TEX_1X: i32 = 1;
/// C++ `TEX2X` terrain-background texture multiplier.
pub const TEX_2X: i32 = 2;
/// C++ `TEX4X` terrain-background texture multiplier.
pub const TEX_4X: i32 = 4;

const MIP_DISTANCE: f32 = 310.0;
const MIP_SLOP: f32 = 40.0;

/// CPU mirror of C++ `m_cullStatus`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum TerrainBackgroundCullStatus {
    /// `CULL_STATUS_UNKNOWN`.
    Unknown = 0,
    /// `CULL_STATUS_VISIBLE`.
    Visible = 1,
    /// `CULL_STATUS_INVISIBLE`.
    Invisible = 2,
}

/// Integer 2D point.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct ICoord2D {
    /// X coordinate.
    pub x: i32,
    /// Y coordinate.
    pub y: i32,
}

/// Integer 2D region.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct IRegion2D {
    /// Low corner.
    pub lo: ICoord2D,
    /// High corner.
    pub hi: ICoord2D,
}

impl IRegion2D {
    /// Construct an inclusive region.
    pub const fn new(lo_x: i32, lo_y: i32, hi_x: i32, hi_y: i32) -> Self {
        Self {
            lo: ICoord2D { x: lo_x, y: lo_y },
            hi: ICoord2D { x: hi_x, y: hi_y },
        }
    }
}

/// Height-map access used by terrain background tessellation.
pub trait TerrainBackgroundHeightMap {
    /// X sample extent.
    fn x_extent(&self) -> i32;
    /// Y sample extent.
    fn y_extent(&self) -> i32;
    /// Raw terrain height sample.
    fn height(&self, x: i32, y: i32) -> i32;
    /// Static terrain diffuse.
    fn static_diffuse(&self, x: i32, y: i32) -> u32;
    /// Inline map border in height samples.
    fn border_size_inline(&self) -> i32 {
        0
    }
}

/// C++ `VertexFormatXYZDUV2` subset emitted by the background patch.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct TerrainBackgroundVertex {
    /// World X.
    pub x: f32,
    /// World Y.
    pub y: f32,
    /// World Z.
    pub z: f32,
    /// Static diffuse color.
    pub diffuse: u32,
    /// Patch U coordinate.
    pub u1: f32,
    /// Patch V coordinate.
    pub v1: f32,
}

/// Axis-aligned bounds for generated terrain vertices.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct TerrainBackgroundBounds {
    /// Minimum point.
    pub min: [f32; 3],
    /// Maximum point.
    pub max: [f32; 3],
}

impl TerrainBackgroundBounds {
    fn empty() -> Self {
        Self {
            min: [f32::MAX; 3],
            max: [f32::MIN; 3],
        }
    }

    fn is_empty(&self) -> bool {
        self.min[0] == f32::MAX
    }

    fn add_point(&mut self, x: f32, y: f32, z: f32) {
        self.min[0] = self.min[0].min(x);
        self.min[1] = self.min[1].min(y);
        self.min[2] = self.min[2].min(z);
        self.max[0] = self.max[0].max(x);
        self.max[1] = self.max[1].max(y);
        self.max[2] = self.max[2].max(z);
    }

    fn center_and_extent(&self) -> Option<([f32; 3], [f32; 3])> {
        if self.is_empty() {
            return None;
        }
        Some((
            [
                (self.min[0] + self.max[0]) * 0.5,
                (self.min[1] + self.max[1]) * 0.5,
                (self.min[2] + self.max[2]) * 0.5,
            ],
            [
                (self.max[0] - self.min[0]) * 0.5,
                (self.max[1] - self.min[1]) * 0.5,
                (self.max[2] - self.min[2]) * 0.5,
            ],
        ))
    }
}

impl Default for TerrainBackgroundBounds {
    fn default() -> Self {
        Self::empty()
    }
}

/// CPU-side vertex/index output for a background terrain patch.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct TerrainBackgroundBuffers {
    /// Required vertices only, in C++ scan order.
    pub vertices: Vec<TerrainBackgroundVertex>,
    /// Triangle list indices generated by `fillVBRecursive`.
    pub indices: Vec<u16>,
    /// Bounds over the whole patch, not just required vertices.
    pub bounds: TerrainBackgroundBounds,
}

/// Low-resolution backup terrain patch.
#[derive(Debug, Clone)]
pub struct W3DTerrainBackground {
    x_origin: i32,
    y_origin: i32,
    width: i32,
    initialized: bool,
    flip_state: Vec<bool>,
    cached_buffers: TerrainBackgroundBuffers,
    terrain_texture_requested: bool,
    terrain_texture_2x_requested: bool,
    terrain_texture_4x_requested: bool,
    terrain_texture_lod: i32,
    cull_status: TerrainBackgroundCullStatus,
    tex_multiplier: i32,
}

impl W3DTerrainBackground {
    /// Construct an unallocated patch, matching C++ constructor state.
    pub fn new() -> Self {
        Self {
            x_origin: 0,
            y_origin: 0,
            width: 0,
            initialized: false,
            flip_state: Vec::new(),
            cached_buffers: TerrainBackgroundBuffers::default(),
            terrain_texture_requested: false,
            terrain_texture_2x_requested: false,
            terrain_texture_4x_requested: false,
            terrain_texture_lod: 0,
            cull_status: TerrainBackgroundCullStatus::Unknown,
            tex_multiplier: TEX_1X,
        }
    }

    /// C++ `allocateTerrainBuffers`.
    pub fn allocate_terrain_buffers<M: TerrainBackgroundHeightMap>(
        &mut self,
        _map: &M,
        x_origin: i32,
        y_origin: i32,
        width: i32,
    ) {
        self.free_terrain_buffers();
        self.x_origin = x_origin;
        self.y_origin = y_origin;
        self.width = width.max(0);
        self.initialized = true;
        self.flip_state = vec![false; self.patch_sample_count()];
    }

    /// C++ `freeTerrainBuffers`.
    pub fn free_terrain_buffers(&mut self) {
        self.cached_buffers = TerrainBackgroundBuffers::default();
        self.flip_state.clear();
        self.initialized = false;
        self.terrain_texture_requested = false;
        self.terrain_texture_2x_requested = false;
        self.terrain_texture_4x_requested = false;
        self.terrain_texture_lod = 0;
        self.cull_status = TerrainBackgroundCullStatus::Unknown;
        self.tex_multiplier = TEX_1X;
    }

    /// C++ `setFlip`.
    pub fn set_flip<M: TerrainBackgroundHeightMap>(&mut self, map: &M) {
        if !self.initialized {
            return;
        }
        self.flip_state.fill(false);
        self.set_flip_recursive(map, 0, 0, self.width);
    }

    /// C++ `doPartialUpdate`, which immediately delegates to `doTesselatedUpdate`.
    pub fn do_partial_update<M: TerrainBackgroundHeightMap>(
        &mut self,
        partial_range: IRegion2D,
        map: &M,
        do_textures: bool,
    ) -> &TerrainBackgroundBuffers {
        self.do_tessellated_update(partial_range, map, do_textures)
    }

    /// C++ `doTesselatedUpdate`.
    pub fn do_tessellated_update<M: TerrainBackgroundHeightMap>(
        &mut self,
        partial_range: IRegion2D,
        map: &M,
        do_textures: bool,
    ) -> &TerrainBackgroundBuffers {
        if !self.initialized {
            return &self.cached_buffers;
        }

        let min_x = self.x_origin;
        let min_y = self.y_origin;
        let max_x = self.x_origin + self.width;
        let max_y = self.y_origin + self.width;

        if partial_range.lo.x > max_x
            || partial_range.lo.y > max_y
            || partial_range.hi.x < min_x
            || partial_range.hi.y < min_y
        {
            return &self.cached_buffers;
        }

        self.set_flip(map);

        let mut ndx = vec![0u16; self.patch_sample_count()];
        let mut vertices = Vec::new();
        let limit_x = map.x_extent() - 1;
        let limit_y = map.y_extent() - 1;
        for j in min_y..=max_y {
            for i in min_x..=max_x {
                let ndx_ndx = self.local_index(i - min_x, j - min_y);
                if self.get_flip_local(i - min_x, j - min_y) {
                    let k = i.min(limit_x);
                    let l = j.min(limit_y);
                    ndx[ndx_ndx] = vertices.len() as u16;
                    vertices.push(self.vertex_for(map, i, j, k, l));
                }
            }
        }

        let mut indices = Vec::new();
        self.fill_vb_recursive(map, 0, 0, self.width, &ndx, &mut indices);

        let mut bounds = TerrainBackgroundBounds::empty();
        for j in min_y..=max_y {
            for i in min_x..=max_x {
                let k = i.min(limit_x);
                let l = j.min(limit_y);
                let x = i as f32 * MAP_XY_FACTOR - map.border_size_inline() as f32 * MAP_XY_FACTOR;
                let y = j as f32 * MAP_XY_FACTOR - map.border_size_inline() as f32 * MAP_XY_FACTOR;
                let z = map.height(k, l) as f32 * MAP_HEIGHT_SCALE;
                bounds.add_point(x, y, z);
            }
        }

        self.cached_buffers = TerrainBackgroundBuffers {
            vertices,
            indices,
            bounds,
        };
        if do_textures || !self.terrain_texture_requested {
            self.terrain_texture_requested = true;
            self.terrain_texture_2x_requested = false;
            self.terrain_texture_4x_requested = false;
            self.terrain_texture_lod = 0;
        }
        &self.cached_buffers
    }

    /// C++ `updateCenter`, using a caller-provided cull result in place of `CameraClass::Cull_Box`.
    pub fn update_center(&mut self, camera_pos: [f32; 3], culled: bool) {
        self.cull_status = if culled {
            TerrainBackgroundCullStatus::Invisible
        } else {
            TerrainBackgroundCullStatus::Visible
        };

        if self.cull_status == TerrainBackgroundCullStatus::Invisible {
            self.terrain_texture_2x_requested = false;
            self.terrain_texture_4x_requested = false;
            self.tex_multiplier = TEX_1X;
            return;
        }

        let Some((center, extent)) = self.cached_buffers.bounds.center_and_extent() else {
            self.tex_multiplier = TEX_1X;
            return;
        };

        let mip_4x_distance_sqr = square(MIP_DISTANCE + MIP_SLOP);
        let mip_2x_distance_sqr = square(2.0 * MIP_DISTANCE + MIP_SLOP);
        let mip_lod_distance_sqr = square(4.0 * MIP_DISTANCE + MIP_SLOP);
        let mut min_dist_sqr = 2.0 * mip_2x_distance_sqr;

        for i in -1..=1 {
            for j in -1..=1 {
                for k in -1..=1 {
                    let corner = [
                        center[0] + extent[0] * i as f32,
                        center[1] + extent[1] * j as f32,
                        center[2] + extent[2] * k as f32,
                    ];
                    let dist_sqr = square(camera_pos[0] - corner[0])
                        + square(camera_pos[1] - corner[1])
                        + square(camera_pos[2] - corner[2]);
                    if dist_sqr < min_dist_sqr {
                        min_dist_sqr = dist_sqr;
                    }
                }
            }
        }

        self.tex_multiplier = TEX_1X;
        if min_dist_sqr < mip_4x_distance_sqr {
            self.tex_multiplier = TEX_4X;
        } else if min_dist_sqr < mip_2x_distance_sqr {
            self.tex_multiplier = TEX_2X;
        } else {
            self.terrain_texture_4x_requested = false;
            self.terrain_texture_2x_requested = false;
            self.terrain_texture_lod = if min_dist_sqr > mip_lod_distance_sqr {
                1
            } else {
                0
            };
        }
    }

    /// C++ `updateTexture`, mirrored as CPU texture-request state.
    pub fn update_texture(&mut self) {
        if self.cull_status == TerrainBackgroundCullStatus::Invisible {
            self.terrain_texture_2x_requested = false;
            self.terrain_texture_4x_requested = false;
            return;
        }

        match self.tex_multiplier {
            TEX_4X => {
                self.terrain_texture_2x_requested = false;
                self.terrain_texture_4x_requested = true;
            }
            TEX_2X => {
                self.terrain_texture_4x_requested = false;
                self.terrain_texture_2x_requested = true;
            }
            _ => {
                self.terrain_texture_4x_requested = false;
                self.terrain_texture_2x_requested = false;
            }
        }
    }

    /// Access cached buffers.
    pub fn buffers(&self) -> &TerrainBackgroundBuffers {
        &self.cached_buffers
    }

    /// Query C++ flip state for a global sample.
    pub fn get_flip_state(&self, x: i32, y: i32) -> bool {
        let lx = x - self.x_origin;
        let ly = y - self.y_origin;
        self.get_flip_local(lx, ly)
    }

    /// Width passed to allocation.
    pub fn width(&self) -> i32 {
        self.width
    }

    /// Texture multiplier requested by camera update logic.
    pub fn tex_multiplier(&self) -> i32 {
        self.tex_multiplier
    }

    /// C++ `isCulled`.
    pub fn is_culled(&self) -> bool {
        self.cull_status == TerrainBackgroundCullStatus::Invisible
    }

    /// Current CPU cull state.
    pub fn cull_status(&self) -> TerrainBackgroundCullStatus {
        self.cull_status
    }

    /// Whether the base flat texture has been requested.
    pub fn terrain_texture_requested(&self) -> bool {
        self.terrain_texture_requested
    }

    /// Whether C++ would currently hold/request the 2x flat texture.
    pub fn terrain_texture_2x_requested(&self) -> bool {
        self.terrain_texture_2x_requested
    }

    /// Whether C++ would currently hold/request the 4x flat texture.
    pub fn terrain_texture_4x_requested(&self) -> bool {
        self.terrain_texture_4x_requested
    }

    /// Last LOD assigned to the base terrain texture.
    pub fn terrain_texture_lod(&self) -> i32 {
        self.terrain_texture_lod
    }

    fn vertex_for<M: TerrainBackgroundHeightMap>(
        &self,
        map: &M,
        i: i32,
        j: i32,
        height_x: i32,
        height_y: i32,
    ) -> TerrainBackgroundVertex {
        TerrainBackgroundVertex {
            diffuse: map.static_diffuse(i, j),
            x: i as f32 * MAP_XY_FACTOR - map.border_size_inline() as f32 * MAP_XY_FACTOR,
            y: j as f32 * MAP_XY_FACTOR - map.border_size_inline() as f32 * MAP_XY_FACTOR,
            z: map.height(height_x, height_y) as f32 * MAP_HEIGHT_SCALE,
            u1: (i - self.x_origin) as f32 / self.width as f32,
            v1: 1.0 - (j - self.y_origin) as f32 / self.width as f32,
        }
    }

    fn set_flip_recursive<M: TerrainBackgroundHeightMap>(
        &mut self,
        map: &M,
        x_offset: i32,
        y_offset: i32,
        width: i32,
    ) {
        if width <= 0 {
            return;
        }
        let limit_x = map.x_extent() - 1;
        let limit_y = map.y_extent() - 1;
        let min_x = self.x_origin + x_offset;
        let min_y = self.y_origin + y_offset;
        let corner_height = map.height(min_x.min(limit_x), min_y.min(limit_y));
        let mut matches = true;

        'outer: for i in 0..=width {
            for j in 0..=width {
                let k = (min_x + i).min(limit_x);
                let l = (min_y + j).min(limit_y);
                if corner_height != map.height(k, l) {
                    matches = false;
                    break 'outer;
                }
            }
        }
        if width == 1 {
            matches = true;
        }

        if matches {
            self.set_flip_local(x_offset, y_offset, true);
            self.set_flip_local(x_offset + width, y_offset, true);
            self.set_flip_local(x_offset + width, y_offset + width, true);
            self.set_flip_local(x_offset, y_offset + width, true);
            return;
        }

        let half_width = width / 2;
        self.set_flip_recursive(map, x_offset, y_offset, half_width);
        self.set_flip_recursive(map, x_offset, y_offset + half_width, half_width);
        self.set_flip_recursive(map, x_offset + half_width, y_offset, half_width);
        self.set_flip_recursive(
            map,
            x_offset + half_width,
            y_offset + half_width,
            half_width,
        );
    }

    fn fill_vb_recursive<M: TerrainBackgroundHeightMap>(
        &self,
        map: &M,
        x_offset: i32,
        y_offset: i32,
        width: i32,
        ndx: &[u16],
        indices: &mut Vec<u16>,
    ) {
        if width <= 0 {
            return;
        }
        let bottom_left_ndx = ndx[self.local_index(x_offset, y_offset)];
        let top_right_ndx = ndx[self.local_index(x_offset + width, y_offset + width)];
        let limit_x = map.x_extent() - 1;
        let limit_y = map.y_extent() - 1;
        let min_x = self.x_origin + x_offset;
        let min_y = self.y_origin + y_offset;
        let corner_height = map.height(min_x, min_y);
        let mut matches = true;

        'outer: for i in 0..=width {
            for j in 0..=width {
                let k = (min_x + i).min(limit_x);
                let l = (min_y + j).min(limit_y);
                if corner_height != map.height(k, l) {
                    matches = false;
                    break 'outer;
                }
            }
        }
        if width == 1 {
            matches = true;
        }

        if matches {
            let mut left = ICoord2D {
                x: x_offset,
                y: y_offset,
            };
            let mut right = left;
            self.advance_left(&mut left, x_offset, y_offset, width);
            self.advance_right(&mut right, x_offset, y_offset, width);

            indices.push(bottom_left_ndx);
            let mut prev_ndx_right = ndx[self.local_index(right.x, right.y)];
            indices.push(prev_ndx_right);
            let mut prev_ndx_left = ndx[self.local_index(left.x, left.y)];
            indices.push(prev_ndx_left);

            let mut did_left = true;
            let mut did_right = true;
            while did_left || did_right {
                did_left = self.advance_left(&mut left, x_offset, y_offset, width);
                if did_left {
                    indices.push(prev_ndx_left);
                    indices.push(prev_ndx_right);
                    prev_ndx_left = ndx[self.local_index(left.x, left.y)];
                    indices.push(prev_ndx_left);
                }
                did_right = self.advance_right(&mut right, x_offset, y_offset, width);
                if did_right {
                    indices.push(prev_ndx_left);
                    indices.push(prev_ndx_right);
                    prev_ndx_right = ndx[self.local_index(right.x, right.y)];
                    indices.push(prev_ndx_right);
                }
            }

            indices.push(prev_ndx_left);
            indices.push(prev_ndx_right);
            indices.push(top_right_ndx);
            return;
        }

        let half_width = width / 2;
        self.fill_vb_recursive(map, x_offset, y_offset, half_width, ndx, indices);
        self.fill_vb_recursive(
            map,
            x_offset,
            y_offset + half_width,
            half_width,
            ndx,
            indices,
        );
        self.fill_vb_recursive(
            map,
            x_offset + half_width,
            y_offset,
            half_width,
            ndx,
            indices,
        );
        self.fill_vb_recursive(
            map,
            x_offset + half_width,
            y_offset + half_width,
            half_width,
            ndx,
            indices,
        );
    }

    fn advance_left(&self, left: &mut ICoord2D, x_offset: i32, y_offset: i32, width: i32) -> bool {
        while left.y < y_offset + width {
            left.y += 1;
            if self.get_flip_local(left.x, left.y) {
                return true;
            }
        }
        while left.x < x_offset + width - 1 {
            left.x += 1;
            if self.get_flip_local(left.x, left.y) {
                return true;
            }
        }
        false
    }

    fn advance_right(
        &self,
        right: &mut ICoord2D,
        x_offset: i32,
        y_offset: i32,
        width: i32,
    ) -> bool {
        while right.x < x_offset + width {
            right.x += 1;
            if self.get_flip_local(right.x, right.y) {
                return true;
            }
        }
        while right.y < y_offset + width - 1 {
            right.y += 1;
            if self.get_flip_local(right.x, right.y) {
                return true;
            }
        }
        false
    }

    fn patch_sample_count(&self) -> usize {
        let side = self.width.max(0) as usize + 1;
        side * side
    }

    fn local_index(&self, x: i32, y: i32) -> usize {
        debug_assert!(x >= 0 && y >= 0 && x <= self.width && y <= self.width);
        x as usize + (self.width as usize + 1) * y as usize
    }

    fn set_flip_local(&mut self, x: i32, y: i32, value: bool) {
        if x >= 0 && y >= 0 && x <= self.width && y <= self.width {
            let index = self.local_index(x, y);
            self.flip_state[index] = value;
        }
    }

    fn get_flip_local(&self, x: i32, y: i32) -> bool {
        if x < 0 || y < 0 || x > self.width || y > self.width {
            return false;
        }
        self.flip_state[self.local_index(x, y)]
    }
}

fn square(value: f32) -> f32 {
    value * value
}

impl Default for W3DTerrainBackground {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    struct TestMap {
        width: i32,
        height: i32,
        heights: Vec<i32>,
        border: i32,
    }

    impl TestMap {
        fn flat(width: i32, height: i32, value: i32) -> Self {
            Self {
                width,
                height,
                heights: vec![value; (width * height) as usize],
                border: 0,
            }
        }

        fn set(&mut self, x: i32, y: i32, value: i32) {
            self.heights[(x + y * self.width) as usize] = value;
        }
    }

    impl TerrainBackgroundHeightMap for TestMap {
        fn x_extent(&self) -> i32 {
            self.width
        }

        fn y_extent(&self) -> i32 {
            self.height
        }

        fn height(&self, x: i32, y: i32) -> i32 {
            self.heights[(x + y * self.width) as usize]
        }

        fn static_diffuse(&self, x: i32, y: i32) -> u32 {
            0x0010_0000 | ((x as u32) << 8) | y as u32
        }

        fn border_size_inline(&self) -> i32 {
            self.border
        }
    }

    #[test]
    fn flat_patch_sets_only_corners_and_emits_two_triangles() {
        let map = TestMap::flat(5, 5, 7);
        let mut background = W3DTerrainBackground::new();
        background.allocate_terrain_buffers(&map, 0, 0, 4);

        let buffers = background
            .do_tessellated_update(IRegion2D::new(0, 0, 4, 4), &map, true)
            .clone();

        assert_eq!(buffers.vertices.len(), 4);
        assert_eq!(buffers.indices, vec![0, 1, 2, 2, 1, 3]);
        assert!(background.get_flip_state(0, 0));
        assert!(background.get_flip_state(4, 0));
        assert!(background.get_flip_state(4, 4));
        assert!(background.get_flip_state(0, 4));
        assert!(!background.get_flip_state(2, 2));
    }

    #[test]
    fn nonflat_patch_recurses_to_required_subpatch_corners() {
        let mut map = TestMap::flat(5, 5, 7);
        map.set(2, 2, 9);
        let mut background = W3DTerrainBackground::new();
        background.allocate_terrain_buffers(&map, 0, 0, 4);

        let buffers = background
            .do_tessellated_update(IRegion2D::new(0, 0, 4, 4), &map, false)
            .clone();

        assert_eq!(buffers.vertices.len(), 25);
        assert_eq!(buffers.indices.len(), 96);
        assert!(background.get_flip_state(2, 2));
        assert_eq!(buffers.indices.len() % 3, 0);
    }

    #[test]
    fn vertices_match_cpp_world_position_uv_and_diffuse() {
        let mut map = TestMap::flat(5, 5, 10);
        map.border = 1;
        let mut background = W3DTerrainBackground::new();
        background.allocate_terrain_buffers(&map, 1, 1, 2);

        let buffers = background
            .do_tessellated_update(IRegion2D::new(1, 1, 3, 3), &map, true)
            .clone();

        let first = buffers.vertices[0];
        assert_eq!(first.diffuse, 0x0010_0101);
        assert_eq!(first.x, 0.0);
        assert_eq!(first.y, 0.0);
        assert_eq!(first.z, 10.0 * MAP_HEIGHT_SCALE);
        assert_eq!(first.u1, 0.0);
        assert_eq!(first.v1, 1.0);
    }

    #[test]
    fn disjoint_partial_update_keeps_existing_buffers() {
        let map = TestMap::flat(5, 5, 3);
        let mut background = W3DTerrainBackground::new();
        background.allocate_terrain_buffers(&map, 0, 0, 4);
        background.do_tessellated_update(IRegion2D::new(0, 0, 4, 4), &map, true);
        let previous = background.buffers().clone();

        let after = background
            .do_tessellated_update(IRegion2D::new(10, 10, 12, 12), &map, true)
            .clone();

        assert_eq!(after, previous);
    }
}
