[package]
name = "gpui-gui"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
build = "build.rs"

[dependencies]
anyhow.workspace = true
bitflags.workspace = true
game_engine = { path = "../../Common" }
gpui = {workspace = true}

[build-dependencies]
walkdir.workspace = true

[dev-dependencies]
tempfile.workspace = true
