//! Simulation data owned by one UnitAIUpdate.
//!
//! Kept separate from the parent FSM so its driver can borrow both directly.
//! Field order follows the original runtime; Xfer remains explicit on UnitAIUpdate.

use super::ai_helpers::RappelState;
use super::imports::*;
use super::types::*;

pub(super) struct UnitAiData {
    pub(super) can_path_through_units: bool,
    pub(super) randomly_offset_mood_check: bool,
    pub(super) next_mood_check_time: UnsignedInt,
    pub(super) allow_chase: bool,
    pub(super) attitude: AIAttitudeType,
    pub(super) last_command_source: CommandSourceType,
    pub(super) current_command: Option<crate::ai::AiCommandType>,
    pub(super) pending_command: Option<crate::ai::AiCommandType>,
    pub(super) surrendered_frames_left: UnsignedInt,
    pub(super) surrendered_player_index: Option<PlayerIndex>,
    pub(super) surrender_duration_frames: UnsignedInt,
    pub(super) demoralized_frames_left: UnsignedInt,
    pub(super) auto_acquire_enemies_when_idle: u32,
    pub(super) mood_attack_check_rate_frames: UnsignedInt,
    pub(super) forbid_player_commands: Bool,
    pub(super) turrets_linked: Bool,
    pub(super) turret_sync_flag: TurretType,
    pub(super) turret_primary_data: Option<TurretAIData>,
    pub(super) turret_secondary_data: Option<TurretAIData>,
    pub(super) locomotor_upgraded: Bool,
    pub(super) current_locomotor_set: LocomotorSetType,
    pub(super) locomotor_set: LocomotorSet,
    pub(super) locomotor_sets: HashMap<LocomotorSetType, Vec<AsciiString>>,
    pub(super) turret_primary_enabled: Bool,
    pub(super) turret_secondary_enabled: Bool,
    pub(super) turret_primary_natural: Bool,
    pub(super) turret_secondary_natural: Bool,
    pub(super) turret_primary_machine: Option<TurretStateMachine>,
    pub(super) turret_secondary_machine: Option<TurretStateMachine>,
    pub(super) enter_target: Option<ObjectID>,
    pub(super) desired_speed: Real,
    pub(super) prior_waypoint_id: Option<crate::waypoint::WaypointId>,
    pub(super) current_waypoint_id: Option<crate::waypoint::WaypointId>,
    pub(super) completed_waypoint_id: Option<crate::waypoint::WaypointId>,
    pub(super) current_goal_path_index: i32,
    pub(super) rappel_state: Option<RappelState>,
    pub(super) original_victim_pos: Option<Coord3D>,
    pub(super) pending_safe_path: Option<Vec<Coord3D>>,
    pub(super) guard_target_type: [GuardTargetType; 2],
    pub(super) location_to_guard: Coord3D,
    pub(super) object_to_guard: ObjectID,
    pub(super) planning_waypoint_queue: [Coord3D; AI_UPDATE_MAX_WAYPOINTS],
    pub(super) planning_waypoint_count: Int,
    pub(super) planning_waypoint_index: Int,
    pub(super) executing_waypoint_queue: Bool,
    pub(super) requested_victim_id: ObjectID,
    pub(super) requested_destination: Coord3D,
    pub(super) requested_destination2: Coord3D,
    pub(super) current_path_snapshot: Option<AiPath>,
    pub(super) pathfind_goal_cell: ICoord2D,
    pub(super) pathfind_cur_cell: ICoord2D,
    pub(super) pathfind_goal_layer: ClassicPathLayer,
    /// Astar ordinals zipped with the installed waypoints. Not xfer'd. Not `AiPath`.
    pub(super) installed_path_layers: Vec<u8>,
    pub(super) move_out_of_way_1: ObjectID,
    pub(super) move_out_of_way_2: ObjectID,
    pub(super) repulsor1: ObjectID,
    pub(super) repulsor2: ObjectID,
    pub(super) ignore_obstacle_id: ObjectID,
    pub(super) ignore_collisions_until: UnsignedInt,
    pub(super) waiting_for_path: Bool,
    pub(super) queue_for_path_frame: UnsignedInt,
    pub(super) path_timestamp: UnsignedInt,
    pub(super) ai_dead: Bool,
    pub(super) is_recruitable: Bool,
    pub(super) next_enemy_scan_time: UnsignedInt,
    pub(super) final_position: Coord3D,
    pub(super) do_final_position: Bool,
    pub(super) is_attack_path: Bool,
    pub(super) is_final_goal: Bool,
    pub(super) is_approach_path: Bool,
    pub(super) is_safe_path: Bool,
    pub(super) movement_complete: Bool,
    /// C++ `m_isMoving`. Not derived from the path.
    pub(super) cpp_is_moving: bool,
    pub(super) locomotor_goal_type: u32,
    pub(super) locomotor_goal_data: Coord3D,
    pub(super) is_blocked: Bool,
    pub(super) blocked_and_stuck: Bool,
    pub(super) retry_path: Bool,
    pub(super) blocked_frames: u32,
    pub(super) cur_max_blocked_speed: Real,
    pub(super) bump_speed_limit: Real,
}

impl Default for UnitAiData {
    fn default() -> Self {
        Self {
            can_path_through_units: false,
            randomly_offset_mood_check: false,
            next_mood_check_time: 0,
            allow_chase: false,
            attitude: AIAttitudeType::Normal,
            last_command_source: CommandSourceType::FromAi,
            current_command: None,
            pending_command: None,
            surrendered_frames_left: 0,
            surrendered_player_index: None,
            surrender_duration_frames: LOGICFRAMES_PER_SECOND * 120,
            demoralized_frames_left: 0,
            auto_acquire_enemies_when_idle: 0,
            mood_attack_check_rate_frames: LOGICFRAMES_PER_SECOND * 2,
            forbid_player_commands: false,
            turrets_linked: false,
            turret_sync_flag: TurretType::Invalid,
            turret_primary_data: None,
            turret_secondary_data: None,
            locomotor_upgraded: false,
            current_locomotor_set: LocomotorSetType::Invalid,
            locomotor_set: LocomotorSet::new(),
            locomotor_sets: HashMap::new(),
            turret_primary_enabled: true,
            turret_secondary_enabled: true,
            turret_primary_natural: true,
            turret_secondary_natural: true,
            turret_primary_machine: None,
            turret_secondary_machine: None,
            enter_target: None,
            desired_speed: FAST_AS_POSSIBLE,
            prior_waypoint_id: None,
            current_waypoint_id: None,
            completed_waypoint_id: None,
            current_goal_path_index: -1,
            rappel_state: None,
            original_victim_pos: None,
            pending_safe_path: None,
            guard_target_type: [GuardTargetType::None_; 2],
            location_to_guard: Coord3D::ZERO,
            object_to_guard: INVALID_ID,
            planning_waypoint_queue: [Coord3D::ZERO; AI_UPDATE_MAX_WAYPOINTS],
            planning_waypoint_count: 0,
            planning_waypoint_index: 0,
            executing_waypoint_queue: false,
            requested_victim_id: INVALID_ID,
            requested_destination: Coord3D::ZERO,
            requested_destination2: Coord3D::ZERO,
            current_path_snapshot: None,
            pathfind_goal_cell: ICoord2D::new(-1, -1),
            pathfind_cur_cell: ICoord2D::new(-1, -1),
            pathfind_goal_layer: ClassicPathLayer::Invalid,
            installed_path_layers: Vec::new(),
            move_out_of_way_1: INVALID_ID,
            move_out_of_way_2: INVALID_ID,
            repulsor1: INVALID_ID,
            repulsor2: INVALID_ID,
            ignore_obstacle_id: INVALID_ID,
            ignore_collisions_until: 0,
            waiting_for_path: false,
            queue_for_path_frame: 0,
            path_timestamp: 0,
            ai_dead: false,
            is_recruitable: true,
            next_enemy_scan_time: 0,
            final_position: Coord3D::ZERO,
            do_final_position: false,
            is_attack_path: false,
            is_final_goal: false,
            is_approach_path: false,
            is_safe_path: false,
            movement_complete: false,
            cpp_is_moving: false,
            locomotor_goal_type: 0,
            locomotor_goal_data: Coord3D::ZERO,
            is_blocked: false,
            blocked_and_stuck: false,
            retry_path: false,
            blocked_frames: 0,
            cur_max_blocked_speed: 0.0,
            bump_speed_limit: FAST_AS_POSSIBLE,
        }
    }
}
