//! Simulation data owned by one UnitAIUpdate.
//!
//! Kept separate from the parent FSM so its driver can borrow both directly.
//! Field order follows the original runtime; Xfer remains explicit on UnitAIUpdate.

use super::ai_helpers::RappelState;
use super::imports::*;
use super::types::*;

pub(super) struct UnitAiData {
    pub(super) can_path_through_units: bool,
    pub(super) randomly_offset_mood_check: bool,
    pub(super) next_mood_check_time: UnsignedInt,
    pub(super) allow_chase: bool,
    pub(super) attitude: AIAttitudeType,
    pub(super) last_command_source: CommandSourceType,
    pub(super) current_command: Option<crate::ai::AiCommandType>,
    pub(super) pending_command: Option<crate::ai::AiCommandType>,
    pub(super) surrendered_frames_left: UnsignedInt,
    pub(super) surrendered_player_index: Option<PlayerIndex>,
    pub(super) surrender_duration_frames: UnsignedInt,
    pub(super) demoralized_frames_left: UnsignedInt,
    pub(super) auto_acquire_enemies_when_idle: u32,
    pub(super) mood_attack_check_rate_frames: UnsignedInt,
    pub(super) forbid_player_commands: Bool,
    pub(super) turrets_linked: Bool,
    pub(super) turret_sync_flag: TurretType,
    pub(super) turret_primary_data: Option<TurretAIData>,
    pub(super) turret_secondary_data: Option<TurretAIData>,
    pub(super) locomotor_upgraded: Bool,
    pub(super) current_locomotor_set: LocomotorSetType,
    pub(super) locomotor_set: LocomotorSet,
    pub(super) locomotor_sets: HashMap<LocomotorSetType, Vec<AsciiString>>,
    pub(super) turret_primary_enabled: Bool,
    pub(super) turret_secondary_enabled: Bool,
    pub(super) turret_primary_natural: Bool,
    pub(super) turret_secondary_natural: Bool,
    pub(super) turret_primary_machine: Option<TurretStateMachine>,
    pub(super) turret_secondary_machine: Option<TurretStateMachine>,
    pub(super) enter_target: Option<ObjectID>,
    pub(super) desired_speed: Real,
    pub(super) prior_waypoint_id: Option<crate::waypoint::WaypointId>,
    pub(super) current_waypoint_id: Option<crate::waypoint::WaypointId>,
    pub(super) completed_waypoint_id: Option<crate::waypoint::WaypointId>,
    pub(super) current_goal_path_index: i32,
    pub(super) rappel_state: Option<RappelState>,
    pub(super) original_victim_pos: Option<Coord3D>,
    pub(super) pending_safe_path: Option<Vec<Coord3D>>,
    pub(super) guard_target_type: [GuardTargetType; 2],
    pub(super) location_to_guard: Coord3D,
    pub(super) object_to_guard: ObjectID,
    pub(super) planning_waypoint_queue: [Coord3D; AI_UPDATE_MAX_WAYPOINTS],
    pub(super) planning_waypoint_count: Int,
    pub(super) planning_waypoint_index: Int,
    pub(super) executing_waypoint_queue: Bool,
    pub(super) requested_victim_id: ObjectID,
    pub(super) requested_destination: Coord3D,
    pub(super) requested_destination2: Coord3D,
    pub(super) current_path_snapshot: Option<AiPath>,
    pub(super) pathfind_goal_cell: ICoord2D,
    pub(super) pathfind_cur_cell: ICoord2D,
    pub(super) pathfind_goal_layer: ClassicPathLayer,
    /// Astar ordinals zipped with the installed waypoints. Not xfer'd. Not `AiPath`.
    pub(super) installed_path_layers: Vec<u8>,
    pub(super) move_out_of_way_1: ObjectID,
    pub(super) move_out_of_way_2: ObjectID,
    pub(super) repulsor1: ObjectID,
    pub(super) repulsor2: ObjectID,
    pub(super) ignore_obstacle_id: ObjectID,
    pub(super) ignore_collisions_until: UnsignedInt,
    pub(super) waiting_for_path: Bool,
    pub(super) queue_for_path_frame: UnsignedInt,
    pub(super) path_timestamp: UnsignedInt,
    pub(super) ai_dead: Bool,
    pub(super) is_recruitable: Bool,
    pub(super) next_enemy_scan_time: UnsignedInt,
    pub(super) final_position: Coord3D,
    pub(super) do_final_position: Bool,
    pub(super) is_attack_path: Bool,
    pub(super) is_final_goal: Bool,
    pub(super) is_approach_path: Bool,
    pub(super) is_safe_path: Bool,
    pub(super) movement_complete: Bool,
    /// C++ `m_isMoving`. Not derived from the path.
    pub(super) cpp_is_moving: bool,
    pub(super) locomotor_goal_type: u32,
    pub(super) locomotor_goal_data: Coord3D,
    pub(super) is_blocked: Bool,
    pub(super) blocked_and_stuck: Bool,
    pub(super) retry_path: Bool,
    pub(super) blocked_frames: u32,
    pub(super) cur_max_blocked_speed: Real,
    pub(super) bump_speed_limit: Real,
}
