//! Module-override installation / registration.
//! Split from `contain_module_overrides.rs`. Registered factory names stay identical.

use super::behavior::*;
use super::body::*;
use super::collide_crates::*;
use super::contain::*;
use super::death::*;
use super::draw_client::*;
use super::factory_gaps::*;
use super::helpers::*;
use super::leftover::*;
use super::production::*;
use super::template_locomotor::install_template_locomotor_applier;
use super::update_modules::*;
use super::*;
use game_engine::common::thing::thing_factory::apply_stored_locomotors_to_all_templates;

pub(super) fn install_contain_overrides() -> Result<(), String> {
    install_template_locomotor_applier();

    register_module_override(
        "InactiveBody",
        ModuleType::Behavior,
        inactive_body_module_factory,
        inactive_body_module_data_factory,
    )?;
    register_module_override(
        "ActiveBody",
        ModuleType::Behavior,
        active_body_module_factory,
        active_body_module_data_factory,
    )?;
    register_module_override(
        "StructureBody",
        ModuleType::Behavior,
        structure_body_module_factory,
        structure_body_module_data_factory,
    )?;
    register_module_override(
        "HighlanderBody",
        ModuleType::Behavior,
        highlander_body_module_factory,
        highlander_body_module_data_factory,
    )?;
    register_module_override(
        "ImmortalBody",
        ModuleType::Behavior,
        immortal_body_module_factory,
        immortal_body_module_data_factory,
    )?;
    register_module_override(
        "HiveStructureBody",
        ModuleType::Behavior,
        hive_structure_body_module_factory,
        hive_structure_body_module_data_factory,
    )?;
    register_module_override(
        "UndeadBody",
        ModuleType::Behavior,
        undead_body_module_factory,
        undead_body_module_data_factory,
    )?;
    register_module_override(
        "DestroyDie",
        ModuleType::Behavior,
        destroy_die_module_factory,
        destroy_die_module_data_factory,
    )?;
    register_module_override(
        "KeepObjectDie",
        ModuleType::Behavior,
        keep_object_die_module_factory,
        keep_object_die_module_data_factory,
    )?;
    register_module_override(
        "UpgradeDie",
        ModuleType::Behavior,
        upgrade_die_module_factory,
        upgrade_die_module_data_factory,
    )?;
    register_module_override(
        "CreateObjectDie",
        ModuleType::Behavior,
        create_object_die_module_factory,
        create_object_die_module_data_factory,
    )?;
    register_module_override(
        "CreateCrateDie",
        ModuleType::Behavior,
        create_crate_die_module_factory,
        create_crate_die_module_data_factory,
    )?;
    register_module_override(
        "FXListDie",
        ModuleType::Behavior,
        fx_list_die_module_factory,
        fx_list_die_module_data_factory,
    )?;
    register_module_override(
        "CrushDie",
        ModuleType::Behavior,
        crush_die_module_factory,
        crush_die_module_data_factory,
    )?;
    register_module_override(
        "EjectPilotDie",
        ModuleType::Behavior,
        eject_pilot_die_module_factory,
        eject_pilot_die_module_data_factory,
    )?;
    register_module_override(
        "RebuildHoleExposeDie",
        ModuleType::Behavior,
        rebuild_hole_expose_die_module_factory,
        rebuild_hole_expose_die_module_data_factory,
    )?;
    register_module_override(
        "SpecialPowerCompletionDie",
        ModuleType::Behavior,
        special_power_completion_die_module_factory,
        special_power_completion_die_module_data_factory,
    )?;
    register_module_override(
        "DamDie",
        ModuleType::Behavior,
        dam_die_module_factory,
        dam_die_module_data_factory,
    )?;
    register_module_override(
        "HelicopterSlowDeathBehavior",
        ModuleType::Behavior,
        helicopter_slow_death_module_factory,
        helicopter_slow_death_data_factory,
    )?;
    register_module_override(
        "SlowDeathBehavior",
        ModuleType::Behavior,
        slow_death_behavior_module_factory,
        slow_death_behavior_module_data_factory,
    )?;
    register_module_override(
        "PoisonedBehavior",
        ModuleType::Behavior,
        poisoned_behavior_module_factory,
        poisoned_behavior_data_factory,
    )?;
    register_module_override(
        "JetSlowDeathBehavior",
        ModuleType::Behavior,
        jet_slow_death_behavior_module_factory,
        jet_slow_death_behavior_data_factory,
    )?;
    register_module_override(
        "InstantDeathBehavior",
        ModuleType::Behavior,
        instant_death_behavior_module_factory,
        instant_death_behavior_module_data_factory,
    )?;
    register_module_override(
        "BattleBusSlowDeathBehavior",
        ModuleType::Behavior,
        battle_bus_slow_death_module_factory,
        battle_bus_slow_death_data_factory,
    )?;
    register_module_override(
        "NeutronMissileSlowDeathBehavior",
        ModuleType::Behavior,
        neutron_missile_slow_death_module_factory,
        neutron_missile_slow_death_data_factory,
    )?;
    register_module_override(
        "NeutronMissileUpdate",
        ModuleType::Behavior,
        neutron_missile_update_module_factory,
        neutron_missile_update_data_factory,
    )?;
    register_module_override(
        "ToppleUpdate",
        ModuleType::Behavior,
        topple_update_module_factory,
        topple_update_data_factory,
    )?;
    register_module_override(
        "LifetimeUpdate",
        ModuleType::Behavior,
        lifetime_update_module_factory,
        lifetime_update_data_factory,
    )?;
    register_module_override(
        "OCLUpdate",
        ModuleType::Behavior,
        ocl_update_module_factory,
        ocl_update_data_factory,
    )?;
    register_module_override(
        "RadiusDecalUpdate",
        ModuleType::Behavior,
        radius_decal_update_module_factory,
        radius_decal_update_data_factory,
    )?;
    register_module_override(
        "StickyBombUpdate",
        ModuleType::Behavior,
        sticky_bomb_update_module_factory,
        sticky_bomb_update_data_factory,
    )?;
    register_module_override(
        "DemoTrapUpdate",
        ModuleType::Behavior,
        demo_trap_update_module_factory,
        demo_trap_update_data_factory,
    )?;
    register_module_override(
        "PointDefenseLaserUpdate",
        ModuleType::Behavior,
        point_defense_laser_update_module_factory,
        point_defense_laser_update_data_factory,
    )?;
    register_module_override(
        "ProjectileStreamUpdate",
        ModuleType::Behavior,
        projectile_stream_update_module_factory,
        projectile_stream_update_data_factory,
    )?;
    register_module_override(
        "SmartBombTargetHomingUpdate",
        ModuleType::Behavior,
        smart_bomb_target_homing_update_module_factory,
        smart_bomb_target_homing_update_data_factory,
    )?;
    register_module_override(
        "TensileFormationUpdate",
        ModuleType::Behavior,
        tensile_formation_update_module_factory,
        tensile_formation_update_data_factory,
    )?;
    register_module_override(
        "AnimationSteeringUpdate",
        ModuleType::Behavior,
        animation_steering_update_module_factory,
        animation_steering_update_data_factory,
    )?;
    register_module_override(
        "AssistedTargetingUpdate",
        ModuleType::Behavior,
        assisted_targeting_update_module_factory,
        assisted_targeting_update_data_factory,
    )?;
    register_module_override(
        "AutoDepositUpdate",
        ModuleType::Behavior,
        auto_deposit_update_module_factory,
        auto_deposit_update_data_factory,
    )?;
    register_module_override(
        "AutoFindHealingUpdate",
        ModuleType::Behavior,
        auto_find_healing_update_module_factory,
        auto_find_healing_update_data_factory,
    )?;
    register_module_override(
        "BaseRegenerateUpdate",
        ModuleType::Behavior,
        base_regenerate_update_module_factory,
        base_regenerate_update_data_factory,
    )?;
    register_module_override(
        "BattlePlanUpdate",
        ModuleType::Behavior,
        battle_plan_update_module_factory,
        battle_plan_update_data_factory,
    )?;
    register_module_override(
        "CleanupHazardUpdate",
        ModuleType::Behavior,
        cleanup_hazard_update_module_factory,
        cleanup_hazard_update_data_factory,
    )?;
    register_module_override(
        "CommandButtonHuntUpdate",
        ModuleType::Behavior,
        command_button_hunt_update_module_factory,
        command_button_hunt_update_data_factory,
    )?;
    register_module_override(
        "SpyVisionUpdate",
        ModuleType::Behavior,
        spy_vision_update_module_factory,
        spy_vision_update_data_factory,
    )?;
    register_module_override(
        "SlavedUpdate",
        ModuleType::Behavior,
        slaved_update_module_factory,
        slaved_update_data_factory,
    )?;
    register_module_override(
        "MobMemberSlavedUpdate",
        ModuleType::Behavior,
        mob_member_slaved_update_module_factory,
        mob_member_slaved_update_data_factory,
    )?;
    register_module_override(
        "FireSpreadUpdate",
        ModuleType::Behavior,
        fire_spread_update_module_factory,
        fire_spread_update_data_factory,
    )?;
    register_module_override(
        "RebuildHoleBehavior",
        ModuleType::Behavior,
        rebuild_hole_behavior_module_factory,
        rebuild_hole_behavior_data_factory,
    )?;
    register_module_override(
        "OverchargeBehavior",
        ModuleType::Behavior,
        overcharge_behavior_module_factory,
        overcharge_behavior_data_factory,
    )?;
    register_module_override(
        "AutoHealBehavior",
        ModuleType::Behavior,
        auto_heal_behavior_module_factory,
        auto_heal_behavior_data_factory,
    )?;
    register_module_override(
        "CountermeasuresBehavior",
        ModuleType::Behavior,
        countermeasures_behavior_module_factory,
        countermeasures_behavior_data_factory,
    )?;
    register_module_override(
        "DumbProjectileBehavior",
        ModuleType::Behavior,
        dumb_projectile_behavior_module_factory,
        dumb_projectile_behavior_data_factory,
    )?;
    register_module_override(
        "BridgeBehavior",
        ModuleType::Behavior,
        bridge_behavior_module_factory,
        bridge_behavior_data_factory,
    )?;
    register_module_override(
        "BridgeScaffoldBehavior",
        ModuleType::Behavior,
        bridge_scaffold_behavior_module_factory,
        bridge_scaffold_behavior_data_factory,
    )?;
    register_module_override(
        "BridgeTowerBehavior",
        ModuleType::Behavior,
        bridge_tower_behavior_module_factory,
        bridge_tower_behavior_data_factory,
    )?;
    register_module_override(
        "StructureCollapseUpdate",
        ModuleType::Behavior,
        structure_collapse_update_module_factory,
        structure_collapse_update_data_factory,
    )?;
    register_module_override(
        "StructureToppleUpdate",
        ModuleType::Behavior,
        structure_topple_update_module_factory,
        structure_topple_update_data_factory,
    )?;
    register_module_override(
        "GrantStealthBehavior",
        ModuleType::Behavior,
        grant_stealth_behavior_module_factory,
        grant_stealth_behavior_data_factory,
    )?;
    register_module_override(
        "StealthUpdate",
        ModuleType::Behavior,
        stealth_update_module_factory,
        stealth_update_module_data_factory,
    )?;
    register_module_override(
        "TransitionDamageFX",
        ModuleType::Behavior,
        transition_damage_fx_module_factory,
        transition_damage_fx_module_data_factory,
    )?;
    register_module_override(
        "EMPUpdate",
        ModuleType::Behavior,
        emp_update_module_factory,
        emp_update_data_factory,
    )?;
    register_module_override(
        "BoneFXUpdate",
        ModuleType::Behavior,
        bone_fx_update_module_factory,
        bone_fx_update_data_factory,
    )?;
    register_module_override(
        "BoneFXDamage",
        ModuleType::Behavior,
        bone_fx_damage_module_factory,
        bone_fx_damage_data_factory,
    )?;
    register_module_override(
        "SpawnBehavior",
        ModuleType::Behavior,
        spawn_behavior_module_factory,
        spawn_behavior_data_factory,
    )?;
    register_module_override(
        "ParticleUplinkCannonUpdate",
        ModuleType::Behavior,
        particle_uplink_cannon_update_module_factory,
        particle_uplink_cannon_update_data_factory,
    )?;
    register_module_override(
        "DefaultProductionExitUpdate",
        ModuleType::Behavior,
        default_production_exit_update_module_factory,
        default_production_exit_update_data_factory,
    )?;
    register_module_override(
        "QueueProductionExitUpdate",
        ModuleType::Behavior,
        queue_production_exit_update_module_factory,
        queue_production_exit_update_data_factory,
    )?;
    register_module_override(
        "SpawnPointProductionExitUpdate",
        ModuleType::Behavior,
        spawn_point_production_exit_update_module_factory,
        spawn_point_production_exit_update_data_factory,
    )?;
    register_module_override(
        "SupplyCenterProductionExitUpdate",
        ModuleType::Behavior,
        supply_center_production_exit_update_module_factory,
        supply_center_production_exit_update_data_factory,
    )?;
    register_module_override(
        "FlightDeckBehavior",
        ModuleType::Behavior,
        flight_deck_behavior_module_factory,
        flight_deck_behavior_data_factory,
    )?;
    register_module_override(
        "AIUpdateInterface",
        ModuleType::Behavior,
        ai_update_interface_module_factory,
        ai_update_interface_data_factory,
    )?;
    register_module_override(
        "TransportAIUpdate",
        ModuleType::Behavior,
        transport_ai_update_module_factory,
        transport_ai_update_data_factory,
    )?;
    register_module_override(
        "DeployStyleAIUpdate",
        ModuleType::Behavior,
        deploy_style_ai_update_module_factory,
        deploy_style_ai_update_data_factory,
    )?;
    register_module_override(
        "WanderAIUpdate",
        ModuleType::Behavior,
        wander_ai_update_module_factory,
        wander_ai_update_data_factory,
    )?;
    register_module_override(
        "JetAIUpdate",
        ModuleType::Behavior,
        jet_ai_update_module_factory,
        jet_ai_update_data_factory,
    )?;
    register_module_override(
        "RailedTransportAIUpdate",
        ModuleType::Behavior,
        railed_transport_ai_update_module_factory,
        railed_transport_ai_update_data_factory,
    )?;
    register_module_override(
        "AssaultTransportAIUpdate",
        ModuleType::Behavior,
        assault_transport_ai_update_module_factory,
        assault_transport_ai_update_data_factory,
    )?;
    register_module_override(
        "DeliverPayloadAIUpdate",
        ModuleType::Behavior,
        deliver_payload_ai_update_module_factory,
        deliver_payload_ai_update_data_factory,
    )?;
    register_module_override(
        "HackInternetAIUpdate",
        ModuleType::Behavior,
        hack_internet_ai_update_module_factory,
        hack_internet_ai_update_data_factory,
    )?;
    register_module_override(
        "SupplyTruckAIUpdate",
        ModuleType::Behavior,
        supply_truck_ai_update_module_factory,
        supply_truck_ai_update_data_factory,
    )?;
    register_module_override(
        "ChinookAIUpdate",
        ModuleType::Behavior,
        chinook_ai_update_module_factory,
        chinook_ai_update_data_factory,
    )?;
    register_module_override(
        "WorkerAIUpdate",
        ModuleType::Behavior,
        worker_ai_update_module_factory,
        worker_ai_update_data_factory,
    )?;
    register_module_override(
        "DozerAIUpdate",
        ModuleType::Behavior,
        dozer_ai_update_module_factory,
        dozer_ai_update_data_factory,
    )?;
    register_module_override(
        "MissileAIUpdate",
        ModuleType::Behavior,
        missile_ai_update_module_factory,
        missile_ai_update_data_factory,
    )?;
    register_module_override(
        "PhysicsBehavior",
        ModuleType::Behavior,
        physics_behavior_module_factory,
        physics_behavior_data_factory,
    )?;
    register_module_override(
        "FlammableUpdate",
        ModuleType::Behavior,
        flammable_update_module_factory,
        flammable_update_data_factory,
    )?;
    register_module_override(
        "SpecialAbilityUpdate",
        ModuleType::Behavior,
        special_ability_update_module_factory,
        special_ability_update_data_factory,
    )?;
    register_module_override(
        "RailroadBehavior",
        ModuleType::Behavior,
        railroad_behavior_module_factory,
        railroad_behavior_data_factory,
    )?;
    register_module_override(
        "ProductionUpdate",
        ModuleType::Behavior,
        production_update_module_factory,
        production_update_data_factory,
    )?;
    register_module_override(
        "ProneUpdate",
        ModuleType::Behavior,
        prone_update_module_factory,
        prone_update_data_factory,
    )?;

    register_module_override(
        "RepairDockUpdate",
        ModuleType::Behavior,
        repair_dock_update_module_factory,
        repair_dock_update_data_factory,
    )?;
    register_module_override(
        "RailedTransportDockUpdate",
        ModuleType::Behavior,
        railed_transport_dock_update_module_factory,
        railed_transport_dock_update_data_factory,
    )?;
    register_module_override(
        "SupplyCenterDockUpdate",
        ModuleType::Behavior,
        supply_center_dock_update_module_factory,
        supply_center_dock_update_data_factory,
    )?;
    register_module_override(
        "SupplyWarehouseDockUpdate",
        ModuleType::Behavior,
        supply_warehouse_dock_update_module_factory,
        supply_warehouse_dock_update_data_factory,
    )?;
    register_module_override(
        "SupplyWarehouseCripplingBehavior",
        ModuleType::Behavior,
        supply_warehouse_crippling_behavior_module_factory,
        supply_warehouse_crippling_behavior_data_factory,
    )?;
    register_module_override(
        "ActiveShroudUpgrade",
        ModuleType::Behavior,
        active_shroud_upgrade_module_factory,
        active_shroud_upgrade_data_factory,
    )?;
    register_module_override(
        "StatusBitsUpgrade",
        ModuleType::Behavior,
        status_bits_upgrade_module_factory,
        status_bits_upgrade_data_factory,
    )?;

    register_module_override(
        "ArmorUpgrade",
        ModuleType::Behavior,
        armor_upgrade_module_factory,
        armor_upgrade_data_factory,
    )?;
    register_module_override(
        "CommandSetUpgrade",
        ModuleType::Behavior,
        command_set_upgrade_module_factory,
        command_set_upgrade_data_factory,
    )?;
    register_module_override(
        "CostModifierUpgrade",
        ModuleType::Behavior,
        cost_modifier_upgrade_module_factory,
        cost_modifier_upgrade_data_factory,
    )?;
    register_module_override(
        "ExperienceScalarUpgrade",
        ModuleType::Behavior,
        experience_scalar_upgrade_module_factory,
        experience_scalar_upgrade_data_factory,
    )?;
    register_module_override(
        "GrantScienceUpgrade",
        ModuleType::Behavior,
        grant_science_upgrade_module_factory,
        grant_science_upgrade_data_factory,
    )?;
    register_module_override(
        "LocomotorSetUpgrade",
        ModuleType::Behavior,
        locomotor_set_upgrade_module_factory,
        locomotor_set_upgrade_data_factory,
    )?;
    register_module_override(
        "MaxHealthUpgrade",
        ModuleType::Behavior,
        max_health_upgrade_module_factory,
        max_health_upgrade_data_factory,
    )?;
    register_module_override(
        "ModelConditionUpgrade",
        ModuleType::Behavior,
        model_condition_upgrade_module_factory,
        model_condition_upgrade_data_factory,
    )?;
    register_module_override(
        "ObjectCreationUpgrade",
        ModuleType::Behavior,
        object_creation_upgrade_module_factory,
        object_creation_upgrade_data_factory,
    )?;
    register_module_override(
        "PassengersFireUpgrade",
        ModuleType::Behavior,
        passengers_fire_upgrade_module_factory,
        passengers_fire_upgrade_data_factory,
    )?;
    register_module_override(
        "PowerPlantUpgrade",
        ModuleType::Behavior,
        power_plant_upgrade_module_factory,
        power_plant_upgrade_data_factory,
    )?;
    register_module_override(
        "RadarUpgrade",
        ModuleType::Behavior,
        radar_upgrade_module_factory,
        radar_upgrade_data_factory,
    )?;
    register_module_override(
        "ReplaceObjectUpgrade",
        ModuleType::Behavior,
        replace_object_upgrade_module_factory,
        replace_object_upgrade_data_factory,
    )?;
    register_module_override(
        "StealthUpgrade",
        ModuleType::Behavior,
        stealth_upgrade_module_factory,
        stealth_upgrade_data_factory,
    )?;
    register_module_override(
        "SubObjectsUpgrade",
        ModuleType::Behavior,
        subobjects_upgrade_module_factory,
        subobjects_upgrade_data_factory,
    )?;
    register_module_override(
        "UnpauseSpecialPowerUpgrade",
        ModuleType::Behavior,
        unpause_special_power_upgrade_module_factory,
        unpause_special_power_upgrade_data_factory,
    )?;
    register_module_override(
        "WeaponBonusUpgrade",
        ModuleType::Behavior,
        weapon_bonus_upgrade_module_factory,
        weapon_bonus_upgrade_data_factory,
    )?;
    register_module_override(
        "WeaponSetUpgrade",
        ModuleType::Behavior,
        weapon_set_upgrade_module_factory,
        weapon_set_upgrade_data_factory,
    )?;
    register_module_override(
        "FireWeaponCollide",
        ModuleType::Behavior,
        fire_weapon_collide_module_factory,
        fire_weapon_collide_data_factory,
    )?;
    register_module_override(
        "SquishCollide",
        ModuleType::Behavior,
        squish_collide_module_factory,
        squish_collide_data_factory,
    )?;
    register_module_override(
        "GrantUpgradeCreate",
        ModuleType::Behavior,
        grant_upgrade_create_module_factory,
        grant_upgrade_create_data_factory,
    )?;
    register_module_override(
        "LockWeaponCreate",
        ModuleType::Behavior,
        lock_weapon_create_module_factory,
        lock_weapon_create_data_factory,
    )?;
    register_module_override(
        "PreorderCreate",
        ModuleType::Behavior,
        preorder_create_module_factory,
        preorder_create_data_factory,
    )?;
    register_module_override(
        "SpecialPowerCreate",
        ModuleType::Behavior,
        special_power_create_module_factory,
        special_power_create_data_factory,
    )?;
    register_module_override(
        "SupplyCenterCreate",
        ModuleType::Behavior,
        supply_center_create_module_factory,
        supply_center_create_data_factory,
    )?;
    register_module_override(
        "SupplyWarehouseCreate",
        ModuleType::Behavior,
        supply_warehouse_create_module_factory,
        supply_warehouse_create_data_factory,
    )?;
    register_module_override(
        "VeterancyGainCreate",
        ModuleType::Behavior,
        veterancy_gain_create_module_factory,
        veterancy_gain_create_data_factory,
    )?;
    register_module_override(
        "ConvertToCarBombCrateCollide",
        ModuleType::Behavior,
        convert_to_car_bomb_crate_collide_module_factory,
        convert_to_car_bomb_crate_collide_data_factory,
    )?;
    register_module_override(
        "ConvertToHijackedVehicleCrateCollide",
        ModuleType::Behavior,
        convert_to_hijacked_vehicle_crate_collide_module_factory,
        convert_to_hijacked_vehicle_crate_collide_data_factory,
    )?;
    register_module_override(
        "HealCrateCollide",
        ModuleType::Behavior,
        heal_crate_collide_module_factory,
        heal_crate_collide_data_factory,
    )?;
    register_module_override(
        "SabotageCommandCenterCrateCollide",
        ModuleType::Behavior,
        sabotage_command_center_crate_collide_module_factory,
        sabotage_command_center_crate_collide_data_factory,
    )?;
    register_module_override(
        "SabotageFakeBuildingCrateCollide",
        ModuleType::Behavior,
        sabotage_fake_building_crate_collide_module_factory,
        sabotage_fake_building_crate_collide_data_factory,
    )?;
    register_module_override(
        "SabotageInternetCenterCrateCollide",
        ModuleType::Behavior,
        sabotage_internet_center_crate_collide_module_factory,
        sabotage_internet_center_crate_collide_data_factory,
    )?;
    register_module_override(
        "SabotageMilitaryFactoryCrateCollide",
        ModuleType::Behavior,
        sabotage_military_factory_crate_collide_module_factory,
        sabotage_military_factory_crate_collide_data_factory,
    )?;
    register_module_override(
        "SabotagePowerPlantCrateCollide",
        ModuleType::Behavior,
        sabotage_power_plant_crate_collide_module_factory,
        sabotage_power_plant_crate_collide_data_factory,
    )?;
    register_module_override(
        "SabotageSuperweaponCrateCollide",
        ModuleType::Behavior,
        sabotage_superweapon_crate_collide_module_factory,
        sabotage_superweapon_crate_collide_data_factory,
    )?;
    register_module_override(
        "SabotageSupplyCenterCrateCollide",
        ModuleType::Behavior,
        sabotage_supply_center_crate_collide_module_factory,
        sabotage_supply_center_crate_collide_data_factory,
    )?;
    register_module_override(
        "SabotageSupplyDropzoneCrateCollide",
        ModuleType::Behavior,
        sabotage_supply_dropzone_crate_collide_module_factory,
        sabotage_supply_dropzone_crate_collide_data_factory,
    )?;
    register_module_override(
        "MoneyCrateCollide",
        ModuleType::Behavior,
        money_crate_collide_module_factory,
        money_crate_collide_data_factory,
    )?;
    register_module_override(
        "SalvageCrateCollide",
        ModuleType::Behavior,
        salvage_crate_collide_module_factory,
        salvage_crate_collide_data_factory,
    )?;
    register_module_override(
        "ShroudCrateCollide",
        ModuleType::Behavior,
        shroud_crate_collide_module_factory,
        shroud_crate_collide_data_factory,
    )?;
    register_module_override(
        "UnitCrateCollide",
        ModuleType::Behavior,
        unit_crate_collide_module_factory,
        unit_crate_collide_data_factory,
    )?;
    register_module_override(
        "VeterancyCrateCollide",
        ModuleType::Behavior,
        veterancy_crate_collide_module_factory,
        veterancy_crate_collide_data_factory,
    )?;
    register_module_override(
        "BunkerBusterBehavior",
        ModuleType::Behavior,
        bunker_buster_behavior_module_factory,
        bunker_buster_behavior_data_factory,
    )?;
    register_module_override(
        "CheckpointUpdate",
        ModuleType::Behavior,
        checkpoint_update_module_factory,
        checkpoint_update_data_factory,
    )?;
    register_module_override(
        "DeletionUpdate",
        ModuleType::Behavior,
        deletion_update_module_factory,
        deletion_update_data_factory,
    )?;
    register_module_override(
        "DynamicShroudClearingRangeUpdate",
        ModuleType::Behavior,
        dynamic_shroud_clearing_range_update_module_factory,
        dynamic_shroud_clearing_range_update_data_factory,
    )?;
    register_module_override(
        "EnemyNearUpdate",
        ModuleType::Behavior,
        enemy_near_update_module_factory,
        enemy_near_update_data_factory,
    )?;
    register_module_override(
        "FireOCLAfterWeaponCooldownUpdate",
        ModuleType::Behavior,
        fire_ocl_after_weapon_cooldown_update_module_factory,
        fire_ocl_after_weapon_cooldown_update_data_factory,
    )?;
    register_module_override(
        "FireWeaponWhenDamagedBehavior",
        ModuleType::Behavior,
        fire_weapon_when_damaged_behavior_module_factory,
        fire_weapon_when_damaged_behavior_data_factory,
    )?;
    register_module_override(
        "FireWeaponWhenDeadBehavior",
        ModuleType::Behavior,
        fire_weapon_when_dead_behavior_module_factory,
        fire_weapon_when_dead_behavior_data_factory,
    )?;
    register_module_override(
        "FireWeaponUpdate",
        ModuleType::Behavior,
        fire_weapon_update_module_factory,
        fire_weapon_update_data_factory,
    )?;
    register_module_override(
        "DynamicGeometryInfoUpdate",
        ModuleType::Behavior,
        dynamic_geometry_info_update_module_factory,
        dynamic_geometry_info_update_data_factory,
    )?;

    register_module_override(
        "FirestormDynamicGeometryInfoUpdate",
        ModuleType::Behavior,
        firestorm_dynamic_geometry_info_update_module_factory,
        firestorm_dynamic_geometry_info_update_data_factory,
    )?;
    register_module_override(
        "FloatUpdate",
        ModuleType::Behavior,
        float_update_module_factory,
        float_update_data_factory,
    )?;
    register_module_override(
        "GenerateMinefieldBehavior",
        ModuleType::Behavior,
        generate_minefield_behavior_module_factory,
        generate_minefield_behavior_data_factory,
    )?;
    register_module_override(
        "MinefieldBehavior",
        ModuleType::Behavior,
        minefield_behavior_module_factory,
        minefield_behavior_data_factory,
    )?;
    register_module_override(
        "HeightDieUpdate",
        ModuleType::Behavior,
        height_die_update_module_factory,
        height_die_update_data_factory,
    )?;
    register_module_override(
        "HijackerUpdate",
        ModuleType::Behavior,
        hijacker_update_module_factory,
        hijacker_update_data_factory,
    )?;
    register_module_override(
        "HordeUpdate",
        ModuleType::Behavior,
        horde_update_module_factory,
        horde_update_data_factory,
    )?;
    register_module_override(
        "NeutronBlastBehavior",
        ModuleType::Behavior,
        neutron_blast_behavior_module_factory,
        neutron_blast_behavior_data_factory,
    )?;
    register_module_override(
        "LeafletDropBehavior",
        ModuleType::Behavior,
        leaflet_drop_behavior_module_factory,
        leaflet_drop_behavior_data_factory,
    )?;
    register_module_override(
        "MissileLauncherBuildingUpdate",
        ModuleType::Behavior,
        missile_launcher_building_update_module_factory,
        missile_launcher_building_update_data_factory,
    )?;
    register_module_override(
        "ParkingPlaceBehavior",
        ModuleType::Behavior,
        parking_place_behavior_module_factory,
        parking_place_behavior_data_factory,
    )?;
    register_module_override(
        "PilotFindVehicleUpdate",
        ModuleType::Behavior,
        pilot_find_vehicle_update_module_factory,
        pilot_find_vehicle_update_data_factory,
    )?;
    register_module_override(
        "PowerPlantUpdate",
        ModuleType::Behavior,
        power_plant_update_module_factory,
        power_plant_update_data_factory,
    )?;
    register_module_override(
        "PropagandaTowerBehavior",
        ModuleType::Behavior,
        propaganda_tower_behavior_module_factory,
        propaganda_tower_behavior_data_factory,
    )?;
    register_module_override(
        "RadarUpdate",
        ModuleType::Behavior,
        radar_update_module_factory,
        radar_update_data_factory,
    )?;
    register_module_override(
        "SpectreGunshipDeploymentUpdate",
        ModuleType::Behavior,
        spectre_gunship_deployment_update_module_factory,
        spectre_gunship_deployment_update_data_factory,
    )?;
    register_module_override(
        "SpectreGunshipUpdate",
        ModuleType::Behavior,
        spectre_gunship_update_module_factory,
        spectre_gunship_update_data_factory,
    )?;
    register_module_override(
        "StealthDetectorUpdate",
        ModuleType::Behavior,
        stealth_detector_update_module_factory,
        stealth_detector_update_data_factory,
    )?;
    register_module_override(
        "TechBuildingBehavior",
        ModuleType::Behavior,
        tech_building_behavior_module_factory,
        tech_building_behavior_data_factory,
    )?;
    register_module_override(
        "WaveGuideUpdate",
        ModuleType::Behavior,
        wave_guide_update_module_factory,
        wave_guide_update_data_factory,
    )?;
    register_module_override(
        "WeaponBonusUpdate",
        ModuleType::Behavior,
        weapon_bonus_update_module_factory,
        weapon_bonus_update_data_factory,
    )?;
    register_module_override(
        "OpenContain",
        ModuleType::Behavior,
        open_contain_module_factory,
        open_contain_module_data_factory,
    )?;
    register_module_override(
        "TransportContain",
        ModuleType::Behavior,
        transport_contain_module_factory,
        transport_contain_module_data_factory,
    )?;
    register_module_override(
        "GarrisonContain",
        ModuleType::Behavior,
        garrison_contain_module_factory,
        garrison_contain_module_data_factory,
    )?;
    register_module_override(
        "TunnelContain",
        ModuleType::Behavior,
        tunnel_contain_module_factory,
        tunnel_contain_module_data_factory,
    )?;
    register_module_override(
        "OverlordContain",
        ModuleType::Behavior,
        overlord_contain_module_factory,
        overlord_contain_module_data_factory,
    )?;
    register_module_override(
        "HelixContain",
        ModuleType::Behavior,
        helix_contain_module_factory,
        helix_contain_module_data_factory,
    )?;
    register_module_override(
        "ParachuteContain",
        ModuleType::Behavior,
        parachute_contain_module_factory,
        parachute_contain_module_data_factory,
    )?;
    register_module_override(
        "MobNexusContain",
        ModuleType::Behavior,
        mob_nexus_contain_module_factory,
        mob_nexus_contain_module_data_factory,
    )?;
    register_module_override(
        "RailedTransportContain",
        ModuleType::Behavior,
        railed_transport_contain_module_factory,
        railed_transport_contain_module_data_factory,
    )?;
    register_module_override(
        "RiderChangeContain",
        ModuleType::Behavior,
        rider_change_contain_module_factory,
        rider_change_contain_module_data_factory,
    )?;
    register_module_override(
        "InternetHackContain",
        ModuleType::Behavior,
        internet_hack_contain_module_factory,
        internet_hack_contain_module_data_factory,
    )?;
    register_module_override(
        "HealContain",
        ModuleType::Behavior,
        heal_contain_module_factory,
        heal_contain_module_data_factory,
    )?;
    register_module_override(
        "CaveContain",
        ModuleType::Behavior,
        cave_contain_module_factory,
        cave_contain_module_data_factory,
    )?;
    register_module_override(
        "W3DModelDraw",
        ModuleType::Draw,
        w3d_model_draw_module_factory,
        w3d_model_draw_module_data_factory,
    )?;
    register_module_override(
        "W3DDefaultDraw",
        ModuleType::Draw,
        w3d_default_draw_module_factory,
        w3d_default_draw_module_data_factory,
    )?;
    register_module_override(
        "W3DDependencyModelDraw",
        ModuleType::Draw,
        w3d_dependency_model_draw_module_factory,
        w3d_dependency_model_draw_module_data_factory,
    )?;
    register_module_override(
        "W3DTankDraw",
        ModuleType::Draw,
        w3d_tank_draw_module_factory,
        w3d_tank_draw_module_data_factory,
    )?;
    register_module_override(
        "W3DOverlordTankDraw",
        ModuleType::Draw,
        w3d_overlord_tank_draw_module_factory,
        w3d_overlord_tank_draw_module_data_factory,
    )?;
    register_module_override(
        "W3DOverlordAircraftDraw",
        ModuleType::Draw,
        w3d_overlord_aircraft_draw_module_factory,
        w3d_overlord_aircraft_draw_module_data_factory,
    )?;
    register_module_override(
        "W3DOverlordTruckDraw",
        ModuleType::Draw,
        w3d_overlord_truck_draw_module_factory,
        w3d_overlord_truck_draw_module_data_factory,
    )?;
    register_module_override(
        "W3DPoliceCarDraw",
        ModuleType::Draw,
        w3d_police_car_draw_module_factory,
        w3d_police_car_draw_module_data_factory,
    )?;
    register_module_override(
        "W3DProjectileStreamDraw",
        ModuleType::Draw,
        w3d_projectile_stream_draw_module_factory,
        w3d_projectile_stream_draw_module_data_factory,
    )?;
    register_module_override(
        "W3DRopeDraw",
        ModuleType::Draw,
        w3d_rope_draw_module_factory,
        w3d_rope_draw_module_data_factory,
    )?;
    register_module_override(
        "W3DScienceModelDraw",
        ModuleType::Draw,
        w3d_science_model_draw_module_factory,
        w3d_science_model_draw_module_data_factory,
    )?;
    register_module_override(
        "W3DSupplyDraw",
        ModuleType::Draw,
        w3d_supply_draw_module_factory,
        w3d_supply_draw_module_data_factory,
    )?;
    register_module_override(
        "W3DTankTruckDraw",
        ModuleType::Draw,
        w3d_tank_truck_draw_module_factory,
        w3d_tank_truck_draw_module_data_factory,
    )?;
    register_module_override(
        "W3DTracerDraw",
        ModuleType::Draw,
        w3d_tracer_draw_module_factory,
        w3d_tracer_draw_module_data_factory,
    )?;
    register_module_override(
        "W3DTreeDraw",
        ModuleType::Draw,
        w3d_tree_draw_module_factory,
        w3d_tree_draw_module_data_factory,
    )?;
    // C++ W3DModuleFactory.cpp:56 addModule(W3DPropDraw)
    register_module_override(
        "W3DPropDraw",
        ModuleType::Draw,
        w3d_prop_draw_module_factory,
        w3d_prop_draw_module_data_factory,
    )?;
    register_module_override(
        "W3DTruckDraw",
        ModuleType::Draw,
        w3d_truck_draw_module_factory,
        w3d_truck_draw_module_data_factory,
    )?;
    register_module_override(
        "W3DLaserDraw",
        ModuleType::Draw,
        w3d_laser_draw_module_factory,
        w3d_laser_draw_module_data_factory,
    )?;
    register_module_override(
        "W3DDebrisDraw",
        ModuleType::Draw,
        w3d_debris_draw_module_factory,
        w3d_debris_draw_module_data_factory,
    )?;
    register_module_override(
        "LaserUpdate",
        ModuleType::ClientUpdate,
        laser_update_module_factory,
        laser_update_module_data_factory,
    )?;
    register_module_override(
        "BeaconClientUpdate",
        ModuleType::ClientUpdate,
        beacon_client_update_module_factory,
        beacon_client_update_module_data_factory,
    )?;
    register_module_override(
        "SwayClientUpdate",
        ModuleType::ClientUpdate,
        sway_client_update_module_factory,
        base_client_update_module_data_factory,
    )?;
    register_module_override(
        "AnimatedParticleSysBoneClientUpdate",
        ModuleType::ClientUpdate,
        animated_particle_sys_bone_client_update_module_factory,
        base_client_update_module_data_factory,
    )?;
    register_module_override(
        "BaikonurLaunchPower",
        ModuleType::Behavior,
        baikonur_launch_power_module_factory,
        baikonur_launch_power_module_data_factory,
    )?;
    register_module_override(
        "CashBountyPower",
        ModuleType::Behavior,
        cash_bounty_power_module_factory,
        cash_bounty_power_module_data_factory,
    )?;
    register_module_override(
        "CashHackSpecialPower",
        ModuleType::Behavior,
        cash_hack_special_power_module_factory,
        cash_hack_special_power_module_data_factory,
    )?;
    register_module_override(
        "CleanupAreaPower",
        ModuleType::Behavior,
        cleanup_area_power_module_factory,
        cleanup_area_power_module_data_factory,
    )?;
    register_module_override(
        "FireWeaponPower",
        ModuleType::Behavior,
        fire_weapon_power_module_factory,
        fire_weapon_power_module_data_factory,
    )?;
    register_module_override(
        "OCLSpecialPower",
        ModuleType::Behavior,
        ocl_special_power_module_factory,
        ocl_special_power_module_data_factory,
    )?;
    register_module_override(
        "SpecialAbility",
        ModuleType::Behavior,
        special_ability_module_factory,
        special_ability_module_data_factory,
    )?;
    register_module_override(
        "SpyVisionSpecialPower",
        ModuleType::Behavior,
        spy_vision_special_power_module_factory,
        spy_vision_special_power_module_data_factory,
    )?;
    register_module_override(
        "DefectorSpecialPower",
        ModuleType::Behavior,
        defector_special_power_module_factory,
        defector_special_power_module_data_factory,
    )?;
    apply_stored_locomotors_to_all_templates();
    Ok(())
}

static CONTAIN_OVERRIDES_READY: OnceLock<Result<(), String>> = OnceLock::new();

pub fn ensure_module_overrides_installed() -> Result<(), String> {
    CONTAIN_OVERRIDES_READY
        .get_or_init(|| {
            install_contain_overrides()?;
            apply_module_overrides_to_existing_templates()?;
            Ok(())
        })
        .clone()
}
