[package]
name = "ww3d-render-2d"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
ww3d-renderer-3d = { path = "../ww3d-renderer-3d" }
ww3d-assets = { path = "../ww3d-assets" }
glam = {workspace = true, features = ["bytemuck"]}
wgpu = {workspace = true}
tokio = {workspace = true, features = ["full"]}
bytemuck = {workspace = true, features = ["derive"]}
thiserror = {workspace = true}
anyhow = {workspace = true}
ab_glyph = {workspace = true}
image = {workspace = true, features = ["png", "jpeg", "tga", "bmp"]}
