//! Legacy D3D/W3D constants used by the C API compatibility layer.
//!
//! Split from `w3d_c_api.rs`.

use bytemuck::{Pod, Zeroable};
use glam::{Mat4, Vec3, Vec4};
use std::collections::{HashMap, hash_map::DefaultHasher};
use std::ffi::{CStr, CString, c_char, c_void};
use std::hash::{Hash, Hasher};
use std::path::{Path, PathBuf};
use std::ptr::null_mut;
use std::sync::Arc;
use std::sync::Mutex;
use tokio::sync::RwLock;

// Global device instance for C compatibility
pub(super) static GLOBAL_W3D_DEVICE: std::sync::Mutex<Option<usize>> = std::sync::Mutex::new(None);
pub(super) const TEMP_MESH_PREFIX: &str = "__w3d_c_api_temp_";
pub(super) const TEMP_MESH_RING_SIZE: u64 = 4096;
pub(super) const D3DFVF_XYZ: u32 = 0x002;
pub(super) const D3DFVF_XYZRHW: u32 = 0x004;
pub(super) const D3DFVF_NORMAL: u32 = 0x010;
pub(super) const D3DFVF_DIFFUSE: u32 = 0x040;
pub(super) const D3DFVF_SPECULAR: u32 = 0x080;
pub(super) const D3DFVF_TEXCOUNT_MASK: u32 = 0xF00;
pub(super) const D3DFVF_TEXCOUNT_SHIFT: u32 = 8;
pub(super) const D3DFVF_TEXCOORDFORMAT_MASK: u32 = 0x3;
pub(super) const D3DFVF_TEXCOORDFORMAT_SHIFT: u32 = 16;
pub(super) const DEFAULT_FVF_TL1: u32 =
    D3DFVF_XYZRHW | D3DFVF_DIFFUSE | D3DFVF_SPECULAR | (1 << D3DFVF_TEXCOUNT_SHIFT);
pub(super) const D3DFMT_INDEX16: u32 = 101;
pub(super) const D3DFMT_INDEX32: u32 = 102;
pub(super) const D3DDECLTYPE_FLOAT1: u8 = 0;
pub(super) const D3DDECLTYPE_FLOAT2: u8 = 1;
pub(super) const D3DDECLTYPE_FLOAT3: u8 = 2;
pub(super) const D3DDECLTYPE_FLOAT4: u8 = 3;
pub(super) const D3DDECLTYPE_D3DCOLOR: u8 = 4;
pub(super) const D3DDECLTYPE_UBYTE4: u8 = 5;
pub(super) const D3DDECLTYPE_SHORT2: u8 = 6;
pub(super) const D3DDECLTYPE_SHORT4: u8 = 7;
pub(super) const D3DDECLTYPE_UBYTE4N: u8 = 8;
pub(super) const D3DDECLTYPE_SHORT2N: u8 = 9;
pub(super) const D3DDECLTYPE_SHORT4N: u8 = 10;
pub(super) const D3DDECLTYPE_USHORT2N: u8 = 11;
pub(super) const D3DDECLTYPE_USHORT4N: u8 = 12;
pub(super) const D3DDECLTYPE_UDEC3: u8 = 13;
pub(super) const D3DDECLTYPE_DEC3N: u8 = 14;
pub(super) const D3DDECLTYPE_UNUSED: u8 = 17;
pub(super) const D3DDECLUSAGE_POSITION: u8 = 0;
pub(super) const D3DDECLUSAGE_NORMAL: u8 = 3;
pub(super) const D3DDECLUSAGE_TEXCOORD: u8 = 5;
pub(super) const D3DDECLUSAGE_POSITIONT: u8 = 9;
pub(super) const D3DDECLUSAGE_COLOR: u8 = 10;
pub(super) const D3DTSS_COLOROP: u32 = 1;
pub(super) const D3DTSS_COLORARG1: u32 = 2;
pub(super) const D3DTSS_COLORARG2: u32 = 3;
pub(super) const D3DTSS_ALPHAOP: u32 = 4;
pub(super) const D3DTSS_ALPHAARG1: u32 = 5;
pub(super) const D3DTSS_ALPHAARG2: u32 = 6;
pub(super) const D3DMCS_MATERIAL: u32 = 0;
pub(super) const D3DMCS_COLOR1: u32 = 1;
pub(super) const D3DMCS_COLOR2: u32 = 2;
pub(super) const D3DTSS_COLORARG0: u32 = 26;
pub(super) const D3DTSS_ALPHAARG0: u32 = 27;
pub(super) const D3DTSS_TEXCOORDINDEX: u32 = 11;
pub(super) const D3DTSS_TEXTURETRANSFORMFLAGS: u32 = 24;
pub(super) const D3DTSS_TCI_PASSTHRU: u32 = 0x0000_0000;
pub(super) const D3DTSS_TCI_CAMERASPACENORMAL: u32 = 0x0001_0000;
pub(super) const D3DTSS_TCI_CAMERASPACEPOSITION: u32 = 0x0002_0000;
pub(super) const D3DTSS_TCI_CAMERASPACEREFLECTIONVECTOR: u32 = 0x0003_0000;
pub(super) const D3DTSS_TCI_SPHEREMAP: u32 = 0x0004_0000;
pub(super) const D3DTSS_TCI_MASK: u32 = 0xFFFF_0000;
pub(super) const D3DTOP_DISABLE: u32 = 1;
pub(super) const D3DTOP_SELECTARG1: u32 = 2;
pub(super) const D3DTOP_SELECTARG2: u32 = 3;
pub(super) const D3DTOP_MODULATE: u32 = 4;
pub(super) const D3DTOP_MODULATE2X: u32 = 5;
pub(super) const D3DTOP_MODULATE4X: u32 = 6;
pub(super) const D3DTOP_ADD: u32 = 7;
pub(super) const D3DTOP_ADDSIGNED: u32 = 8;
pub(super) const D3DTOP_ADDSIGNED2X: u32 = 9;
pub(super) const D3DTOP_SUBTRACT: u32 = 10;
pub(super) const D3DTOP_ADDSMOOTH: u32 = 11;
pub(super) const D3DTOP_BLENDDIFFUSEALPHA: u32 = 12;
pub(super) const D3DTOP_BLENDTEXTUREALPHA: u32 = 13;
pub(super) const D3DTOP_BLENDFACTORALPHA: u32 = 14;
pub(super) const D3DTOP_BLENDTEXTUREALPHAPM: u32 = 15;
pub(super) const D3DTOP_BLENDCURRENTALPHA: u32 = 16;
pub(super) const D3DTOP_PREMODULATE: u32 = 17;
pub(super) const D3DTOP_MODULATEALPHA_ADDCOLOR: u32 = 18;
pub(super) const D3DTOP_MODULATECOLOR_ADDALPHA: u32 = 19;
pub(super) const D3DTOP_MODULATEINVALPHA_ADDCOLOR: u32 = 20;
pub(super) const D3DTOP_MODULATEINVCOLOR_ADDALPHA: u32 = 21;
pub(super) const D3DTOP_BUMPENVMAP: u32 = 22;
pub(super) const D3DTOP_BUMPENVMAPLUMINANCE: u32 = 23;
pub(super) const D3DTOP_DOTPRODUCT3: u32 = 24;
pub(super) const D3DTOP_MULTIPLYADD: u32 = 25;
pub(super) const D3DTOP_LERP: u32 = 26;
pub(super) const D3DTA_SELECTMASK: u32 = 0xF;
pub(super) const D3DTA_DIFFUSE: u32 = 0x0;
pub(super) const D3DTA_CURRENT: u32 = 0x1;
pub(super) const D3DTA_TEXTURE: u32 = 0x2;
pub(super) const D3DTA_TFACTOR: u32 = 0x3;
pub(super) const D3DTA_SPECULAR: u32 = 0x4;
pub(super) const D3DTA_TEMP: u32 = 0x5;
pub(super) const D3DTA_COMPLEMENT: u32 = 0x10;
pub(super) const D3DTA_ALPHAREPLICATE: u32 = 0x20;
pub(super) const D3DCULL_NONE: u32 = 1;
pub(super) const D3DTTFF_DISABLE: u32 = 0;
pub(super) const D3DTTFF_COUNT_MASK: u32 = 0xF;
pub(super) const D3DTTFF_COUNT1: u32 = 1;
pub(super) const D3DTTFF_COUNT2: u32 = 2;
pub(super) const D3DTTFF_COUNT3: u32 = 3;
pub(super) const D3DTTFF_COUNT4: u32 = 4;
pub(super) const D3DTTFF_PROJECTED: u32 = 256;
