#ifndef __FTPDEFS_H_INCLUDED__
#define __FTPDEFS_H_INCLUDED__


// CFtp return codes.

#define FTP_SUCCEEDED		S_OK
#define	FTP_FAILED			MAKE_HRESULT( SEVERITY_ERROR, FACILITY_ITF, 1 )
#define FTP_TRYING			MAKE_HRESULT( SEVERITY_ERROR, FACILITY_ITF, 2 )


#endif
