#ifndef NETUTILDEFS_HEADER
#define NETUTILDEFS_HEADER


#define NETUTIL_E_ERROR       MAKE_HRESULT( SEVERITY_ERROR, FACILITY_ITF, 100)
#define NETUTIL_E_BUSY        MAKE_HRESULT( SEVERITY_ERROR, FACILITY_ITF, 101)
#define NETUTIL_E_TIMEOUT     MAKE_HRESULT( SEVERITY_ERROR, FACILITY_ITF, 102)

#define NETUTIL_E_INVALIDFIELD  MAKE_HRESULT( SEVERITY_ERROR, FACILITY_ITF, 256)
#define NETUTIL_E_CANTVERIFY    MAKE_HRESULT( SEVERITY_ERROR, FACILITY_ITF, 257)

#define NETUTIL_S_FINISHED    MAKE_HRESULT( SEVERITY_SUCCESS, FACILITY_ITF, 500)

#endif
